-- BMI範囲マスタ
CREATE TABLE BMI_RANGE_MT (
-- BMI範囲ID
BMI_RANGE_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
-- 範囲下限
RANGE_MIN INT,
-- 範囲上限
RANGE_MAX INT,
-- 肥満度ステータス
OVER_WEIGHT_STATUS VARCHAR(2),
-- 更新日時
UPDATE_DATE TIMESTAMP,
-- 登録日時
REG_DATE TIMESTAMP
);
