CREATE TABLE HEALTH_INFO_FILE_SETTING (
-- ユーザID
USER_ID VARCHAR(16) NOT NULL PRIMARY KEY,
-- ヘッダーフラグ
HEADER_FLAG VARCHAR(1),
-- フッターフラグ
FOOTER_FLAG VARCHAR(1),
-- マスクフラグ
MASK_FLAG VARCHAR(1),
-- 囲い文字利用フラグ
ENCLOSURE_CHAR_FLAG VARCHAR(1),
-- 更新日時
UPDATE_DATE TIMESTAMP,
-- 登録日時
REG_DATE TIMESTAMP
);
