CREATE TABLE HEALTH_INFO (
-- 健康情報ID
HEALTH_INFO_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
-- ユーザID
USER_ID VARCHAR(16),
-- 身長
HEIGHT DECIMAL(6, 3),
-- 体重
WEIGHT DECIMAL(6, 3),
-- BMI
BMI DECIMAL(6, 3),
-- 標準体重
STANDARD_WEIGHT DECIMAL(6, 3),
-- ユーザステータス
USER_STATUS VARCHAR(2),
-- 更新日時
UPDATE_DATE TIMESTAMP,
-- 登録日時
REG_DATE TIMESTAMP
);
