<template>
  <div>
    <v-row justify="center">
      <v-col class="text-center" sm="12" md="12">
        <AppBreadCrumbs :items="breadcrumbs" />
      </v-col>
    </v-row>
    <v-row justify="center">
      <v-col class="text-left" sm="12" md="12">
        <AppContentsTitle :title="breadcrumbs[breadcrumbs.length - 1].text" />
      </v-col>
    </v-row>
    <v-row justify="center" align="center">
      <v-col sm="12" md="12">
        <AppBaseIF :ifs="ifs" />
      </v-col>
    </v-row>
  </div>
</template>

<script>
import AppBreadCrumbs from "~/components/AppBreadCrumbs.vue";
import AppContentsTitle from "~/components/AppContentsTitle.vue";
import AppBaseIF from "~/components/AppBaseIF.vue";

export default {
  // RootAPIのレイアウトを適用
  layout: "rootApiLayout",
  components: {
    AppBreadCrumbs,
    AppContentsTitle,
    AppBaseIF,
  },
  data: function () {
    return {
      breadcrumbs: [
        {
          text: "Top",
          disabled: false,
          href: "/",
        },
        {
          text: "管理者サイト用API",
          disabled: false,
          href: "/root/api",
        },
        {
          text: "IF一覧",
          disabled: true,
          href: "/root/api/interface",
        },
      ],
      ifs: [
        {
          name: "ヘルスチェックAPI",
          endpoint: "/api/root/healthcheck",
          httpMethod: "GET",
          description: "Root APIサーバの起動状態を確認するAPI",
          url: "/root/api/healthcheck",
          request: [],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
          ],
        },

        {
          name: "ログインAPI",
          endpoint: "/api/root/login",
          httpMethod: "POST",
          description: "管理者サイトへログインするためのAPI",
          url: "/root/api/login",
          request: [
            {
              physicalName: "seq_login_id",
              logicalName: "ログインID",
              required: true,
              type: "半角数字",
              byte: null,
              description: null,
            },
            {
              physicalName: "password",
              logicalName: "パスワード",
              required: true,
              type: null,
              byte: null,
              description: null,
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "token",
              logicalName: "トークン",
              required: false,
              type: "半角英数記号",
              byte: null,
              description: "result='0'の場合、必須",
            },
          ],
        },

        {
          name: "Top情報取得API",
          endpoint: "/api/root/top",
          httpMethod: "GET",
          description: "管理サイトTop画面情報の取得を行うAPI",
          url: "/root/api/top",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "date",
              logicalName: "対象年月",
              required: false,
              type: "YYYYMM",
              byte: null,
              description: "取得対象のTOP情報の年月を指定",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "health_info_reg_graph_list",
              logicalName: "健康情報登録グラフ情報リスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0' かつ データが存在する場合、必須",
            },
            {
              physicalName: "count",
              logicalName: "登録件数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "該当年月の登録件数",
            },
            {
              physicalName: "date",
              logicalName: "登録日",
              required: false,
              type: "YYYY/MM/DD",
              layer: 1,
              byte: null,
              description: "該当年月日",
            },
            {
              physicalName: "account_reg_graph_list",
              logicalName: "アカウント登録グラフ情報リスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0' かつ データが存在する場合、必須",
            },
            {
              physicalName: "count",
              logicalName: "登録件数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "該当年月の登録件数",
            },
            {
              physicalName: "date",
              logicalName: "登録日",
              required: false,
              type: "YYYY/MM/DD",
              layer: 1,
              byte: null,
              description: "該当年月日",
            },
          ],
        },

        {
          name: "Top情報(健康情報)取得API",
          endpoint: "/api/root/top/healthinfo",
          httpMethod: "GET",
          description: "管理サイトTop画面情報の取得を行うAPI",
          url: "/root/api/top/healthinfo",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "date",
              logicalName: "対象年月",
              required: false,
              type: "YYYYMM",
              byte: null,
              description: "取得対象のTOP情報の年月を指定",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "health_info_reg_graph_list",
              logicalName: "健康情報登録グラフ情報リスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0' かつ データが存在する場合、必須",
            },
            {
              physicalName: "count",
              logicalName: "登録件数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "該当年月の登録件数",
            },
            {
              physicalName: "date",
              logicalName: "登録日",
              required: false,
              type: "YYYY/MM/DD",
              layer: 1,
              byte: null,
              description: "該当年月日",
            },
          ],
        },

        {
          name: "Top情報(アカウント情報)取得API",
          endpoint: "/api/root/top/acount",
          httpMethod: "GET",
          description: "管理サイトTop画面情報の取得を行うAPI",
          url: "/root/api/top/acount",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "date",
              logicalName: "対象年月",
              required: false,
              type: "YYYYMM",
              byte: null,
              description: "取得対象のTOP情報の年月を指定",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "account_reg_graph_list",
              logicalName: "アカウント登録グラフ情報リスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0' かつ データが存在する場合、必須",
            },
            {
              physicalName: "count",
              logicalName: "登録件数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "該当年月の登録件数",
            },
            {
              physicalName: "date",
              logicalName: "登録日",
              required: false,
              type: "YYYY/MM/DD",
              layer: 1,
              byte: null,
              description: "該当年月日",
            },
          ],
        },

        {
          name: "ユーザ取得API",
          endpoint: "/api/root/user/{seq_login_id}",
          httpMethod: "GET",
          description: "管理サイトユーザ情報の取得を行うAPI",
          url: "/root/api/user",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "seq_login_id",
              logicalName: "ログインID",
              required: false,
              type: "半角数字",
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "roles",
              logicalName: "権限リスト",
              required: false,
              type: "配列",
              byte: null,
              description: "ユーザに紐づく権限のリスト",
            },
            {
              physicalName: "label",
              logicalName: "権限名",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: null,
            },
            {
              physicalName: "value",
              logicalName: "値",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: null,
            },
            {
              physicalName: "delete_flag",
              logicalName: "削除フラグ",
              required: false,
              type: "半角数字",
              byte: null,
              description:
                "result='0'の場合、必須<br><ul><li>0:未削除</li><li>1:削除済</li></ul>",
            },
            {
              physicalName: "password_expire",
              logicalName: "パスワード有効期限",
              required: false,
              type: "YYYY/MM/DD",
              byte: null,
              description:
                "result='0'の場合、必須<br>該当ユーザのパスワード有効期限",
            },
            {
              physicalName: "remarks",
              logicalName: "備考",
              required: false,
              type: null,
              byte: null,
              description:
                "result='0' かつ データが存在する場合、必須<br>該当ユーザの備考",
            },
          ],
        },

        {
          name: "ユーザ作成API",
          endpoint: "/api/root/user/",
          httpMethod: "POST",
          description: "管理サイトユーザの作成を行うAPI",
          url: "/root/api/user/entry",
          headers: [
            {
              key: "Content-Type",
              value: "application/json",
            },
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "password",
              logicalName: "パスワード",
              required: true,
              type: null,
              byte: null,
              description: null,
            },
            {
              physicalName: "conf_password",
              logicalName: "確認用パスワード",
              required: true,
              type: null,
              byte: null,
              description: null,
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "seq_login_id",
              logicalName: "ログインID",
              required: false,
              type: "半角数字",
              byte: null,
              description: "result='0'の場合、必須",
            },
          ],
        },

        {
          name: "ユーザ編集API",
          endpoint: "/api/root/user/{seq_login_id}",
          httpMethod: "PUT",
          description: "管理サイトユーザの編集を行うAPI",
          url: "/root/api/user/edit",
          headers: [
            {
              key: "Content-Type",
              value: "application/json",
            },
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "roles",
              logicalName: "権限リスト",
              required: true,
              type: "配列",
              byte: null,
              description: "権限のリスト",
            },
            {
              physicalName: "delete_flag",
              logicalName: "削除フラグ",
              required: true,
              type: "真偽値",
              byte: null,
              description:
                "<ul><li>true:削除する</li><li>false:削除しない</li></ul>",
            },
            {
              physicalName: "password",
              logicalName: "パスワード",
              required: true,
              type: null,
              byte: null,
              description: "更新後のパスワード",
            },
            {
              physicalName: "password_expire",
              logicalName: "パスワード有効期限",
              required: true,
              type: "YYYY/MM/DD",
              byte: null,
              description: "更新後のパスワード有効期限",
            },
            {
              physicalName: "remarks",
              logicalName: "備考",
              required: true,
              type: null,
              byte: null,
              description: "更新後の備考",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
          ],
        },

        {
          name: "アカウント情報一覧取得API",
          endpoint: "/api/root/account",
          httpMethod: "GET",
          description: "健康管理アプリのユーザの一覧を取得するAPI",
          url: "/root/api/account",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "page",
              logicalName: "ページ数",
              required: true,
              type: "半角数字",
              byte: null,
              description: "取得対象ページ数",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "paging",
              logicalName: "ページング情報",
              required: false,
              type: null,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "total_record_num",
              logicalName: "合計レコード数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "合計レコード数",
            },
            {
              physicalName: "from_record_num",
              logicalName: "レコード数(from)",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード開始番号",
            },
            {
              physicalName: "to_record_num",
              logicalName: "レコード数(to)",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード終了番号",
            },
            {
              physicalName: "total_page",
              logicalName: "総ページ数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード終了番号",
            },
            {
              physicalName: "current_page_num",
              logicalName: "現在のページ数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "現在のページ数",
            },
            {
              physicalName: "record_per_page",
              logicalName: "1ページあたりのレコード数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "1ページあたりのレコード数",
            },
            {
              physicalName: "can_go_next",
              logicalName: "次リンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "次リンク押下できるかどうか",
            },
            {
              physicalName: "next_href",
              logicalName: "次リンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "次リンクのhref属性",
            },
            {
              physicalName: "can_go_previous",
              logicalName: "前リンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "前リンク押下できるかどうか",
            },
            {
              physicalName: "previous_href",
              logicalName: "前リンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "前リンクのhref属性",
            },
            {
              physicalName: "can_go_last",
              logicalName: "最後ページまでのリンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "最後ページまでのリンクを押下できるかどうか",
            },
            {
              physicalName: "last_href",
              logicalName: "最後ページリンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "最後ページリンクのhref属性",
            },
            {
              physicalName: "can_go_first",
              logicalName: "先頭ページまでのリンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "先頭ページまでのリンクを押下できるかどうか",
            },
            {
              physicalName: "first_href",
              logicalName: "先頭ページリンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "先頭ページリンクのhref属性",
            },
            {
              physicalName: "account_list",
              logicalName: "アカウント情報リスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0' かつ データが存在する場合、必須",
            },
            {
              physicalName: "seq_user_id",
              logicalName: "ユーザID",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "ユーザを一意に識別するID",
            },
            {
              physicalName: "mail_address",
              logicalName: "メールアドレス",
              required: false,
              type: "メールアドレス",
              layer: 1,
              byte: null,
              description: "ユーザが登録しているメールアドレス",
            },
            {
              physicalName: "delete_flag",
              logicalName: "削除フラグ",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: 1,
              description: "<ul><li>0:未削除</li><li>1:削除済</li></ul>",
            },
            {
              physicalName: "password_expire",
              logicalName: "パスワード有効期限",
              required: false,
              type: "YYYY/MM/DD",
              layer: 1,
              byte: null,
              description: "ユーザのパスワード有効期限",
            },
            {
              physicalName: "remarks",
              logicalName: "備考",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "ユーザの登録している備考情報",
            },
            {
              physicalName: "api_key",
              logicalName: "APIキー",
              required: false,
              type: null,
              layer: 1,
              byte: 64,
              description:
                "ユーザの登録しているAPIキー<br>健康管理APIを実行する際ヘッダーに指定する",
            },
            {
              physicalName: "reg_date",
              logicalName: "登録日時",
              required: false,
              type: "YYYY/MM/DD HH:MM:SS",
              layer: 1,
              byte: null,
              description: "ユーザのアカウント情報を登録した日時",
            },
            {
              physicalName: "update_date",
              logicalName: "更新日時",
              required: false,
              type: "YYYY/MM/DD HH:MM:SS",
              layer: 1,
              byte: null,
              description: "ユーザのアカウント情報を更新した日時",
            },
            {
              physicalName: "header_flag",
              logicalName: "ヘッダ利用有無フラグ",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: 1,
              description:
                "<ul><li>0:ヘッダーをファイルに表示しない</li><li>1:ヘッダーをファイルに表示する</li></ul>",
            },
            {
              physicalName: "footer_flag",
              logicalName: "フッタ利用有無フラグ",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: 1,
              description:
                "<ul><li>0:フッターをファイルに表示しない</li><li>1:フッターをファイルに表示する</li></ul>",
            },
            {
              physicalName: "mask_flag",
              logicalName: "マスク利用有無フラグ",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: 1,
              description:
                "<ul><li>0:マスク表示しない</li><li>1:マスク表示する</li></ul>",
            },
            {
              physicalName: "enclosure_char_flag",
              logicalName: "囲み文字利用有無フラグ",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: 1,
              description:
                "<ul><li>0:ヘッダーをファイルに表示しない</li><li>1:ヘッダーをファイルに表示する</li></ul>",
            },
          ],
        },

        {
          name: "アカウント情報編集API",
          endpoint: "/api/root/account/{seq_user_id}",
          httpMethod: "PUT",
          description: "健康管理アプリのユーザを編集するAPI",
          url: "/root/api/account/edit",
          headers: [
            {
              key: "Content-Type",
              value: "application/json",
            },
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "mail_address",
              logicalName: "メールアドレス",
              required: true,
              type: null,
              layer: 1,
              byte: 64,
              description: "更新したいメールアドレスを指定",
            },
            {
              physicalName: "password_expire",
              logicalName: "パスワード有効期限",
              required: true,
              type: "YYYY/MM/DD",
              layer: 1,
              byte: null,
              description: "更新したいパスワード有効期限を指定",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
          ],
        },

        {
          name: "API通信ログ一覧取得API",
          endpoint: "/api/root/apidata",
          httpMethod: "GET",
          description: "健康管理APIの実行履歴一覧を取得するAPI",
          url: "/root/api/apidata",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "page",
              logicalName: "ページ数",
              required: true,
              type: "半角数字",
              byte: null,
              description: "取得対象ページ数",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "paging",
              logicalName: "ページング情報",
              required: false,
              type: null,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "total_record_num",
              logicalName: "合計レコード数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "合計レコード数",
            },
            {
              physicalName: "from_record_num",
              logicalName: "レコード数(from)",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード開始番号",
            },
            {
              physicalName: "to_record_num",
              logicalName: "レコード数(to)",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード終了番号",
            },
            {
              physicalName: "total_page",
              logicalName: "総ページ数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード終了番号",
            },
            {
              physicalName: "current_page_num",
              logicalName: "現在のページ数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "現在のページ数",
            },
            {
              physicalName: "record_per_page",
              logicalName: "1ページあたりのレコード数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "1ページあたりのレコード数",
            },
            {
              physicalName: "can_go_next",
              logicalName: "次リンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "次リンク押下できるかどうか",
            },
            {
              physicalName: "next_href",
              logicalName: "次リンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "次リンクのhref属性",
            },
            {
              physicalName: "can_go_previous",
              logicalName: "前リンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "前リンク押下できるかどうか",
            },
            {
              physicalName: "previous_href",
              logicalName: "前リンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "前リンクのhref属性",
            },
            {
              physicalName: "can_go_last",
              logicalName: "最後ページまでのリンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "最後ページまでのリンクを押下できるかどうか",
            },
            {
              physicalName: "last_href",
              logicalName: "最後ページリンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "最後ページリンクのhref属性",
            },
            {
              physicalName: "can_go_first",
              logicalName: "先頭ページまでのリンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "先頭ページまでのリンクを押下できるかどうか",
            },
            {
              physicalName: "first_href",
              logicalName: "先頭ページリンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "先頭ページリンクのhref属性",
            },
            {
              physicalName: "api_log_list",
              logicalName: "API通信ログリスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0' かつ データが存在する場合、必須",
            },
            {
              physicalName: "seq_api_log_id",
              logicalName: "API通信ログID",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "API実行履歴を一意に識別するID",
            },
            {
              physicalName: "transaction_id",
              logicalName: "トランザクションID",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "API実行履歴を処理単位で一意に識別するID",
            },
            {
              physicalName: "api_name",
              logicalName: "API名",
              required: false,
              type: null,
              layer: 1,
              byte: 64,
              description: null,
            },
            {
              physicalName: "seq_user_id",
              logicalName: "ユーザID",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "ユーザを一意にするID",
            },
            {
              physicalName: "remarks",
              logicalName: "備考",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "ユーザの登録している備考情報",
            },
            {
              physicalName: "http_status",
              logicalName: "HTTPステータス",
              required: false,
              type: null,
              layer: 1,
              byte: 3,
              description: null,
            },
            {
              physicalName: "result",
              logicalName: "API処理結果",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "APIの処理結果",
            },
            {
              physicalName: "detail",
              logicalName: "詳細",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "API実行時のエラー内容",
            },
            {
              physicalName: "request_date",
              logicalName: "APIリクエスト日時",
              required: false,
              type: "YYYY/MM/DD HH:MM:SS",
              layer: 1,
              byte: 1,
              description: "API送信日時",
            },
            {
              physicalName: "response_date",
              logicalName: "APIレスポンス日時",
              required: false,
              type: "YYYY/MM/DD HH:MM:SS",
              layer: 1,
              byte: 1,
              description: "API受信日時",
            },
          ],
        },

        {
          name: "健康情報一覧API",
          endpoint: "/api/root/healthinfo",
          httpMethod: "GET",
          description: "健康管理アプリのユーザの健康情報一覧を取得するAPI",
          url: "/root/api/healthinfo",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "page",
              logicalName: "ページ数",
              required: true,
              type: "半角数字",
              byte: null,
              description: "取得対象ページ数",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "paging",
              logicalName: "ページング情報",
              required: false,
              type: null,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "total_record_num",
              logicalName: "合計レコード数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "合計レコード数",
            },
            {
              physicalName: "from_record_num",
              logicalName: "レコード数(from)",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード開始番号",
            },
            {
              physicalName: "to_record_num",
              logicalName: "レコード数(to)",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード終了番号",
            },
            {
              physicalName: "total_page",
              logicalName: "総ページ数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード終了番号",
            },
            {
              physicalName: "current_page_num",
              logicalName: "現在のページ数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "現在のページ数",
            },
            {
              physicalName: "record_per_page",
              logicalName: "1ページあたりのレコード数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "1ページあたりのレコード数",
            },
            {
              physicalName: "can_go_next",
              logicalName: "次リンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "次リンク押下できるかどうか",
            },
            {
              physicalName: "next_href",
              logicalName: "次リンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "次リンクのhref属性",
            },
            {
              physicalName: "can_go_previous",
              logicalName: "前リンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "前リンク押下できるかどうか",
            },
            {
              physicalName: "previous_href",
              logicalName: "前リンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "前リンクのhref属性",
            },
            {
              physicalName: "can_go_last",
              logicalName: "最後ページまでのリンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "最後ページまでのリンクを押下できるかどうか",
            },
            {
              physicalName: "last_href",
              logicalName: "最後ページリンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "最後ページリンクのhref属性",
            },
            {
              physicalName: "can_go_first",
              logicalName: "先頭ページまでのリンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "先頭ページまでのリンクを押下できるかどうか",
            },
            {
              physicalName: "first_href",
              logicalName: "先頭ページリンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "先頭ページリンクのhref属性",
            },
            {
              physicalName: "health_info_list",
              logicalName: "健康情報リスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0' かつ データが存在する場合、必須",
            },
            {
              physicalName: "seq_health_info_id",
              logicalName: "健康情報ID",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "健康情報を一意に識別するID",
            },
            {
              physicalName: "seq_user_id",
              logicalName: "ユーザID",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "ユーザを一意にするID",
            },
            {
              physicalName: "height",
              logicalName: "身長",
              required: false,
              type: "小数値",
              layer: 1,
              byte: null,
              description: "ユーザの登録している身長",
            },
            {
              physicalName: "weight",
              logicalName: "体重",
              required: false,
              type: "小数値",
              layer: 1,
              byte: null,
              description: "ユーザの登録している体重",
            },
            {
              physicalName: "bmi",
              logicalName: "BMI",
              required: false,
              type: "小数値",
              layer: 1,
              byte: null,
              description: "ユーザの登録しているBMI",
            },
            {
              physicalName: "standard_weight",
              logicalName: "標準体重",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "ユーザの登録している標準体重",
            },
            {
              physicalName: "health_info_status",
              logicalName: "健康情報ステータス",
              required: false,
              type: null,
              layer: 1,
              byte: 2,
              description: "ユーザの登録している体重より判定されたステータス",
            },
            {
              physicalName: "status",
              logicalName: "ステータス",
              required: false,
              type: null,
              layer: 2,
              byte: 3,
              description:
                "<ul><li>10:減少</li><li>20:変化なし</li><li>30:増加</li></ul>",
            },
            {
              physicalName: "message",
              logicalName: "メッセージ",
              required: false,
              type: null,
              layer: 2,
              byte: null,
              description: null,
            },
            {
              physicalName: "bmi_status",
              logicalName: "BMIステータス",
              required: false,
              type: "オブジェクト",
              layer: 1,
              byte: 2,
              description: "ユーザの登録している体重より判定されたステータス",
            },
            {
              physicalName: "status",
              logicalName: "ステータス",
              required: false,
              type: null,
              layer: 2,
              byte: 3,
              description:
                "<ul><li>10:低体重</li><li>11:普通体重</li><li>12:肥満(1)</li><li>13:肥満(2)</li><li>14:肥満(3)</li><li>15:肥満(4)</li></ul>",
            },
            {
              physicalName: "message",
              logicalName: "メッセージ",
              required: false,
              type: null,
              layer: 2,
              byte: null,
              description: null,
            },
            {
              physicalName: "health_info_reg_date",
              logicalName: "健康情報登録日時",
              required: false,
              type: "YYYY/MM/DD HH:MM:SS",
              layer: 1,
              byte: null,
              description: "ユーザの健康情報を登録した日時",
            },
          ],
        },

        {
          name: "健康情報編集API",
          endpoint: "/api/root/healthinfo/{seq_health_info_id}",
          httpMethod: "PUT",
          description: "健康管理アプリのユーザの健康情報を更新するAPI",
          url: "/root/api/healthinfo/edit",
          headers: [
            {
              key: "Content-Type",
              value: "application/json",
            },
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "seq_user_id",
              logicalName: "ユーザID",
              required: true,
              type: "半角数字",
              byte: null,
              description: null,
            },
            {
              physicalName: "height",
              logicalName: "身長",
              required: true,
              type: "小数値",
              byte: null,
              description: "更新したい身長",
            },
            {
              physicalName: "weight",
              logicalName: "体重",
              required: true,
              type: "小数値",
              byte: null,
              description: "更新したい体重",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
          ],
        },

        {
          name: "お知らせ情報一覧取得API",
          endpoint: "/api/root/news",
          httpMethod: "GET",
          description: "健康管理アプリのお知らせ情報一覧を取得するAPI",
          url: "/root/api/news",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "news_list",
              logicalName: "お知らせ情報リスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "index",
              logicalName: "順序",
              required: false,
              type: "半角数字",
              byte: null,
              layer: 1,
              description: "お知らせ情報の表示順",
            },
            {
              physicalName: "title",
              logicalName: "タイトル",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "お知らせ情報のタイトル",
            },
            {
              physicalName: "date",
              logicalName: "日付",
              required: false,
              type: "YYYY/MM/DD",
              byte: null,
              layer: 1,
              description: "お知らせ情報の日付",
            },
            {
              physicalName: "detail",
              logicalName: "詳細",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "お知らせ情報の詳細情報",
            },
            {
              physicalName: "tag",
              logicalName: "タグ情報",
              required: false,
              type: "オブジェクト",
              byte: null,
              layer: 1,
              description: "お知らせ情報のタグ情報",
            },
            {
              physicalName: "color",
              logicalName: "色",
              required: false,
              type: null,
              byte: null,
              layer: 2,
              description:
                "お知らせ情報のタグ色<ul><li>blue</li><li>yellow</li><li>red</li></ul>",
            },
            {
              physicalName: "name",
              logicalName: "タグ名",
              required: false,
              type: null,
              byte: null,
              layer: 2,
              description: "お知らせ情報のタグ名",
            },
          ],
        },

        {
          name: "お知らせ情報登録API",
          endpoint: "/api/root/news",
          httpMethod: "POST",
          description: "健康管理アプリのお知らせ情報を登録するAPI",
          url: "/root/api/news/entry",
          headers: [
            {
              key: "Content-Type",
              value: "application/json",
            },
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "title",
              logicalName: "タイトル",
              required: true,
              type: null,
              byte: null,
              layer: 1,
              description: "お知らせ情報のタイトル",
            },
            {
              physicalName: "date",
              logicalName: "日付",
              required: true,
              type: "YYYY/MM/DD",
              byte: null,
              layer: 1,
              description: "お知らせ情報の日付",
            },
            {
              physicalName: "detail",
              logicalName: "詳細",
              required: true,
              type: null,
              byte: null,
              layer: 1,
              description: "お知らせ情報の詳細情報",
            },
            {
              physicalName: "tag",
              logicalName: "タグ情報",
              required: true,
              type: "オブジェクト",
              byte: null,
              layer: 1,
              description: "お知らせ情報のタグ情報",
            },
            {
              physicalName: "color",
              logicalName: "色",
              required: true,
              type: null,
              byte: null,
              layer: 2,
              description:
                "お知らせ情報のタグ色<ul><li>blue</li><li>yellow</li><li>red</li></ul>",
            },
            {
              physicalName: "name",
              logicalName: "タグ名",
              required: true,
              type: null,
              byte: null,
              layer: 2,
              description: "お知らせ情報のタグ名",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "news_data",
              logicalName: "お知らせ情報",
              required: false,
              type: "オブジェクト",
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "index",
              logicalName: "順序",
              required: false,
              type: "半角数字",
              byte: null,
              layer: 1,
              description: "お知らせ情報の表示順",
            },
            {
              physicalName: "title",
              logicalName: "タイトル",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "お知らせ情報のタイトル",
            },
            {
              physicalName: "date",
              logicalName: "日付",
              required: false,
              type: "YYYY/MM/DD",
              byte: null,
              layer: 1,
              description: "お知らせ情報の日付",
            },
            {
              physicalName: "detail",
              logicalName: "詳細",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "お知らせ情報の詳細情報",
            },
            {
              physicalName: "tag",
              logicalName: "タグ情報",
              required: false,
              type: "オブジェクト",
              byte: null,
              layer: 1,
              description: "お知らせ情報のタグ情報",
            },
            {
              physicalName: "color",
              logicalName: "色",
              required: false,
              type: null,
              byte: null,
              layer: 2,
              description:
                "お知らせ情報のタグ色<ul><li>blue</li><li>yellow</li><li>red</li></ul>",
            },
            {
              physicalName: "name",
              logicalName: "タグ名",
              required: false,
              type: null,
              byte: null,
              layer: 2,
              description: "お知らせ情報のタグ名",
            },
          ],
        },

        {
          name: "お知らせ情報編集API",
          endpoint: "/api/root/news/{id}",
          httpMethod: "PUT",
          description: "健康管理アプリのお知らせ情報を変更するAPI",
          url: "/root/api/news/edit",
          headers: [
            {
              key: "Content-Type",
              value: "application/json",
            },
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "index",
              logicalName: "表示順",
              required: true,
              type: "半角数字",
              byte: null,
              layer: 1,
              description: "お知らせ情報の表示順",
            },
            {
              physicalName: "title",
              logicalName: "タイトル",
              required: true,
              type: null,
              byte: null,
              layer: 1,
              description: "お知らせ情報のタイトル",
            },
            {
              physicalName: "date",
              logicalName: "日付",
              required: true,
              type: "YYYY/MM/DD",
              byte: null,
              layer: 1,
              description: "お知らせ情報の日付",
            },
            {
              physicalName: "detail",
              logicalName: "詳細",
              required: true,
              type: null,
              byte: null,
              layer: 1,
              description: "お知らせ情報の詳細情報",
            },
            {
              physicalName: "tag",
              logicalName: "タグ情報",
              required: true,
              type: "オブジェクト",
              byte: null,
              layer: 1,
              description: "お知らせ情報のタグ情報",
            },
            {
              physicalName: "color",
              logicalName: "色",
              required: true,
              type: null,
              byte: null,
              layer: 2,
              description:
                "お知らせ情報のタグ色<ul><li>blue</li><li>yellow</li><li>red</li></ul>",
            },
            {
              physicalName: "name",
              logicalName: "タグ名",
              required: true,
              type: null,
              byte: null,
              layer: 2,
              description: "お知らせ情報のタグ名",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "news_data",
              logicalName: "お知らせ情報",
              required: false,
              type: "オブジェクト",
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "index",
              logicalName: "順序",
              required: false,
              type: "半角数字",
              byte: null,
              layer: 1,
              description: "お知らせ情報の表示順",
            },
            {
              physicalName: "title",
              logicalName: "タイトル",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "お知らせ情報のタイトル",
            },
            {
              physicalName: "date",
              logicalName: "日付",
              required: false,
              type: "YYYY/MM/DD",
              byte: null,
              layer: 1,
              description: "お知らせ情報の日付",
            },
            {
              physicalName: "detail",
              logicalName: "詳細",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "お知らせ情報の詳細情報",
            },
            {
              physicalName: "tag",
              logicalName: "タグ情報",
              required: false,
              type: "オブジェクト",
              byte: null,
              layer: 1,
              description: "お知らせ情報のタグ情報",
            },
            {
              physicalName: "color",
              logicalName: "色",
              required: false,
              type: null,
              byte: null,
              layer: 2,
              description:
                "お知らせ情報のタグ色<ul><li>blue</li><li>yellow</li><li>red</li></ul>",
            },
            {
              physicalName: "name",
              logicalName: "タグ名",
              required: false,
              type: null,
              byte: null,
              layer: 2,
              description: "お知らせ情報のタグ名",
            },
          ],
        },

        {
          name: "お知らせ情報削除API",
          endpoint: "/api/root/news/{id}",
          httpMethod: "DELETE",
          description: "健康管理アプリのお知らせ情報を削除するAPI",
          url: "/root/api/news/delete",
          headers: [
            {
              key: "Content-Type",
              value: "application/json",
            },
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "delete_news_id",
              logicalName: "削除したお知らせ情報ID",
              required: false,
              type: "半角数字",
              byte: null,
              description: "result='0'の場合、必須",
            },
          ],
        },

        {
          name: "メモ情報一覧取得API",
          endpoint: "/api/root/note",
          httpMethod: "GET",
          description: "管理者用サイトユーザのメモ情報一覧を返却するAPI",
          url: "/root/api/note",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "seq_login_id",
              logicalName: "管理者サイトログイン情報ID",
              required: true,
              type: "半角数字",
              byte: null,
              layer: 1,
              description: "ログインID",
            },
            {
              physicalName: "page",
              logicalName: "ページ数",
              required: true,
              type: "半角数字",
              byte: null,
              description: "取得対象ページ数",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "paging",
              logicalName: "ページング情報",
              required: false,
              type: null,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "total_record_num",
              logicalName: "合計レコード数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "合計レコード数",
            },
            {
              physicalName: "from_record_num",
              logicalName: "レコード数(from)",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード開始番号",
            },
            {
              physicalName: "to_record_num",
              logicalName: "レコード数(to)",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード終了番号",
            },
            {
              physicalName: "total_page",
              logicalName: "総ページ数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード終了番号",
            },
            {
              physicalName: "current_page_num",
              logicalName: "現在のページ数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "現在のページ数",
            },
            {
              physicalName: "record_per_page",
              logicalName: "1ページあたりのレコード数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "1ページあたりのレコード数",
            },
            {
              physicalName: "can_go_next",
              logicalName: "次リンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "次リンク押下できるかどうか",
            },
            {
              physicalName: "next_href",
              logicalName: "次リンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "次リンクのhref属性",
            },
            {
              physicalName: "can_go_previous",
              logicalName: "前リンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "前リンク押下できるかどうか",
            },
            {
              physicalName: "previous_href",
              logicalName: "前リンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "前リンクのhref属性",
            },
            {
              physicalName: "can_go_last",
              logicalName: "最後ページまでのリンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "最後ページまでのリンクを押下できるかどうか",
            },
            {
              physicalName: "last_href",
              logicalName: "最後ページリンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "最後ページリンクのhref属性",
            },
            {
              physicalName: "can_go_first",
              logicalName: "先頭ページまでのリンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "先頭ページまでのリンクを押下できるかどうか",
            },
            {
              physicalName: "first_href",
              logicalName: "先頭ページリンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "先頭ページリンクのhref属性",
            },
            {
              physicalName: "note_list",
              logicalName: "メモ情報リスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "seq_root_user_note_info_id",
              logicalName: "管理者サイトユーザメモ情報ID",
              required: false,
              type: "半角数字",
              byte: null,
              layer: 1,
              description: "メモ情報を一意に識別するID",
            },
            {
              physicalName: "title",
              logicalName: "件名",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "メモ情報のタイトル",
            },
            {
              physicalName: "detail",
              logicalName: "詳細",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "メモ情報の内容",
            },
            {
              physicalName: "reg_date",
              logicalName: "登録日時",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "メモ情報を登録した日時",
            },
            {
              physicalName: "update_date",
              logicalName: "更新日時",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "メモ情報を更新した日時",
            },
          ],
        },

        {
          name: "メモ情報登録API",
          endpoint: "/api/root/note",
          httpMethod: "POST",
          description: "管理者用サイトユーザのメモ情報を登録するAPI",
          url: "/root/api/note/entry",
          headers: [
            {
              key: "Content-Type",
              value: "application/json",
            },
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "seq_login_id",
              logicalName: "管理者サイトログイン情報ID",
              required: true,
              type: "半角数字",
              byte: null,
              layer: 1,
              description: "ログインID",
            },
            {
              physicalName: "title",
              logicalName: "件名",
              required: true,
              type: null,
              byte: null,
              layer: 1,
              description: "メモ情報の件名",
            },
            {
              physicalName: "detail",
              logicalName: "詳細",
              required: true,
              type: null,
              byte: null,
              layer: 1,
              description: "メモ情報の詳細",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
          ],
        },

        {
          name: "メモ情報編集API",
          endpoint: "/api/root/note/{seq_root_user_note_info_id}",
          httpMethod: "PUT",
          description: "管理者用サイトユーザのメモ情報を編集するAPI",
          url: "/root/api/note/edit",
          headers: [
            {
              key: "Content-Type",
              value: "application/json",
            },
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "title",
              logicalName: "件名",
              required: true,
              type: null,
              byte: null,
              layer: 1,
              description: "メモ情報の件名",
            },
            {
              physicalName: "detail",
              logicalName: "詳細",
              required: true,
              type: null,
              byte: null,
              layer: 1,
              description: "メモ情報の詳細",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
          ],
        },

        {
          name: "メモ情報削除API",
          endpoint: "/api/root/note/{seq_root_user_note_info_id}",
          httpMethod: "DELETE",
          description: "管理者用サイトユーザのメモ情報を削除するAPI",
          url: "/root/api/note/delete",
          headers: [
            {
              key: "Content-Type",
              value: "application/json",
            },
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
          ],
        },

        {
          name: "権限マスタ一覧取得API",
          endpoint: "/api/root/roles",
          httpMethod: "GET",
          description: "管理者サイト権限マスタの一覧を返却するAPI",
          url: "/root/api/roles",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "roles",
              logicalName: "メモ情報リスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "label",
              logicalName: "権限名",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description:
                "権限マスタの権限名<ul><li>00:管理者権限</li><li>01:照会権限</li><li>02:作成権限</li></ul>",
            },
            {
              physicalName: "value",
              logicalName: "値",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "権限マスタの値",
            },
          ],
        },

        {
          name: "問い合わせ情報一覧取得API",
          endpoint: "/api/root/inquiry",
          httpMethod: "GET",
          description: "問い合わせ情報の一覧を返却するAPI",
          url: "/root/api/inquiry",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "paging",
              logicalName: "ページング情報",
              required: false,
              type: null,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "total_record_num",
              logicalName: "合計レコード数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "合計レコード数",
            },
            {
              physicalName: "from_record_num",
              logicalName: "レコード数(from)",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード開始番号",
            },
            {
              physicalName: "to_record_num",
              logicalName: "レコード数(to)",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード終了番号",
            },
            {
              physicalName: "total_page",
              logicalName: "総ページ数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "レコード終了番号",
            },
            {
              physicalName: "current_page_num",
              logicalName: "現在のページ数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "現在のページ数",
            },
            {
              physicalName: "record_per_page",
              logicalName: "1ページあたりのレコード数",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "1ページあたりのレコード数",
            },
            {
              physicalName: "can_go_next",
              logicalName: "次リンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "次リンク押下できるかどうか",
            },
            {
              physicalName: "next_href",
              logicalName: "次リンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "次リンクのhref属性",
            },
            {
              physicalName: "can_go_previous",
              logicalName: "前リンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "前リンク押下できるかどうか",
            },
            {
              physicalName: "previous_href",
              logicalName: "前リンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "前リンクのhref属性",
            },
            {
              physicalName: "can_go_last",
              logicalName: "最後ページまでのリンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "最後ページまでのリンクを押下できるかどうか",
            },
            {
              physicalName: "last_href",
              logicalName: "最後ページリンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "最後ページリンクのhref属性",
            },
            {
              physicalName: "can_go_first",
              logicalName: "先頭ページまでのリンク押下可能フラグ",
              required: false,
              type: "真偽値",
              layer: 1,
              byte: null,
              description: "先頭ページまでのリンクを押下できるかどうか",
            },
            {
              physicalName: "first_href",
              logicalName: "先頭ページリンク属性",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "先頭ページリンクのhref属性",
            },
            {
              physicalName: "inquiry_list",
              logicalName: "問い合わせリスト",
              required: false,
              type: "配列",
              byte: null,
              description: "問い合わせリスト",
            },
            {
              physicalName: "seq_inquiry_mng_id",
              logicalName: "問い合わせ管理ID",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "問い合わせ管理ID",
            },
            {
              physicalName: "seq_user_id",
              logicalName: "ユーザID",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "ユーザID",
            },
            {
              physicalName: "responder_login_id",
              logicalName: "対応者ログインID",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "対応者ログインID",
            },
            {
              physicalName: "status",
              logicalName: "問い合わせステータス",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "問い合わせステータス",
            },
            {
              physicalName: "label",
              logicalName: "問い合わせステータス名",
              required: false,
              type: null,
              layer: 2,
              byte: null,
              description: "問い合わせステータス名",
            },
            {
              physicalName: "value",
              logicalName: "問い合わせステータス値",
              required: false,
              type: null,
              layer: 2,
              byte: null,
              description: "問い合わせステータス値",
            },
            {
              physicalName: "type",
              logicalName: "問い合わせ種別",
              required: false,
              type: null,
              layer: 1,
              byte: null,
              description: "問い合わせ種別",
            },
            {
              physicalName: "label",
              logicalName: "問い合わせ種別名",
              required: false,
              type: null,
              layer: 2,
              byte: null,
              description: "問い合わせ種別名",
            },
            {
              physicalName: "value",
              logicalName: "問い合わせ種別値",
              required: false,
              type: null,
              layer: 2,
              byte: null,
              description: "問い合わせ種別値",
            },
            {
              physicalName: "title",
              logicalName: "件名",
              required: false,
              type: "全角文字",
              layer: 1,
              byte: null,
              description: "件名",
            },
            {
              physicalName: "body",
              logicalName: "本文",
              required: false,
              type: "全角文字",
              layer: 1,
              byte: null,
              description: "本文",
            },
            {
              physicalName: "reg_date",
              logicalName: "登録日時",
              required: false,
              type: "YYYY/MM/DD HH:MM:SS",
              layer: 1,
              byte: null,
              description: "問い合わせ情報を登録した日時",
            },
            {
              physicalName: "update_date",
              logicalName: "更新日時",
              required: false,
              type: "YYYY/MM/DD HH:MM:SS",
              layer: 1,
              byte: null,
              description: "問い合わせ情報を更新した日時",
            },
          ],
        },
        {
          name: "問い合わせ情報編集API",
          endpoint: "/api/root/inquiry/{seq_inquiry_mng_id}",
          httpMethod: "PUT",
          description: "問い合わせ情報を更新するAPI",
          url: "/root/api/inquiry/{seq_inquiry_mng_id}",
          headers: [
            {
              key: "Content-Type",
              value: "application/json",
            },
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
          ],
        },
        {
          name: "問い合わせステータスマスタ一覧取得API",
          endpoint: "/api/root/inquiry/status",
          httpMethod: "GET",
          description: "問い合わせステータスマスタの一覧を返却するAPI",
          url: "/root/api/inquiry/status",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "statuses",
              logicalName: "ステータスリスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "label",
              logicalName: "ステータス名",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description:
                "ステータス名<ul><li>00:未対応</li><li>01:対応中</li><li>02:完了</li></ul>",
            },
            {
              physicalName: "value",
              logicalName: "値",
              required: false,
              type: null,
              byte: null,
              layer: 1,
              description: "ステータスの値",
            },
          ],
        },
        {
          name: "問い合わせ情報通知API",
          endpoint: "/api/root/inquiry/notice",
          httpMethod: "GET",
          description: "指定されたステータスの問い合わせ情報の件数を通知するAPI",
          url: "/root/api/inquiry/notice",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [
            {
              physicalName: "status",
              logicalName: "ステータス",
              required: true,
              type: "半角英数字",
              byte: 1,
              description:
                "処理結果<ul><li>00：未対応</li><li>01：対応中</li><li>02：完了</li></ul>",
            },
          ],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "count",
              logicalName: "問い合わせ件数",
              required: false,
              type: "半角数字",
              byte: null,
              description: "result='0'の場合、必須",
            },
          ],
        },
        {
          name: "Job履歴情報一覧取得API",
          endpoint: "/api/root/job",
          httpMethod: "GET",
          description: "健康管理バッチで実行されたJob履歴情報の一覧を返却するAPI",
          url: "/root/api/job",
          headers: [
            {
              key: "Authorization",
              value: "Bearer ログインAPI.レスポンス.tokenを設定",
            },
          ],
          request: [],
          response: [
            {
              physicalName: "result",
              logicalName: "処理結果",
              required: true,
              type: "半角数字",
              byte: 1,
              description:
                "処理結果<ul><li>0:正常終了</li><li>1:異常終了</li></ul>",
            },
            {
              physicalName: "errors",
              logicalName: "エラー情報",
              required: false,
              type: null,
              byte: null,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "message",
              logicalName: "エラーメッセージ",
              required: false,
              type: null,
              layer: 1,
              byte: 256,
              description: "result='1'の場合、必須",
            },
            {
              physicalName: "job_list",
              logicalName: "Job履歴情報リスト",
              required: false,
              type: "配列",
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "job_instance_id",
              logicalName: "jobInstanceId",
              required: false,
              type: "半角数字",
              layer: 1,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "start_time",
              logicalName: "開始日時",
              required: false,
              type: "yyyy/MM/dd HH:mm:ss",
              layer: 1,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "end_time",
              logicalName: "終了日時",
              required: false,
              type: "yyyy/MM/dd HH:mm:ss",
              layer: 1,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "status",
              logicalName: "ステータス",
              required: false,
              type: "半角英字",
              layer: 1,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "job_name",
              logicalName: "Job名",
              required: false,
              type: "全角文字",
              layer: 1,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "parameter_list",
              logicalName: "Jobパラメータリスト",
              required: false,
              type: "配列",
              layer: 1,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "name",
              logicalName: "パラメータ名",
              required: false,
              type: "半角英字",
              layer: 2,
              byte: null,
              description: "result='0'の場合、必須",
            },
            {
              physicalName: "value",
              logicalName: "パラメータ値",
              required: false,
              type: "半角英数字",
              layer: 2,
              byte: null,
              description: "result='0'の場合、必須",
            },
          ],
        },
      ],
    };
  },
};
</script>

<style scoped></style>
