-- アカウント情報
DROP TABLE IF EXISTS ACCOUNT;
-- 健康情報
DROP TABLE IF EXISTS HEALTH_INFO;
-- 健康情報ファイル設定
DROP TABLE IF EXISTS HEALTH_INFO_FILE_SETTING;
-- BMI範囲マスタ
DROP TABLE IF EXISTS BMI_RANGE_MT;
-- アカウント回復トークン情報
DROP TABLE IF EXISTS ACCOUNT_RECOVERY_TOKEN_DATA;
-- API通信情報
DROP TABLE IF EXISTS API_COMMUNICATION_DATA;
-- 管理者サイトユーザログイン情報
DROP TABLE IF EXISTS ROOT_LOGIN_INFO;
-- 管理者サイトユーザ権限管理マスタ
DROP TABLE IF EXISTS ROOT_USER_ROLE_MNG_MT;
-- 管理者サイトユーザ権限詳細マスタ
DROP TABLE IF EXISTS ROOT_USER_ROLE_DETAIL_MT;
-- 管理者サイト権限マスタ
DROP TABLE IF EXISTS ROOT_ROLE_MT;
-- 管理者サイトユーザメモ情報
DROP TABLE IF EXISTS ROOT_USER_NOTE_INFO;
-- お知らせ情報
DROP TABLE IF EXISTS NEWS_INFO;
-- ユーザ情報
DROP TABLE IF EXISTS USER;
-- ユーザ回復トークン情報
DROP TABLE IF EXISTS USER_RECOVERY_TOKEN;