-- ユーザ情報
DROP TABLE IF EXISTS USER;
-- 健康情報
DROP TABLE IF EXISTS HEALTH_INFO;
-- 健康情報ファイル設定
DROP TABLE IF EXISTS HEALTH_INFO_FILE_SETTING;
-- BMI範囲マスタ
DROP TABLE IF EXISTS BMI_RANGE_MT;
-- ユーザ回復トークン情報
DROP TABLE IF EXISTS USER_RECOVERY_TOKEN;
-- API通信ログ
DROP TABLE IF EXISTS API_LOG;
-- 管理者サイトユーザログイン情報
DROP TABLE IF EXISTS ROOT_LOGIN_INFO;
-- 管理者サイトユーザ権限管理マスタ
DROP TABLE IF EXISTS ROOT_USER_ROLE_MNG_MT;
-- 管理者サイトユーザ権限詳細マスタ
DROP TABLE IF EXISTS ROOT_USER_ROLE_DETAIL_MT;
-- 管理者サイト権限マスタ
DROP TABLE IF EXISTS ROOT_ROLE_MT;
-- 管理者サイトユーザメモ情報
DROP TABLE IF EXISTS ROOT_USER_NOTE_INFO;
-- お知らせ情報
DROP TABLE IF EXISTS NEWS_INFO;
-- ユーザ健康目標情報
DROP TABLE IF EXISTS USER_HEALTH_GOAL;
-- 問い合わせ管理情報
DROP TABLE IF EXISTS INQUIRY_MANAGEMENT;
-- 問い合わせ種別マスタ
DROP TABLE IF EXISTS INQUIRY_TYPE_MT;
-- 問い合わせステータスマスタ
DROP TABLE IF EXISTS INQUIRY_STATUS_MT;
