-- ユーザ情報
SHOW COLUMNS FROM USER;
-- 健康情報
SHOW COLUMNS FROM HEALTH_INFO;
-- 健康情報ファイル設定
SHOW COLUMNS FROM HEALTH_INFO_FILE_SETTING;
-- BMI範囲マスタ
SHOW COLUMNS FROM BMI_RANGE_MT;
-- ユーザ回復トークン情報
SHOW COLUMNS FROM USER_RECOVERY_TOKEN;
-- API通信ログ
SHOW COLUMNS FROM API_LOG;
-- 管理者サイトユーザログイン情報
SHOW COLUMNS FROM ROOT_LOGIN_INFO;
-- 管理者サイトユーザ権限管理マスタ
SHOW COLUMNS FROM ROOT_USER_ROLE_MNG_MT;
-- 管理者サイトユーザ権限詳細マスタ
SHOW COLUMNS FROM ROOT_USER_ROLE_DETAIL_MT;
-- 管理者サイト権限マスタ
SHOW COLUMNS FROM ROOT_ROLE_MT;
-- 管理者サイトユーザメモ情報
SHOW COLUMNS FROM ROOT_USER_NOTE_INFO;
-- お知らせ情報
SHOW COLUMNS FROM NEWS_INFO;
-- ユーザ健康目標情報
SHOW COLUMNS FROM USER_HEALTH_GOAL;
-- 問い合わせ管理情報
SHOW COLUMNS FROM INQUIRY_MANAGEMENT;
-- 問い合わせ種別マスタ
SHOW COLUMNS FROM INQUIRY_TYPE_MT;
-- 問い合わせステータスマスタ
SHOW COLUMNS FROM INQUIRY_STATUS_MT;
