-- アカウント情報
SHOW COLUMNS FROM ACCOUNT;
-- 健康情報
SHOW COLUMNS FROM HEALTH_INFO;
-- 健康情報ファイル設定
SHOW COLUMNS FROM HEALTH_INFO_FILE_SETTING;
-- BMI範囲マスタ
SHOW COLUMNS FROM BMI_RANGE_MT;
-- アカウント回復トークン情報
SHOW COLUMNS FROM ACCOUNT_RECOVERY_TOKEN_DATA;
-- API通信情報
SHOW COLUMNS FROM API_COMMUNICATION_DATA;
-- 管理者サイトユーザログイン情報
SHOW COLUMNS FROM ROOT_LOGIN_INFO;
-- 管理者サイトユーザ権限管理マスタ
SHOW COLUMNS FROM ROOT_USER_ROLE_MNG_MT;
-- 管理者サイトユーザ権限詳細マスタ
SHOW COLUMNS FROM ROOT_USER_ROLE_DETAIL_MT;
-- 管理者サイト権限マスタ
SHOW COLUMNS FROM ROOT_ROLE_MT;