front:
  # TODO URLを変更すること
  url: http://localhost:8083
  page: 20
spring:
  # 設定ファイル読込
    config:
      import:
        - "classpath:/dev1/crypt.properties"
        - "classpath:/dev1/jdbc.properties"
        - "classpath:/dev1/system.properties"
        - "classpath:/dev1/aws.properties"
        - "classpath:/dev1/healthInfo.properties"
