front:
  url: http://localhost:8083
  news:
    page: 10
  note:
    page: 10
  account:
    page: 30
  api:
    page: 30
  healthinfo:
    page: 30
spring:
  # 設定ファイル読込
    config:
      import:
        - "classpath:/dev1/crypt.properties"
        - "classpath:/dev1/jdbc.properties"
        - "classpath:/dev1/system.properties"
        - "classpath:/dev1/aws.properties"
        - "classpath:/dev1/healthInfo.properties"
