spring:
  application:
    name: ha-root
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: messages
    cache-duration: -1
    encoding: UTF-8
  output:
    ansi:
      enabled: always
  web: 
    resources:
      add-mappings: false
  thymeleaf:
    check-template-location: false