# Generated by Django 3.0.3 on 2024-11-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq_user_id', models.DecimalField(decimal_places=0, max_digits=15)),
                ('health_data_created_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('standard_weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
