# Generated by Django 3.0.3 on 2024-11-30 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20241130_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthinfo',
            old_name='health_info_created_at',
            new_name='created_at',
        ),
    ]
