module "healthinfo" {
  source = "../../modules"

  project_name                         = var.project_name
  app_env                              = var.app_env
  vpc_cidr                             = var.vpc_cidr
  az_count                             = var.az_count
  public_subnet_cidrs                  = var.public_subnet_cidrs
  private_db_subnet_cidrs              = var.private_db_subnet_cidrs
  db_name                              = var.db_name
  db_engine_version                    = var.db_engine_version
  db_master_username                   = var.db_master_username
  db_master_password_parameter_version = var.db_master_password_parameter_version
  db_app_username                      = var.db_app_username
  api_log_queue_name                   = var.api_log_queue_name
  app_ssm_parameter_prefix             = var.app_ssm_parameter_prefix
  bastion_ssh_allowed_cidr             = var.bastion_ssh_allowed_cidr
  bastion_instance_type                = var.bastion_instance_type
  bastion_key_name                     = var.bastion_key_name
  dashboard_desired_count              = var.dashboard_desired_count
  api_desired_count                    = var.api_desired_count
  api_public_allowed_cidr              = var.api_public_allowed_cidr
  track_desired_count                  = var.track_desired_count
  track_public_allowed_cidr            = var.track_public_allowed_cidr
  track_django_allowed_hosts           = var.track_django_allowed_hosts
  root_api_desired_count               = var.root_api_desired_count
  root_api_public_allowed_cidr         = var.root_api_public_allowed_cidr
  root_front_url                       = var.root_front_url
  app_data_bucket_name                 = var.app_data_bucket_name
  image_tag                            = var.image_tag
  health_info_dashboard_url            = var.health_info_dashboard_url
}
