# Dockerfile.ha-track
FROM python:3.13.8
WORKDIR /app

# create log dir
RUN mkdir -p /var/app/log

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY ha_track/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ha_track/ /app/

EXPOSE 8086

CMD ["gunicorn","--bind","0.0.0.0:8086","--access-logfile","-","--error-logfile","-","ha_track.wsgi:application"]
