# ---- build stage ----
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /work

# copy build source
COPY . .

# ha-api build
RUN cd ha-pom && mvn -Dmaven.test.skip=true -pl ../ha-api -am package

# ---- run stage ----
FROM eclipse-temurin:21-jre
WORKDIR /app

# copy jar
COPY --from=build /work/ha-api/target/*.jar /app/api-1.0.0.jar

EXPOSE 8081
ENTRYPOINT ["java","-jar","/app/api-1.0.0.jar"]
