"""
Django settings for ha_track project.

Generated by 'django-admin startproject' using Django 4.2.16.
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

APP_ENV = os.getenv("APP_ENV", "local").lower()

BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = Path(os.getenv("DJANGO_LOG_DIR", "/var/app/log"))
try:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
except OSError:
    LOG_DIR = BASE_DIR / "log"
    LOG_DIR.mkdir(parents=True, exist_ok=True)

LOCAL_SECRET_KEY = (
    "django-insecure-$xe5g@$zhg=fa8mv3waqymq07%d9i&uiry+434wchbx$f8*ju2"
)
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    LOCAL_SECRET_KEY if APP_ENV == "local" else "",
)
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is required when APP_ENV is not local."
    )

DEBUG = os.getenv(
    "DJANGO_DEBUG",
    "true" if APP_ENV == "local" else "false",
).lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = (
    os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
    if os.getenv("DJANGO_ALLOWED_HOSTS")
    else []
)

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "api.apps.ApiConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ha_track.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "debug.log"),
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "api": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

WSGI_APPLICATION = "ha_track.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

def get_health_info_dynamodb_table_name():
    if APP_ENV == "local":
        return "health_info_local"

    if APP_ENV not in {"dev", "prd"}:
        raise ImproperlyConfigured("APP_ENV must be local, dev, or prd.")

    table_name = os.getenv("HEALTH_INFO_DYNAMODB_TABLE_NAME")
    if not table_name:
        raise ImproperlyConfigured(
            "HEALTH_INFO_DYNAMODB_TABLE_NAME is required when APP_ENV is not local."
        )

    expected_table_name = f"health_info_{APP_ENV}"
    if table_name != expected_table_name:
        raise ImproperlyConfigured(
            "HEALTH_INFO_DYNAMODB_TABLE_NAME must be "
            f"{expected_table_name} when APP_ENV is {APP_ENV}."
        )

    return table_name


HEALTH_INFO_DYNAMODB_TABLE_NAME = get_health_info_dynamodb_table_name()
