-- アカウント情報
CREATE TABLE IF NOT EXISTS ACCOUNT (
  -- ユーザID
  USER_ID VARCHAR(16) NOT NULL PRIMARY KEY COMMENT 'ユーザID',
  -- パスワード
  PASSWORD VARCHAR(64) NOT NULL COMMENT 'パスワード',
  -- 削除フラグ
  DELETE_FLAG VARCHAR(1) NOT NULL COMMENT '削除フラグ',
  -- パスワード有効期限
  PASSWORD_EXPIRE DATE NOT NULL COMMENT 'パスワード有効期限',
  -- 備考
  REMARKS VARCHAR(256) COMMENT '備考',
  -- APIキー
  API_KEY VARCHAR(64) COMMENT 'APIキー',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);