-- メール情報
CREATE TABLE IF NOT EXISTS MAIL_INFO (
  -- ユーザID
  USER_ID VARCHAR(16) NOT NULL PRIMARY KEY COMMENT 'ユーザID',
  -- メールアドレス
  MAIL_ADDRESS VARCHAR(512) NOT NULL COMMENT 'メールアドレス',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);