-- システム環境マスタ
CREATE TABLE SYSTEM_ENVIRONMENT_MT (
-- 環境ID
ENVIRONMENT_ID VARCHAR(16) NOT NULL PRIMARY KEY,
-- ページング件数
PAGING_COUNT INT,
-- 更新日時
UPDATE_DATE TIMESTAMP,
-- 登録日時
REG_DATE TIMESTAMP
);
