package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.AccountRecoveryToken;
import jp.co.ha.db.entity.AccountRecoveryTokenExample;
import jp.co.ha.db.entity.AccountRecoveryTokenKey;

/**
 * アカウント回復トークンのMapper
 *
 * @version 1.0.0
 */
public interface AccountRecoveryTokenMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    long countByExample(AccountRecoveryTokenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    int deleteByExample(AccountRecoveryTokenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    int deleteByPrimaryKey(AccountRecoveryTokenKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    int insert(AccountRecoveryToken record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    int insertSelective(AccountRecoveryToken record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    List<AccountRecoveryToken> selectByExampleWithRowbounds(
            AccountRecoveryTokenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    List<AccountRecoveryToken> selectByExample(AccountRecoveryTokenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    AccountRecoveryToken selectByPrimaryKey(AccountRecoveryTokenKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    int updateByExampleSelective(@Param("record") AccountRecoveryToken record,
            @Param("example") AccountRecoveryTokenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    int updateByExample(@Param("record") AccountRecoveryToken record,
            @Param("example") AccountRecoveryTokenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    int updateByPrimaryKeySelective(AccountRecoveryToken record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Sun Nov 29 14:01:10 GMT+09:00 2020
     */
    int updateByPrimaryKey(AccountRecoveryToken record);
}