package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.AccountRecoveryTokenData;
import jp.co.ha.db.entity.AccountRecoveryTokenDataExample;
import jp.co.ha.db.entity.AccountRecoveryTokenDataKey;

/**
 * アカウント回復トークン情報Mapper
 *
 * @version 1.0.0
 */
public interface AccountRecoveryTokenDataMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    long countByExample(AccountRecoveryTokenDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByExample(AccountRecoveryTokenDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByPrimaryKey(AccountRecoveryTokenDataKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insert(AccountRecoveryTokenData row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insertSelective(AccountRecoveryTokenData row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<AccountRecoveryTokenData> selectByExampleWithRowbounds(
            AccountRecoveryTokenDataExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<AccountRecoveryTokenData> selectByExample(
            AccountRecoveryTokenDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    AccountRecoveryTokenData selectByPrimaryKey(AccountRecoveryTokenDataKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExampleSelective(@Param("row") AccountRecoveryTokenData row,
            @Param("example") AccountRecoveryTokenDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExample(@Param("row") AccountRecoveryTokenData row,
            @Param("example") AccountRecoveryTokenDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKeySelective(AccountRecoveryTokenData row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token_data
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKey(AccountRecoveryTokenData row);
}