package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.ApiCommunicationData;
import jp.co.ha.db.entity.ApiCommunicationDataExample;
import jp.co.ha.db.entity.ApiCommunicationDataKey;

/**
 * API通信情報Mapper
 *
 * @version 1.0.0
 */
public interface ApiCommunicationDataMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    long countByExample(ApiCommunicationDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    int deleteByExample(ApiCommunicationDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    int deleteByPrimaryKey(ApiCommunicationDataKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    int insert(ApiCommunicationData row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    int insertSelective(ApiCommunicationData row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    List<ApiCommunicationData> selectByExampleWithRowbounds(
            ApiCommunicationDataExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    List<ApiCommunicationData> selectByExample(ApiCommunicationDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    ApiCommunicationData selectByPrimaryKey(ApiCommunicationDataKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    int updateByExampleSelective(@Param("row") ApiCommunicationData row,
            @Param("example") ApiCommunicationDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    int updateByExample(@Param("row") ApiCommunicationData row,
            @Param("example") ApiCommunicationDataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    int updateByPrimaryKeySelective(ApiCommunicationData row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
     * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
     */
    int updateByPrimaryKey(ApiCommunicationData row);
}