package jp.co.ha.db.mapper;

import java.util.List;
import jp.co.ha.db.entity.ApiLog;
import jp.co.ha.db.entity.ApiLogExample;
import jp.co.ha.db.entity.ApiLogKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ApiLogMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    long countByExample(ApiLogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByExample(ApiLogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByPrimaryKey(ApiLogKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insert(ApiLog row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insertSelective(ApiLog row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<ApiLog> selectByExampleWithRowbounds(ApiLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<ApiLog> selectByExample(ApiLogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    ApiLog selectByPrimaryKey(ApiLogKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") ApiLog row,
            @Param("example") ApiLogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExample(@Param("row") ApiLog row,
            @Param("example") ApiLogExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(ApiLog row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table API_LOG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKey(ApiLog row);
}