package jp.co.ha.db.mapper;

import java.util.List;
import jp.co.ha.db.entity.ApiLog;
import jp.co.ha.db.entity.ApiLogExample;
import jp.co.ha.db.entity.ApiLogKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ApiLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    long countByExample(ApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    int deleteByExample(ApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    int deleteByPrimaryKey(ApiLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    int insert(ApiLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    int insertSelective(ApiLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    List<ApiLog> selectByExampleWithRowbounds(ApiLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    List<ApiLog> selectByExample(ApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    ApiLog selectByPrimaryKey(ApiLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    int updateByExampleSelective(@Param("row") ApiLog row, @Param("example") ApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    int updateByExample(@Param("row") ApiLog row, @Param("example") ApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    int updateByPrimaryKeySelective(ApiLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table API_LOG
     *
     * @mbg.generated Mon Dec 29 15:36:50 GMT+09:00 2025
     */
    int updateByPrimaryKey(ApiLog row);
}