package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.BmiRangeMt;
import jp.co.ha.db.entity.BmiRangeMtExample;
import jp.co.ha.db.entity.BmiRangeMtKey;

/**
 * BMI範囲マスタMapper
 *
 * @version 1.0.0
 */
public interface BmiRangeMtMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    long countByExample(BmiRangeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByExample(BmiRangeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByPrimaryKey(BmiRangeMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insert(BmiRangeMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insertSelective(BmiRangeMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<BmiRangeMt> selectByExampleWithRowbounds(BmiRangeMtExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<BmiRangeMt> selectByExample(BmiRangeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    BmiRangeMt selectByPrimaryKey(BmiRangeMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") BmiRangeMt row,
            @Param("example") BmiRangeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExample(@Param("row") BmiRangeMt row,
            @Param("example") BmiRangeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(BmiRangeMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table BMI_RANGE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKey(BmiRangeMt row);
}