package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.BmiRangeMt;
import jp.co.ha.db.entity.BmiRangeMtExample;
import jp.co.ha.db.entity.BmiRangeMtKey;

/**
 * BMI範囲マスタMapper
 *
 * @version 1.0.0
 */
public interface BmiRangeMtMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    long countByExample(BmiRangeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int deleteByExample(BmiRangeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int deleteByPrimaryKey(BmiRangeMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int insert(BmiRangeMt record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int insertSelective(BmiRangeMt record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    List<BmiRangeMt> selectByExampleWithRowbounds(BmiRangeMtExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    List<BmiRangeMt> selectByExample(BmiRangeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    BmiRangeMt selectByPrimaryKey(BmiRangeMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int updateByExampleSelective(@Param("record") BmiRangeMt record,
            @Param("example") BmiRangeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int updateByExample(@Param("record") BmiRangeMt record,
            @Param("example") BmiRangeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int updateByPrimaryKeySelective(BmiRangeMt record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table bmi_range_mt
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int updateByPrimaryKey(BmiRangeMt record);
}