package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.HealthInfoFileSetting;
import jp.co.ha.db.entity.HealthInfoFileSettingExample;
import jp.co.ha.db.entity.HealthInfoFileSettingKey;

/**
 * 健康情報ファイル設定情報Mapper
 *
 * @version 1.0.0
 */
public interface HealthInfoFileSettingMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    long countByExample(HealthInfoFileSettingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int deleteByExample(HealthInfoFileSettingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int deleteByPrimaryKey(HealthInfoFileSettingKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int insert(HealthInfoFileSetting record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int insertSelective(HealthInfoFileSetting record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    List<HealthInfoFileSetting> selectByExampleWithRowbounds(
            HealthInfoFileSettingExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    List<HealthInfoFileSetting> selectByExample(HealthInfoFileSettingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    HealthInfoFileSetting selectByPrimaryKey(HealthInfoFileSettingKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int updateByExampleSelective(@Param("record") HealthInfoFileSetting record,
            @Param("example") HealthInfoFileSettingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int updateByExample(@Param("record") HealthInfoFileSetting record,
            @Param("example") HealthInfoFileSettingExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int updateByPrimaryKeySelective(HealthInfoFileSetting record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info_file_setting
     *
     * @mbg.generated Sat Apr 10 13:45:33 GMT+09:00 2021
     */
    int updateByPrimaryKey(HealthInfoFileSetting record);
}