package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import jp.co.ha.db.entity.HealthInfo;
import jp.co.ha.db.entity.HealthInfoExample;

/**
 * 健康情報Mapper
 * 
 * @since 1.0
 */
public interface HealthInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table health_info
	 *
	 * @mbg.generated Thu Feb 14 20:37:33 JST 2019
	 */
	long countByExample(HealthInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table health_info
	 *
	 * @mbg.generated Thu Feb 14 20:37:33 JST 2019
	 */
	int deleteByExample(HealthInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table health_info
	 *
	 * @mbg.generated Thu Feb 14 20:37:33 JST 2019
	 */
	int deleteByPrimaryKey(Integer healthInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table health_info
	 *
	 * @mbg.generated Thu Feb 14 20:37:33 JST 2019
	 */
	int insert(HealthInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table health_info
	 *
	 * @mbg.generated Thu Feb 14 20:37:33 JST 2019
	 */
	int insertSelective(HealthInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table health_info
	 *
	 * @mbg.generated Thu Feb 14 20:37:33 JST 2019
	 */
	List<HealthInfo> selectByExample(HealthInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table health_info
	 *
	 * @mbg.generated Thu Feb 14 20:37:33 JST 2019
	 */
	HealthInfo selectByPrimaryKey(Integer healthInfoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table health_info
	 *
	 * @mbg.generated Thu Feb 14 20:37:33 JST 2019
	 */
	int updateByExampleSelective(@Param("record") HealthInfo record, @Param("example") HealthInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table health_info
	 *
	 * @mbg.generated Thu Feb 14 20:37:33 JST 2019
	 */
	int updateByExample(@Param("record") HealthInfo record, @Param("example") HealthInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table health_info
	 *
	 * @mbg.generated Thu Feb 14 20:37:33 JST 2019
	 */
	int updateByPrimaryKeySelective(HealthInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table health_info
	 *
	 * @mbg.generated Thu Feb 14 20:37:33 JST 2019
	 */
	int updateByPrimaryKey(HealthInfo record);

	/**
	 * 指定したユーザIDで最後に登録した健康情報を検索
	 *
	 * @param userId
	 *     ユーザID
	 * @return 健康情報
	 */
	HealthInfo selectByUserIdLast(String userId);

}