package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.HealthInfo;
import jp.co.ha.db.entity.HealthInfoExample;
import jp.co.ha.db.entity.HealthInfoKey;

/**
 * 健康情報Mapper
 *
 * @version 1.0.0
 */
public interface HealthInfoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    long countByExample(HealthInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByExample(HealthInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByPrimaryKey(HealthInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insert(HealthInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insertSelective(HealthInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<HealthInfo> selectByExampleWithRowbounds(HealthInfoExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<HealthInfo> selectByExample(HealthInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    HealthInfo selectByPrimaryKey(HealthInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExampleSelective(@Param("row") HealthInfo row,
            @Param("example") HealthInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExample(@Param("row") HealthInfo row,
            @Param("example") HealthInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKeySelective(HealthInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table health_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKey(HealthInfo row);

}