package jp.co.ha.db.mapper;

import java.util.List;
import jp.co.ha.db.entity.InquiryManagement;
import jp.co.ha.db.entity.InquiryManagementExample;
import jp.co.ha.db.entity.InquiryManagementKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InquiryManagementMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    long countByExample(InquiryManagementExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    int deleteByExample(InquiryManagementExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    int deleteByPrimaryKey(InquiryManagementKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    int insert(InquiryManagement row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    int insertSelective(InquiryManagement row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    List<InquiryManagement> selectByExampleWithRowbounds(InquiryManagementExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    List<InquiryManagement> selectByExample(InquiryManagementExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    InquiryManagement selectByPrimaryKey(InquiryManagementKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    int updateByExampleSelective(@Param("row") InquiryManagement row,
            @Param("example") InquiryManagementExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    int updateByExample(@Param("row") InquiryManagement row,
            @Param("example") InquiryManagementExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    int updateByPrimaryKeySelective(InquiryManagement row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    int updateByPrimaryKey(InquiryManagement row);
}