package jp.co.ha.db.mapper;

import java.util.List;
import jp.co.ha.db.entity.InquiryTypeMt;
import jp.co.ha.db.entity.InquiryTypeMtExample;
import jp.co.ha.db.entity.InquiryTypeMtKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InquiryTypeMtMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    long countByExample(InquiryTypeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByExample(InquiryTypeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByPrimaryKey(InquiryTypeMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insert(InquiryTypeMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insertSelective(InquiryTypeMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<InquiryTypeMt> selectByExampleWithRowbounds(InquiryTypeMtExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<InquiryTypeMt> selectByExample(InquiryTypeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    InquiryTypeMt selectByPrimaryKey(InquiryTypeMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") InquiryTypeMt row,
            @Param("example") InquiryTypeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExample(@Param("row") InquiryTypeMt row,
            @Param("example") InquiryTypeMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(InquiryTypeMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table INQUIRY_TYPE_MT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKey(InquiryTypeMt row);
}