package jp.co.ha.db.mapper;

import java.util.List;
import jp.co.ha.db.entity.InquiryStatusMt;
import jp.co.ha.db.entity.InquiryStatusMtExample;
import jp.co.ha.db.entity.InquiryStatusMtKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InquiryStatusMtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    long countByExample(InquiryStatusMtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    int deleteByExample(InquiryStatusMtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    int deleteByPrimaryKey(InquiryStatusMtKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    int insert(InquiryStatusMt row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    int insertSelective(InquiryStatusMt row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    List<InquiryStatusMt> selectByExampleWithRowbounds(InquiryStatusMtExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    List<InquiryStatusMt> selectByExample(InquiryStatusMtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    InquiryStatusMt selectByPrimaryKey(InquiryStatusMtKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    int updateByExampleSelective(@Param("row") InquiryStatusMt row, @Param("example") InquiryStatusMtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    int updateByExample(@Param("row") InquiryStatusMt row, @Param("example") InquiryStatusMtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    int updateByPrimaryKeySelective(InquiryStatusMt row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    int updateByPrimaryKey(InquiryStatusMt row);
}