package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.NewsInfo;
import jp.co.ha.db.entity.NewsInfoExample;
import jp.co.ha.db.entity.NewsInfoKey;

/**
 * お知らせ情報Mapper
 *
 * @version 1.0.0
 */
public interface NewsInfoMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    long countByExample(NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    int deleteByExample(NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    int deleteByPrimaryKey(NewsInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    int insert(NewsInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    int insertSelective(NewsInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    List<NewsInfo> selectByExampleWithRowbounds(NewsInfoExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    List<NewsInfo> selectByExample(NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    NewsInfo selectByPrimaryKey(NewsInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    int updateByExampleSelective(@Param("record") NewsInfo record,
            @Param("example") NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    int updateByExample(@Param("record") NewsInfo record,
            @Param("example") NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    int updateByPrimaryKeySelective(NewsInfo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table news_info
     *
     * @mbg.generated Sat May 08 22:44:13 GMT+09:00 2021
     */
    int updateByPrimaryKey(NewsInfo record);
}