package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.NewsInfo;
import jp.co.ha.db.entity.NewsInfoExample;
import jp.co.ha.db.entity.NewsInfoKey;

/**
 * お知らせ情報Mapper
 *
 * @version 1.0.0
 */
public interface NewsInfoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    long countByExample(NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    int deleteByExample(NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    int deleteByPrimaryKey(NewsInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    int insert(NewsInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    int insertSelective(NewsInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    List<NewsInfo> selectByExampleWithRowbounds(NewsInfoExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    List<NewsInfo> selectByExample(NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    NewsInfo selectByPrimaryKey(NewsInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    int updateByExampleSelective(@Param("row") NewsInfo row,
            @Param("example") NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    int updateByExample(@Param("row") NewsInfo row,
            @Param("example") NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    int updateByPrimaryKeySelective(NewsInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    int updateByPrimaryKey(NewsInfo row);
}