package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.RootLoginInfo;
import jp.co.ha.db.entity.RootLoginInfoExample;
import jp.co.ha.db.entity.RootLoginInfoKey;

/**
 * 管理者サイトユーザログイン情報Mapper
 *
 * @version 1.0.0
 */
public interface RootLoginInfoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    long countByExample(RootLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByExample(RootLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByPrimaryKey(RootLoginInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insert(RootLoginInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insertSelective(RootLoginInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<RootLoginInfo> selectByExampleWithRowbounds(RootLoginInfoExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<RootLoginInfo> selectByExample(RootLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    RootLoginInfo selectByPrimaryKey(RootLoginInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") RootLoginInfo row,
            @Param("example") RootLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExample(@Param("row") RootLoginInfo row,
            @Param("example") RootLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(RootLoginInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_LOGIN_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKey(RootLoginInfo row);
}