package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.RootLoginInfo;
import jp.co.ha.db.entity.RootLoginInfoExample;
import jp.co.ha.db.entity.RootLoginInfoKey;

/**
 * 管理者サイトユーザログイン情報Mapper
 *
 * @version 1.0.0
 */
public interface RootLoginInfoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    long countByExample(RootLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    int deleteByExample(RootLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    int deleteByPrimaryKey(RootLoginInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    int insert(RootLoginInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    int insertSelective(RootLoginInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    List<RootLoginInfo> selectByExampleWithRowbounds(RootLoginInfoExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    List<RootLoginInfo> selectByExample(RootLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    RootLoginInfo selectByPrimaryKey(RootLoginInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    int updateByExampleSelective(@Param("row") RootLoginInfo row,
            @Param("example") RootLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    int updateByExample(@Param("row") RootLoginInfo row,
            @Param("example") RootLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    int updateByPrimaryKeySelective(RootLoginInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_login_info
     * 
     * @mbg.generated Sun Dec 15 12:08:13 GMT+09:00 2024
     */
    int updateByPrimaryKey(RootLoginInfo row);
}