package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.RootUserNoteInfo;
import jp.co.ha.db.entity.RootUserNoteInfoExample;
import jp.co.ha.db.entity.RootUserNoteInfoKey;

public interface RootUserNoteInfoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    long countByExample(RootUserNoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByExample(RootUserNoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByPrimaryKey(RootUserNoteInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insert(RootUserNoteInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insertSelective(RootUserNoteInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<RootUserNoteInfo> selectByExampleWithRowbounds(RootUserNoteInfoExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<RootUserNoteInfo> selectByExample(RootUserNoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    RootUserNoteInfo selectByPrimaryKey(RootUserNoteInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExampleSelective(@Param("row") RootUserNoteInfo row,
            @Param("example") RootUserNoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExample(@Param("row") RootUserNoteInfo row,
            @Param("example") RootUserNoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKeySelective(RootUserNoteInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_note_info
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKey(RootUserNoteInfo row);
}