package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.RootUserNoteInfo;
import jp.co.ha.db.entity.RootUserNoteInfoExample;
import jp.co.ha.db.entity.RootUserNoteInfoKey;

/**
 * 管理者サイトユーザメモ情報Mapper
 *
 * @version 1.0.0
 */
public interface RootUserNoteInfoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    long countByExample(RootUserNoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByExample(RootUserNoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByPrimaryKey(RootUserNoteInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insert(RootUserNoteInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insertSelective(RootUserNoteInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<RootUserNoteInfo> selectByExampleWithRowbounds(RootUserNoteInfoExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<RootUserNoteInfo> selectByExample(RootUserNoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    RootUserNoteInfo selectByPrimaryKey(RootUserNoteInfoKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") RootUserNoteInfo row,
            @Param("example") RootUserNoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExample(@Param("row") RootUserNoteInfo row,
            @Param("example") RootUserNoteInfoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(RootUserNoteInfo row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKey(RootUserNoteInfo row);
}