package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.RootRoleMt;
import jp.co.ha.db.entity.RootRoleMtExample;
import jp.co.ha.db.entity.RootRoleMtKey;

/**
 * 管理者サイト権限マスタMapper
 *
 * @version 1.0.0
 */
public interface RootRoleMtMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    long countByExample(RootRoleMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByExample(RootRoleMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByPrimaryKey(RootRoleMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insert(RootRoleMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insertSelective(RootRoleMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<RootRoleMt> selectByExampleWithRowbounds(RootRoleMtExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<RootRoleMt> selectByExample(RootRoleMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    RootRoleMt selectByPrimaryKey(RootRoleMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExampleSelective(@Param("row") RootRoleMt row,
            @Param("example") RootRoleMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExample(@Param("row") RootRoleMt row,
            @Param("example") RootRoleMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKeySelective(RootRoleMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_role_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKey(RootRoleMt row);
}