package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.RootUserRoleMngMt;
import jp.co.ha.db.entity.RootUserRoleMngMtExample;
import jp.co.ha.db.entity.RootUserRoleMngMtKey;

/**
 * 管理者サイトユーザ権限管理マスタMapper
 *
 * @version 1.0.0
 */
public interface RootUserRoleMngMtMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    long countByExample(RootUserRoleMngMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByExample(RootUserRoleMngMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByPrimaryKey(RootUserRoleMngMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insert(RootUserRoleMngMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insertSelective(RootUserRoleMngMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<RootUserRoleMngMt> selectByExampleWithRowbounds(RootUserRoleMngMtExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<RootUserRoleMngMt> selectByExample(RootUserRoleMngMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    RootUserRoleMngMt selectByPrimaryKey(RootUserRoleMngMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExampleSelective(@Param("row") RootUserRoleMngMt row,
            @Param("example") RootUserRoleMngMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExample(@Param("row") RootUserRoleMngMt row,
            @Param("example") RootUserRoleMngMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKeySelective(RootUserRoleMngMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_mng_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKey(RootUserRoleMngMt row);
}