package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.RootUserRoleDetailMt;
import jp.co.ha.db.entity.RootUserRoleDetailMtExample;
import jp.co.ha.db.entity.RootUserRoleDetailMtKey;

/**
 * 管理者サイトユーザ権限詳細マスタMapper
 *
 * @version 1.0.0
 */
public interface RootUserRoleDetailMtMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    long countByExample(RootUserRoleDetailMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByExample(RootUserRoleDetailMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int deleteByPrimaryKey(RootUserRoleDetailMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insert(RootUserRoleDetailMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int insertSelective(RootUserRoleDetailMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<RootUserRoleDetailMt> selectByExampleWithRowbounds(
            RootUserRoleDetailMtExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    List<RootUserRoleDetailMt> selectByExample(RootUserRoleDetailMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    RootUserRoleDetailMt selectByPrimaryKey(RootUserRoleDetailMtKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExampleSelective(@Param("row") RootUserRoleDetailMt row,
            @Param("example") RootUserRoleDetailMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByExample(@Param("row") RootUserRoleDetailMt row,
            @Param("example") RootUserRoleDetailMtExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKeySelective(RootUserRoleDetailMt row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     * 
     * @mbg.generated Sat Dec 21 15:17:08 GMT+09:00 2024
     */
    int updateByPrimaryKey(RootUserRoleDetailMt row);
}