package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.User;
import jp.co.ha.db.entity.UserExample;
import jp.co.ha.db.entity.UserKey;

/**
 * ユーザ情報Mapper
 *
 * @version 1.0.0
 */
public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    User selectByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") User row,
            @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKey(User row);
}