package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.UserRecoveryToken;
import jp.co.ha.db.entity.UserRecoveryTokenExample;
import jp.co.ha.db.entity.UserRecoveryTokenKey;

/**
 * ユーザ回復トークン情報Mapper
 *
 * @version 1.0.0
 */
public interface UserRecoveryTokenMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    long countByExample(UserRecoveryTokenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByExample(UserRecoveryTokenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByPrimaryKey(UserRecoveryTokenKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insert(UserRecoveryToken row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insertSelective(UserRecoveryToken row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<UserRecoveryToken> selectByExampleWithRowbounds(UserRecoveryTokenExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<UserRecoveryToken> selectByExample(UserRecoveryTokenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    UserRecoveryToken selectByPrimaryKey(UserRecoveryTokenKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") UserRecoveryToken row,
            @Param("example") UserRecoveryTokenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExample(@Param("row") UserRecoveryToken row,
            @Param("example") UserRecoveryTokenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(UserRecoveryToken row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_RECOVERY_TOKEN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKey(UserRecoveryToken row);
}