package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.UserHealthGoal;
import jp.co.ha.db.entity.UserHealthGoalExample;
import jp.co.ha.db.entity.UserHealthGoalKey;

/**
 * ユーザ健康目標情報Mapper
 *
 * @version 1.0.0
 */
public interface UserHealthGoalMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    long countByExample(UserHealthGoalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    int deleteByExample(UserHealthGoalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    int deleteByPrimaryKey(UserHealthGoalKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    int insert(UserHealthGoal row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    int insertSelective(UserHealthGoal row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    List<UserHealthGoal> selectByExampleWithRowbounds(UserHealthGoalExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    List<UserHealthGoal> selectByExample(UserHealthGoalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    UserHealthGoal selectByPrimaryKey(UserHealthGoalKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    int updateByExampleSelective(@Param("row") UserHealthGoal row,
            @Param("example") UserHealthGoalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    int updateByExample(@Param("row") UserHealthGoal row,
            @Param("example") UserHealthGoalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    int updateByPrimaryKeySelective(UserHealthGoal row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_health_goal
     *
     * @mbg.generated Sun Jul 27 19:47:35 GMT+09:00 2025
     */
    int updateByPrimaryKey(UserHealthGoal row);
}