package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.UserHealthGoal;
import jp.co.ha.db.entity.UserHealthGoalExample;
import jp.co.ha.db.entity.UserHealthGoalKey;

/**
 * ユーザ健康目標情報Mapper
 *
 * @version 1.0.0
 */
public interface UserHealthGoalMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    long countByExample(UserHealthGoalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByExample(UserHealthGoalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int deleteByPrimaryKey(UserHealthGoalKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insert(UserHealthGoal row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int insertSelective(UserHealthGoal row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<UserHealthGoal> selectByExampleWithRowbounds(UserHealthGoalExample example,
            RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    List<UserHealthGoal> selectByExample(UserHealthGoalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    UserHealthGoal selectByPrimaryKey(UserHealthGoalKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExampleSelective(@Param("row") UserHealthGoal row,
            @Param("example") UserHealthGoalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByExample(@Param("row") UserHealthGoal row,
            @Param("example") UserHealthGoalExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKeySelective(UserHealthGoal row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    int updateByPrimaryKey(UserHealthGoal row);
}