package jp.co.ha.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.ha.db.entity.User;
import jp.co.ha.db.entity.UserExample;
import jp.co.ha.db.entity.UserKey;

/**
 * ユーザ情報Mapper
 *
 * @version 1.0.0
 */
public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    int deleteByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    User selectByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    int updateByExampleSelective(@Param("row") User row,
            @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    int updateByPrimaryKey(User row);
}