ALTER TABLE API_COMMUNICATION_DATA modify COLUMN HTTP_METHOD VARCHAR(16) COMMENT 'HTTPメソッド';
ALTER TABLE API_COMMUNICATION_DATA modify COLUMN URL VARCHAR(256) COMMENT 'リクエストURL';
ALTER TABLE API_COMMUNICATION_DATA modify COLUMN BODY VARCHAR(1024) COMMENT 'リクエストBody';
