-- ユーザ情報
CREATE TABLE IF NOT EXISTS USER_DATA (
  -- ユーザID
  SEQ_USER_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'ユーザID',
  -- パスワード
  PASSWORD VARCHAR(64) NOT NULL COMMENT 'パスワード',
  -- メールアドレス
  MAIL_ADDRESS VARCHAR(512) NOT NULL COMMENT 'メールアドレス',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL COMMENT '削除フラグ',
  -- パスワード有効期限
  PASSWORD_EXPIRE DATE NOT NULL COMMENT 'パスワード有効期限',
  -- 備考
  REMARKS VARCHAR(256) COMMENT '備考',
  -- APIキー
  API_KEY VARCHAR(64) COMMENT 'APIキー',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

-- ユーザ回復トークン情報
CREATE TABLE IF NOT EXISTS USER_RECOVERY_TOKEN (
  -- アカウント回復トークン情報ID
  SEQ_USER_RECOVERY_TOKEN_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'アカウント回復トークン情報ID',
  -- ユーザID
  SEQ_USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
  -- トークン
  TOKEN VARCHAR(64) NOT NULL COMMENT 'トークン',
  -- トークン作成日時
  TOKEN_CREATE_DATE DATETIME NOT NULL COMMENT 'トークン作成日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);
