-- API通信情報
CREATE TABLE IF NOT EXISTS API_COMMUNICATION_DATA (
  -- API通信情報ID
  SEQ_API_COMMUNICATION_DATA_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'API通信情報ID',
  -- API名
  API_NAME VARCHAR(64) NOT NULL COMMENT 'API名',
  -- ユーザID
  SEQ_USER_ID INT COMMENT 'ユーザID',
  -- HTTPステータス
  HTTP_STATUS VARCHAR(3) COMMENT 'HTTPステータス',
  -- 処理結果
  RESULT VARCHAR(1) COMMENT '処理結果',
  -- エラー詳細
  DETAIL VARCHAR(256) COMMENT 'エラー詳細',
  -- リクエスト送信日時
  REQUEST_DATE DATETIME NOT NULL COMMENT 'リクエスト送信日時',
  -- レスポンス受信日時
  RESPONSE_DATE DATETIME COMMENT 'レスポンス受信日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);
