ALTER TABLE API_COMMUNICATION_DATA CHANGE COLUMN HTTP_METHOD HTTP_METHOD VARCHAR(16) COMMENT 'HTTPメソッド';
ALTER TABLE API_COMMUNICATION_DATA CHANGE COLUMN URL URL VARCHAR(256) COMMENT 'リクエストURL';
ALTER TABLE API_COMMUNICATION_DATA CHANGE COLUMN BODY BODY VARCHAR(1024) COMMENT 'リクエストBody';

ALTER TABLE API_COMMUNICATION_DATA MODIFY HTTP_METHOD text after API_NAME;
ALTER TABLE API_COMMUNICATION_DATA MODIFY URL text after HTTP_METHOD;
ALTER TABLE API_COMMUNICATION_DATA MODIFY BODY text after URL;
