ALTER TABLE INQUIRY_MANAGEMENT ALTER COLUMN DELETE_FLAG SET DEFAULT FALSE;
ALTER TABLE NEWS_INFO ALTER COLUMN DELETE_FLAG SET DEFAULT FALSE;
ALTER TABLE ROOT_LOGIN_INFO ALTER COLUMN DELETE_FLAG SET DEFAULT FALSE;
ALTER TABLE ROOT_USER_NOTE_INFO ALTER COLUMN DELETE_FLAG SET DEFAULT FALSE;
ALTER TABLE USER_HEALTH_GOAL ALTER COLUMN DELETE_FLAG SET DEFAULT FALSE;
ALTER TABLE USER ALTER COLUMN DELETE_FLAG SET DEFAULT FALSE;