-- DDL
-- API通信情報
CREATE TABLE IF NOT EXISTS API_COMMUNICATION_DATA (
  -- API通信情報ID
  SEQ_API_COMMUNICATION_DATA_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'API通信情報ID',
  -- トランザクションID
  TRANSACTION_ID VARCHAR(36) NOT NULL COMMENT 'トランザクションID',
  -- API名
  API_NAME VARCHAR(64) NOT NULL COMMENT 'API名',
  -- HTTPメソッド
  HTTP_METHOD VARCHAR(16) NOT NULL COMMENT 'HTTPメソッド',
  -- URL
  URL VARCHAR(256) NOT NULL COMMENT 'URL',
  -- リクエストBody
  BODY VARCHAR(1024) COMMENT 'リクエストBody',
  -- HTTPステータス
  HTTP_STATUS VARCHAR(3) COMMENT 'HTTPステータス',
  -- エラー詳細
  DETAIL VARCHAR(256) COMMENT 'エラー詳細',
  -- リクエスト送信日時
  REQUEST_DATE DATETIME NOT NULL COMMENT 'リクエスト送信日時',
  -- レスポンス受信日時
  RESPONSE_DATE DATETIME COMMENT 'レスポンス受信日時',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- BMI範囲マスタ
CREATE TABLE IF NOT EXISTS BMI_RANGE_MT (
  -- BMI範囲マスタID
  SEQ_BMI_RANGE_MT_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'BMI範囲マスタID',
  -- 範囲下限
  RANGE_MIN INT NOT NULL COMMENT '範囲下限',
  -- 範囲上限
  RANGE_MAX INT NOT NULL COMMENT '範囲上限',
  -- 肥満度ステータス
  OVER_WEIGHT_STATUS VARCHAR(2) NOT NULL COMMENT '肥満度ステータス',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 健康情報ファイル設定
CREATE TABLE IF NOT EXISTS HEALTH_INFO_FILE_SETTING (
  -- ユーザID
  SEQ_USER_ID BIGINT NOT NULL PRIMARY KEY COMMENT 'ユーザID',
  -- ヘッダーフラグ
  HEADER_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'ヘッダーフラグ',
  -- フッターフラグ
  FOOTER_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'フッターフラグ',
  -- マスクフラグ
  MASK_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'マスクフラグ',
  -- 囲い文字利用フラグ
  ENCLOSURE_CHAR_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '囲い文字利用フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 健康情報
CREATE TABLE IF NOT EXISTS HEALTH_INFO (
  -- 健康情報ID
  SEQ_HEALTH_INFO_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '健康情報ID',
  -- ユーザID
  SEQ_USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
  -- 身長
  HEIGHT DECIMAL(6, 3) NOT NULL COMMENT '身長',
  -- 体重
  WEIGHT DECIMAL(6, 3) NOT NULL COMMENT '体重',
  -- BMI
  BMI DECIMAL(6, 3) NOT NULL COMMENT 'BMI',
  -- 標準体重
  STANDARD_WEIGHT DECIMAL(6, 3) NOT NULL COMMENT '標準体重',
  -- 健康情報作成日時
  HEALTH_INFO_REG_DATE DATETIME NOT NULL COMMENT '健康情報作成日時',
  -- BMI範囲マスタID
  SEQ_BMI_RANGE_MT_ID BIGINT NOT NULL COMMENT 'BMI範囲マスタID',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 問い合わせ管理情報
CREATE TABLE IF NOT EXISTS INQUIRY_MANAGEMENT (
  -- 問い合わせID
  SEQ_INQUIRY_MNG_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '問い合わせID',
  -- ユーザID
  SEQ_USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
  -- S3キー
  S3_KEY VARCHAR(100) NOT NULL COMMENT 'S3キー',
  -- 問い合わせステータス
  INQUIRY_STATUS VARCHAR(2) NOT NULL COMMENT '問い合わせステータス',
  -- 問い合わせ種別
  INQUIRY_TYPE VARCHAR(2) COMMENT '問い合わせ種別',
  -- タイトル
  TITLE VARCHAR(100) NOT NULL COMMENT 'タイトル',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 対応者ログイン情報ID
  RESPONDER_LOGIN_ID BIGINT COMMENT '対応者ログイン情報ID'
);

-- 問い合わせステータスマスタ
CREATE TABLE IF NOT EXISTS INQUIRY_STATUS_MT (
  -- 問い合わせステータス
  INQUIRY_STATUS VARCHAR(2) NOT NULL PRIMARY KEY COMMENT '問い合わせステータス',
  -- 名前
  NAME VARCHAR(16) NOT NULL COMMENT '名前',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 問い合わせ種別マスタ
CREATE TABLE IF NOT EXISTS INQUIRY_TYPE_MT (
  -- 問い合わせ種別
  INQUIRY_TYPE VARCHAR(2) NOT NULL PRIMARY KEY COMMENT '問い合わせ種別',
  -- 名前
  NAME VARCHAR(16) NOT NULL COMMENT '名前',
  -- 補足説明
  DESCRIPTION VARCHAR(64) COMMENT '補足説明',
  -- 表示フラグ
  DISP_FLAG BOOLEAN NOT NULL DEFAULT TRUE COMMENT '表示フラグ',
  -- 表示順
  DISP_ORDER INT NOT NULL COMMENT '表示順',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- お知らせ情報
CREATE TABLE IF NOT EXISTS NEWS_INFO (
  -- お知らせ情報ID
  SEQ_NEWS_INFO_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'お知らせ情報ID',
  -- S3キー
  S3_KEY VARCHAR(100) NOT NULL COMMENT 'S3キー',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 管理者サイトユーザログイン情報
CREATE TABLE IF NOT EXISTS ROOT_LOGIN_INFO (
  -- 管理者サイトユーザログイン情報ID
  SEQ_ROOT_LOGIN_INFO_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '管理者サイトユーザログイン情報ID',
  -- パスワード
  PASSWORD VARCHAR(64) NOT NULL COMMENT 'パスワード',
  -- パスワード有効期限
  PASSWORD_EXPIRE DATE NOT NULL COMMENT 'パスワード有効期限',
  -- 管理者サイトユーザ権限管理マスタID
  SEQ_ROOT_USER_ROLE_MNG_MT_ID BIGINT NOT NULL COMMENT '管理者サイトユーザ権限管理マスタID',
  -- 備考
  REMARKS VARCHAR(256) COMMENT '備考',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 管理者サイト権限マスタ
CREATE TABLE IF NOT EXISTS ROOT_ROLE_MT (
  -- 管理者サイト権限マスタID
  SEQ_ROOT_ROLE_MT_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '管理者サイト権限マスタID',
  -- ユーザ権限
  ROLE VARCHAR(2) NOT NULL COMMENT 'ユーザ権限',
  -- ユーザ権限名
  ROLE_NAME VARCHAR(64) NOT NULL COMMENT 'ユーザ権限名',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 管理者サイトユーザメモ情報
CREATE TABLE IF NOT EXISTS ROOT_USER_NOTE_INFO (
  -- メモユーザ情報ID
  SEQ_ROOT_USER_NOTE_INFO_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'メモユーザ情報ID',
  -- 管理者サイトユーザログイン情報ID
  SEQ_ROOT_LOGIN_INFO_ID BIGINT NOT NULL COMMENT '管理者サイトユーザログイン情報ID',
  -- 件名
  TITLE VARCHAR(30) NOT NULL COMMENT '件名',
  -- S3キー
  S3_KEY VARCHAR(100) NOT NULL COMMENT 'S3キー',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 管理者サイトユーザ権限詳細マスタ
CREATE TABLE IF NOT EXISTS ROOT_USER_ROLE_DETAIL_MT (
  -- 管理者サイトユーザ権限詳細マスタID
  SEQ_ROOT_USER_ROLE_DETAIL_MT_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '管理者サイトユーザ権限詳細マスタID',
  -- 管理者サイトユーザ権限管理マスタID
  SEQ_ROOT_USER_ROLE_MNG_MT_ID BIGINT NOT NULL COMMENT '管理者サイトユーザ権限管理マスタID',
  -- 管理者サイト権限マスタID
  SEQ_ROOT_ROLE_MT_ID BIGINT NOT NULL COMMENT '管理者サイト権限マスタID',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 管理者サイトユーザ権限管理マスタ
CREATE TABLE IF NOT EXISTS ROOT_USER_ROLE_MNG_MT (
  -- 管理者サイトユーザ権限管理マスタID
  SEQ_ROOT_USER_ROLE_MNG_MT_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '管理者サイトユーザ権限管理マスタID',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

-- ユーザ健康目標情報
CREATE TABLE IF NOT EXISTS USER_HEALTH_GOAL (
  -- 目標ID
  SEQ_HEALTH_GOAL_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '目標ID',
  -- ユーザID
  SEQ_USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
  -- 体重
  WEIGHT DECIMAL(6, 3) NOT NULL COMMENT '体重',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- ユーザ回復トークン情報
CREATE TABLE IF NOT EXISTS USER_RECOVERY_TOKEN (
  -- アカウント回復トークン情報ID
  SEQ_USER_RECOVERY_TOKEN_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'アカウント回復トークン情報ID',
  -- ユーザID
  SEQ_USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
  -- トークン
  TOKEN VARCHAR(64) NOT NULL COMMENT 'トークン',
  -- トークン作成日時
  TOKEN_CREATE_DATE DATETIME NOT NULL COMMENT 'トークン作成日時',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- ユーザ情報
CREATE TABLE IF NOT EXISTS USER (
  -- ユーザID
  SEQ_USER_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'ユーザID',
  -- パスワード
  PASSWORD VARCHAR(64) NOT NULL COMMENT 'パスワード',
  -- メールアドレス
  MAIL_ADDRESS VARCHAR(512) NOT NULL COMMENT 'メールアドレス',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- パスワード有効期限
  PASSWORD_EXPIRE DATE NOT NULL COMMENT 'パスワード有効期限',
  -- 備考
  REMARKS VARCHAR(256) COMMENT '備考',
  -- APIキー
  API_KEY VARCHAR(64) NOT NULL COMMENT 'APIキー',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 性別
  GENDER_TYPE INT NOT NULL DEFAULT 0 COMMENT '性別',
  -- 誕生日
  BIRTH_DATE DATE NOT NULL DEFAULT '2000/01/01' COMMENT '誕生日'
);

-- SpringBatchのメタデータを作成するためのSQL
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT;

SET foreign_key_checks = 0;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION;
SET foreign_key_checks = 1;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ (ID BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ (ID BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS BATCH_JOB_SEQ (ID BIGINT NOT NULL);

INSERT INTO BATCH_JOB_EXECUTION_SEQ VALUES (0);
INSERT INTO BATCH_STEP_EXECUTION_SEQ VALUES (0);
INSERT INTO BATCH_JOB_SEQ VALUES (0);

CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE  (
  JOB_INSTANCE_ID BIGINT  PRIMARY KEY ,
  VERSION BIGINT,
  JOB_NAME VARCHAR(100) NOT NULL ,
  JOB_KEY VARCHAR(2500)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION  (
  JOB_EXECUTION_ID BIGINT  PRIMARY KEY ,
  VERSION BIGINT,
  JOB_INSTANCE_ID BIGINT NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL,
  START_TIME TIMESTAMP DEFAULT NULL,
  END_TIME TIMESTAMP DEFAULT NULL,
  STATUS VARCHAR(10),
  EXIT_CODE VARCHAR(20),
  EXIT_MESSAGE VARCHAR(2500),
  LAST_UPDATED TIMESTAMP,
  JOB_CONFIGURATION_LOCATION VARCHAR(2500) NULL,
  CONSTRAINT JOB_INSTANCE_EXECUTION_FK
  FOREIGN KEY (JOB_INSTANCE_ID)
  REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS  (
	JOB_EXECUTION_ID BIGINT NOT NULL ,
	PARAMETER_NAME VARCHAR(100) NOT NULL ,
	PARAMETER_TYPE VARCHAR(100) NOT NULL ,
	PARAMETER_VALUE VARCHAR(2500) ,
	IDENTIFYING CHAR(1) NOT NULL ,
	CONSTRAINT JOB_EXEC_PARAMS_FK
	FOREIGN KEY (JOB_EXECUTION_ID)
	REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION  (
  STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY ,
  VERSION BIGINT NOT NULL,
  STEP_NAME VARCHAR(100) NOT NULL,
  JOB_EXECUTION_ID BIGINT NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL,
  START_TIME TIMESTAMP DEFAULT NULL ,
  END_TIME TIMESTAMP DEFAULT NULL,
  STATUS VARCHAR(10),
  COMMIT_COUNT BIGINT ,
  READ_COUNT BIGINT ,
  FILTER_COUNT BIGINT ,
  WRITE_COUNT BIGINT ,
  READ_SKIP_COUNT BIGINT ,
  WRITE_SKIP_COUNT BIGINT ,
  PROCESS_SKIP_COUNT BIGINT ,
  ROLLBACK_COUNT BIGINT ,
  EXIT_CODE VARCHAR(20) ,
  EXIT_MESSAGE VARCHAR(2500) ,
  LAST_UPDATED TIMESTAMP,
  CONSTRAINT JOB_EXECUTION_STEP_FK
  FOREIGN KEY (JOB_EXECUTION_ID)
  REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT  (
  JOB_EXECUTION_ID BIGINT PRIMARY KEY,
  SHORT_CONTEXT VARCHAR(2500) NOT NULL,
  SERIALIZED_CONTEXT BLOB,
  CONSTRAINT JOB_EXEC_CTX_FK
  FOREIGN KEY (JOB_EXECUTION_ID)
  REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT  (
  STEP_EXECUTION_ID BIGINT PRIMARY KEY,
  SHORT_CONTEXT VARCHAR(2500) NOT NULL,
  SERIALIZED_CONTEXT BLOB,
  CONSTRAINT STEP_EXEC_CTX_FK
  FOREIGN KEY (STEP_EXECUTION_ID)
  REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;


-- DML
INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('0','18','10',FALSE,'2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('18','25','11',FALSE,'2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('25','30','12',FALSE,'2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('30','35','13',FALSE,'2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('35','40','14',FALSE,'2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('40','999','15',FALSE,'2020/07/26 12:34:56','2020/07/26 12:34:56');

INSERT INTO INQUIRY_STATUS_MT (INQUIRY_STATUS,NAME,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('00','未対応',FALSE,'2025/8/9 9:38:12','2025/8/9 9:38:12');
INSERT INTO INQUIRY_STATUS_MT (INQUIRY_STATUS,NAME,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('01','対応中',FALSE,'2025/8/9 9:38:12','2025/8/9 9:38:12');
INSERT INTO INQUIRY_STATUS_MT (INQUIRY_STATUS,NAME,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('02','完了',FALSE,'2025/8/9 9:38:12','2025/8/9 9:38:12');

INSERT INTO INQUIRY_TYPE_MT (INQUIRY_TYPE,NAME,DESCRIPTION,DISP_FLAG,DISP_ORDER,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('00','不具合','アプリケーションの不具合や通信エラー時に指定',TRUE,'1',FALSE,'2025/8/9 9:38:12','2025/8/9 9:38:12');
INSERT INTO INQUIRY_TYPE_MT (INQUIRY_TYPE,NAME,DESCRIPTION,DISP_FLAG,DISP_ORDER,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('01','要望','アプリケーションの改善点の報告時に指定',TRUE,'2',FALSE,'2025/8/9 9:38:12','2025/8/9 9:38:12');

INSERT INTO ROOT_ROLE_MT (ROLE,ROLE_NAME,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('00','管理者権限',FALSE,'2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO ROOT_ROLE_MT (ROLE,ROLE_NAME,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('01','照会権限',FALSE,'2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO ROOT_ROLE_MT (ROLE,ROLE_NAME,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('02','作成権限',FALSE,'2020/07/26 12:34:56','2020/07/26 12:34:56');
