ALTER TABLE HEALTH_INFO_FILE_SETTING CHANGE COLUMN HEADER_FLAG HEADER_FLAG BOOLEAN COMMENT 'ヘッダーフラグ';
ALTER TABLE HEALTH_INFO_FILE_SETTING CHANGE COLUMN FOOTER_FLAG FOOTER_FLAG BOOLEAN COMMENT 'フッターフラグ';
ALTER TABLE HEALTH_INFO_FILE_SETTING CHANGE COLUMN MASK_FLAG MASK_FLAG BOOLEAN COMMENT 'マスクフラグ';
ALTER TABLE HEALTH_INFO_FILE_SETTING CHANGE COLUMN ENCLOSURE_CHAR_FLAG ENCLOSURE_CHAR_FLAG BOOLEAN COMMENT '囲い文字利用フラグ';

ALTER TABLE ROOT_LOGIN_INFO CHANGE COLUMN DELETE_FLAG DELETE_FLAG BOOLEAN NOT NULL COMMENT '削除フラグ';