-- アカウント情報
CREATE TABLE IF NOT EXISTS ACCOUNT (
  -- ユーザID
  SEQ_USER_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'ユーザID',
  -- パスワード
  PASSWORD VARCHAR(64) NOT NULL COMMENT 'パスワード',
  -- メールアドレス
  MAIL_ADDRESS VARCHAR(512) NOT NULL COMMENT 'メールアドレス',
  -- 削除フラグ
  DELETE_FLAG VARCHAR(1) NOT NULL COMMENT '削除フラグ',
  -- パスワード有効期限
  PASSWORD_EXPIRE DATE NOT NULL COMMENT 'パスワード有効期限',
  -- 備考
  REMARKS VARCHAR(256) COMMENT '備考',
  -- APIキー
  API_KEY VARCHAR(64) COMMENT 'APIキー',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

-- BMI範囲マスタ
CREATE TABLE IF NOT EXISTS BMI_RANGE_MT (
  -- BMI範囲マスタID
  SEQ_BMI_RANGE_MT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'BMI範囲マスタID',
  -- 範囲下限
  RANGE_MIN INT COMMENT '範囲下限',
  -- 範囲上限
  RANGE_MAX INT COMMENT '範囲上限',
  -- 肥満度ステータス
  OVER_WEIGHT_STATUS VARCHAR(2) COMMENT '肥満度ステータス',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

-- 健康情報ファイル設定
CREATE TABLE IF NOT EXISTS HEALTH_INFO_FILE_SETTING (
  -- ユーザID
  SEQ_USER_ID INT NOT NULL PRIMARY KEY COMMENT 'ユーザID',
  -- ヘッダーフラグ
  HEADER_FLAG VARCHAR(1) COMMENT 'ヘッダーフラグ',
  -- フッターフラグ
  FOOTER_FLAG VARCHAR(1) COMMENT 'フッターフラグ',
  -- マスクフラグ
  MASK_FLAG VARCHAR(1) COMMENT 'マスクフラグ',
  -- 囲い文字利用フラグ
  ENCLOSURE_CHAR_FLAG VARCHAR(1) COMMENT '囲い文字利用フラグ',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

-- 健康情報
CREATE TABLE IF NOT EXISTS HEALTH_INFO (
  -- 健康情報ID
  SEQ_HEALTH_INFO_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '健康情報ID',
  -- ユーザID
  SEQ_USER_ID INT NOT NULL COMMENT 'ユーザID',
  -- 身長
  HEIGHT DECIMAL(6, 3) COMMENT '身長',
  -- 体重
  WEIGHT DECIMAL(6, 3) COMMENT '体重',
  -- BMI
  BMI DECIMAL(6, 3) COMMENT 'BMI',
  -- 標準体重
  STANDARD_WEIGHT DECIMAL(6, 3) COMMENT '標準体重',
  -- 健康情報ステータス
  HEALTH_INFO_STATUS VARCHAR(2) COMMENT '健康情報ステータス',
  -- 健康情報作成日時
  HEALTH_INFO_REG_DATE DATETIME COMMENT '健康情報作成日時',
  -- BMI範囲マスタID
  SEQ_BMI_RANGE_MT_ID INT COMMENT 'BMI範囲マスタID',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

-- アカウント回復トークン情報
CREATE TABLE IF NOT EXISTS ACCOUNT_RECOVERY_TOKEN_DATA (
  -- アカウント回復トークン情報ID
  SEQ_ACCOUNT_RECOVERY_TOKEN_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'アカウント回復トークン情報ID',
  -- ユーザID
  SEQ_USER_ID INT NOT NULL COMMENT 'ユーザID',
  -- トークン
  TOKEN VARCHAR(64) NOT NULL COMMENT 'トークン',
  -- トークン作成日時
  TOKEN_CREATE_DATE DATETIME NOT NULL COMMENT 'トークン作成日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,UPDATE_DATE,REG_DATE) VALUES ('0','18','10','2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,UPDATE_DATE,REG_DATE) VALUES ('18','25','11','2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,UPDATE_DATE,REG_DATE) VALUES ('25','30','12','2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,UPDATE_DATE,REG_DATE) VALUES ('30','35','13','2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,UPDATE_DATE,REG_DATE) VALUES ('35','40','14','2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO BMI_RANGE_MT (RANGE_MIN,RANGE_MAX,OVER_WEIGHT_STATUS,UPDATE_DATE,REG_DATE) VALUES ('40','999','15','2020/07/26 12:34:56','2020/07/26 12:34:56');

-- API通信情報
CREATE TABLE IF NOT EXISTS API_COMMUNICATION_DATA (
  -- API通信情報ID
  SEQ_API_COMMUNICATION_DATA_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'API通信情報ID',
  -- トランザクションID
  TRANSACTION_ID INT NOT NULL COMMENT 'トランザクションID',
  -- API名
  API_NAME VARCHAR(64) NOT NULL COMMENT 'API名',
  -- ユーザID
  SEQ_USER_ID INT COMMENT 'ユーザID',
  -- HTTPステータス
  HTTP_STATUS VARCHAR(3) COMMENT 'HTTPステータス',
  -- 処理結果
  RESULT VARCHAR(1) COMMENT '処理結果',
  -- エラー詳細
  DETAIL VARCHAR(256) COMMENT 'エラー詳細',
  -- リクエスト送信日時
  REQUEST_DATE DATETIME NOT NULL COMMENT 'リクエスト送信日時',
  -- レスポンス受信日時
  RESPONSE_DATE DATETIME COMMENT 'レスポンス受信日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

-- 管理者サイトユーザログイン情報
CREATE TABLE IF NOT EXISTS ROOT_LOGIN_INFO (
  -- 管理者サイトユーザログイン情報ID
  SEQ_ROOT_LOGIN_INFO_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '管理者サイトユーザログイン情報ID',
  -- パスワード
  PASSWORD VARCHAR(64) NOT NULL COMMENT 'パスワード',
  -- 削除フラグ
  DELETE_FLAG VARCHAR(1) NOT NULL COMMENT '削除フラグ',
  -- パスワード有効期限
  PASSWORD_EXPIRE DATE NOT NULL COMMENT 'パスワード有効期限',
  -- 管理者サイトユーザ権限管理マスタID
  SEQ_ROOT_USER_ROLE_MNG_MT_ID INT NOT NULL COMMENT '管理者サイトユーザ権限管理マスタID',
  -- 備考
  REMARKS VARCHAR(256) COMMENT '備考',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

-- 管理者サイトユーザ権限管理マスタ
CREATE TABLE IF NOT EXISTS ROOT_USER_ROLE_MNG_MT (
  -- 管理者サイトユーザ権限管理マスタID
  SEQ_ROOT_USER_ROLE_MNG_MT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '管理者サイトユーザ権限管理マスタID',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

-- 管理者サイトユーザ権限詳細マスタ
CREATE TABLE IF NOT EXISTS ROOT_USER_ROLE_DETAIL_MT (
  -- 管理者サイトユーザ権限詳細マスタID
  SEQ_ROOT_USER_ROLE_DETAIL_MT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '管理者サイトユーザ権限詳細マスタID',
  -- 管理者サイトユーザ権限管理マスタID
  SEQ_ROOT_USER_ROLE_MNG_MT_ID INT NOT NULL COMMENT '管理者サイトユーザ権限管理マスタID',
  -- 管理者サイト権限マスタID
  SEQ_ROOT_ROLE_MT_ID INT NOT NULL COMMENT '管理者サイト権限マスタID',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

-- 管理者サイト権限マスタ
CREATE TABLE IF NOT EXISTS ROOT_ROLE_MT (
  -- 管理者サイト権限マスタID
  SEQ_ROOT_ROLE_MT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '管理者サイト権限マスタID',
  -- ユーザ権限
  ROLE VARCHAR(2) NOT NULL COMMENT 'ユーザ権限',
  -- ユーザ権限名
  ROLE_NAME VARCHAR(64) NOT NULL COMMENT 'ユーザ権限名',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);

INSERT INTO ROOT_ROLE_MT (ROLE,ROLE_NAME,UPDATE_DATE,REG_DATE) VALUES ('00','管理者権限','2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO ROOT_ROLE_MT (ROLE,ROLE_NAME,UPDATE_DATE,REG_DATE) VALUES ('01','照会権限','2020/07/26 12:34:56','2020/07/26 12:34:56');
INSERT INTO ROOT_ROLE_MT (ROLE,ROLE_NAME,UPDATE_DATE,REG_DATE) VALUES ('02','作成権限','2020/07/26 12:34:56','2020/07/26 12:34:56');
