-- 問い合わせステータスマスタ
CREATE TABLE IF NOT EXISTS INQUIRY_STATUS_MT (
  -- 問い合わせステータス
  INQUIRY_STATUS VARCHAR(2) NOT NULL PRIMARY KEY COMMENT '問い合わせステータス',
  -- 名前
  NAME VARCHAR(16) NOT NULL COMMENT '名前',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- INQUIRY_TYPE_MT
INSERT INTO INQUIRY_TYPE_MT (INQUIRY_TYPE,NAME,DESCRIPTION,DISP_FLAG,DISP_ORDER,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('00','不具合','アプリケーションの不具合や通信エラー時に指定',TRUE,'1',FALSE,'2025/8/9 9:38:12','2025/8/9 9:38:12');
INSERT INTO INQUIRY_TYPE_MT (INQUIRY_TYPE,NAME,DESCRIPTION,DISP_FLAG,DISP_ORDER,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('01','要望','アプリケーションの改善点の報告時に指定',TRUE,'2',FALSE,'2025/8/9 9:38:12','2025/8/9 9:38:12');

-- INQUIRY_STATUS_MT
INSERT INTO INQUIRY_STATUS_MT (INQUIRY_STATUS,NAME,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('00','未対応',FALSE,'2025/8/9 9:38:12','2025/8/9 9:38:12');
INSERT INTO INQUIRY_STATUS_MT (INQUIRY_STATUS,NAME,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('01','対応中',FALSE,'2025/8/9 9:38:12','2025/8/9 9:38:12');
INSERT INTO INQUIRY_STATUS_MT (INQUIRY_STATUS,NAME,DELETE_FLAG,REG_DATE,UPDATE_DATE) VALUES ('02','完了',FALSE,'2025/8/9 9:38:12','2025/8/9 9:38:12');
