spring:
  # 設定ファイル読込
  config:
    import:
      - "classpath:/dev/jdbc.properties"
      - "classpath:/dev/system.properties"
      - "classpath:/dev/aws.properties"
      - "classpath:/dev/healthInfo.properties"
