-- アカウント情報
DROP TABLE IF EXISTS ACCOUNT;
-- 健康情報
DROP TABLE IF EXISTS HEALTH_INFO;
-- 健康情報ファイル設定
DROP TABLE IF EXISTS HEALTH_INFO_FILE_SETTING;
-- BMI範囲マスタ
DROP TABLE IF EXISTS BMI_RANGE_MT;
-- アカウント回復トークン
DROP TABLE IF EXISTS ACCOUNT_RECOVERY_TOKEN;