-- アカウント情報
DROP TABLE IF EXISTS ACCOUNT;
-- 健康情報
DROP TABLE IF EXISTS HEALTH_INFO;
-- 健康情報ファイル設定
DROP TABLE IF EXISTS HEALTH_INFO_FILE_SETTING;
-- メール情報
DROP TABLE IF EXISTS MAIL_INFO;
-- BMI範囲マスタ
DROP TABLE IF EXISTS BMI_RANGE_MT;