package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * アカウント回復トークンEntity
 *
 * @version 1.0.0
 */
@Entity
public class AccountRecoveryToken extends AccountRecoveryTokenKey
        implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account_recovery_token.SEQ_USER_ID
     *
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    private Integer seqUserId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account_recovery_token.TOKEN
     *
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    private String token;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account_recovery_token.TOKEN_CREATE_DATE
     *
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    private LocalDateTime tokenCreateDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account_recovery_token.UPDATE_DATE
     *
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    private LocalDateTime updateDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account_recovery_token.REG_DATE
     *
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table account_recovery_token
     *
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account_recovery_token.SEQ_USER_ID
     *
     * @return the value of account_recovery_token.SEQ_USER_ID
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    public Integer getSeqUserId() {
        return seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account_recovery_token.SEQ_USER_ID
     *
     * @param seqUserId
     *     the value for account_recovery_token.SEQ_USER_ID
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    public void setSeqUserId(Integer seqUserId) {
        this.seqUserId = seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account_recovery_token.TOKEN
     *
     * @return the value of account_recovery_token.TOKEN
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account_recovery_token.TOKEN
     *
     * @param token
     *     the value for account_recovery_token.TOKEN
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account_recovery_token.TOKEN_CREATE_DATE
     *
     * @return the value of account_recovery_token.TOKEN_CREATE_DATE
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    public LocalDateTime getTokenCreateDate() {
        return tokenCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account_recovery_token.TOKEN_CREATE_DATE
     *
     * @param tokenCreateDate
     *     the value for account_recovery_token.TOKEN_CREATE_DATE
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    public void setTokenCreateDate(LocalDateTime tokenCreateDate) {
        this.tokenCreateDate = tokenCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account_recovery_token.UPDATE_DATE
     *
     * @return the value of account_recovery_token.UPDATE_DATE
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account_recovery_token.UPDATE_DATE
     *
     * @param updateDate
     *     the value for account_recovery_token.UPDATE_DATE
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account_recovery_token.REG_DATE
     *
     * @return the value of account_recovery_token.REG_DATE
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account_recovery_token.REG_DATE
     *
     * @param regDate
     *     the value for account_recovery_token.REG_DATE
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqUserId=").append(seqUserId);
        sb.append(", token=").append(token);
        sb.append(", tokenCreateDate=").append(tokenCreateDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", regDate=").append(regDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AccountRecoveryToken other = (AccountRecoveryToken) that;
        return (this.getSeqAccountRecoveryTokenId() == null
                ? other.getSeqAccountRecoveryTokenId() == null
                : this.getSeqAccountRecoveryTokenId()
                        .equals(other.getSeqAccountRecoveryTokenId()))
                && (this.getSeqUserId() == null ? other.getSeqUserId() == null
                        : this.getSeqUserId().equals(other.getSeqUserId()))
                && (this.getToken() == null ? other.getToken() == null
                        : this.getToken().equals(other.getToken()))
                && (this.getTokenCreateDate() == null ? other.getTokenCreateDate() == null
                        : this.getTokenCreateDate().equals(other.getTokenCreateDate()))
                && (this.getUpdateDate() == null ? other.getUpdateDate() == null
                        : this.getUpdateDate().equals(other.getUpdateDate()))
                && (this.getRegDate() == null ? other.getRegDate() == null
                        : this.getRegDate().equals(other.getRegDate()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table account_recovery_token
     *
     * @mbg.generated Tue Nov 03 19:10:53 GMT+09:00 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSeqAccountRecoveryTokenId() == null) ? 0
                : getSeqAccountRecoveryTokenId().hashCode());
        result = prime * result
                + ((getSeqUserId() == null) ? 0 : getSeqUserId().hashCode());
        result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
        result = prime * result
                + ((getTokenCreateDate() == null) ? 0 : getTokenCreateDate().hashCode());
        result = prime * result
                + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getRegDate() == null) ? 0 : getRegDate().hashCode());
        return result;
    }
}