package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * API通信情報Entity
 *
 * @version 1.0.0
 */
@Entity
public class ApiCommunicationData extends ApiCommunicationDataKey
        implements Serializable {

    /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.TRANSACTION_ID
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private String transactionId;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.API_NAME
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private String apiName;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.HTTP_METHOD
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private String httpMethod;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.URL
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private String url;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.BODY
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private String body;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.HTTP_STATUS
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private String httpStatus;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.DETAIL
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private String detail;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.REQUEST_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private LocalDateTime requestDate;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.RESPONSE_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private LocalDateTime responseDate;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.DELETE_FLAG
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private Boolean deleteFlag;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.REG_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private LocalDateTime regDate;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column API_COMMUNICATION_DATA.UPDATE_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        private LocalDateTime updateDate;

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.TRANSACTION_ID
        * @return  the value of API_COMMUNICATION_DATA.TRANSACTION_ID
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public String getTransactionId() {
        return transactionId;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.TRANSACTION_ID
        * @param transactionId  the value for API_COMMUNICATION_DATA.TRANSACTION_ID
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.API_NAME
        * @return  the value of API_COMMUNICATION_DATA.API_NAME
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public String getApiName() {
        return apiName;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.API_NAME
        * @param apiName  the value for API_COMMUNICATION_DATA.API_NAME
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setApiName(String apiName) {
        this.apiName = apiName;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.HTTP_METHOD
        * @return  the value of API_COMMUNICATION_DATA.HTTP_METHOD
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public String getHttpMethod() {
        return httpMethod;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.HTTP_METHOD
        * @param httpMethod  the value for API_COMMUNICATION_DATA.HTTP_METHOD
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.URL
        * @return  the value of API_COMMUNICATION_DATA.URL
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public String getUrl() {
        return url;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.URL
        * @param url  the value for API_COMMUNICATION_DATA.URL
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setUrl(String url) {
        this.url = url;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.BODY
        * @return  the value of API_COMMUNICATION_DATA.BODY
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public String getBody() {
        return body;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.BODY
        * @param body  the value for API_COMMUNICATION_DATA.BODY
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setBody(String body) {
        this.body = body;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.HTTP_STATUS
        * @return  the value of API_COMMUNICATION_DATA.HTTP_STATUS
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public String getHttpStatus() {
        return httpStatus;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.HTTP_STATUS
        * @param httpStatus  the value for API_COMMUNICATION_DATA.HTTP_STATUS
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setHttpStatus(String httpStatus) {
        this.httpStatus = httpStatus;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.DETAIL
        * @return  the value of API_COMMUNICATION_DATA.DETAIL
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public String getDetail() {
        return detail;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.DETAIL
        * @param detail  the value for API_COMMUNICATION_DATA.DETAIL
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setDetail(String detail) {
        this.detail = detail;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.REQUEST_DATE
        * @return  the value of API_COMMUNICATION_DATA.REQUEST_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public LocalDateTime getRequestDate() {
        return requestDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.REQUEST_DATE
        * @param requestDate  the value for API_COMMUNICATION_DATA.REQUEST_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setRequestDate(LocalDateTime requestDate) {
        this.requestDate = requestDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.RESPONSE_DATE
        * @return  the value of API_COMMUNICATION_DATA.RESPONSE_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public LocalDateTime getResponseDate() {
        return responseDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.RESPONSE_DATE
        * @param responseDate  the value for API_COMMUNICATION_DATA.RESPONSE_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setResponseDate(LocalDateTime responseDate) {
        this.responseDate = responseDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.DELETE_FLAG
        * @return  the value of API_COMMUNICATION_DATA.DELETE_FLAG
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public Boolean getDeleteFlag() {
        return deleteFlag;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.DELETE_FLAG
        * @param deleteFlag  the value for API_COMMUNICATION_DATA.DELETE_FLAG
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.REG_DATE
        * @return  the value of API_COMMUNICATION_DATA.REG_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public LocalDateTime getRegDate() {
        return regDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.REG_DATE
        * @param regDate  the value for API_COMMUNICATION_DATA.REG_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column API_COMMUNICATION_DATA.UPDATE_DATE
        * @return  the value of API_COMMUNICATION_DATA.UPDATE_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public LocalDateTime getUpdateDate() {
        return updateDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column API_COMMUNICATION_DATA.UPDATE_DATE
        * @param updateDate  the value for API_COMMUNICATION_DATA.UPDATE_DATE
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        @Override
        public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", transactionId=").append(transactionId);
        sb.append(", apiName=").append(apiName);
        sb.append(", httpMethod=").append(httpMethod);
        sb.append(", url=").append(url);
        sb.append(", body=").append(body);
        sb.append(", httpStatus=").append(httpStatus);
        sb.append(", detail=").append(detail);
        sb.append(", requestDate=").append(requestDate);
        sb.append(", responseDate=").append(responseDate);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", regDate=").append(regDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
        }

        /**
        * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        @Override
        public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ApiCommunicationData other = (ApiCommunicationData) that;
        return (this.getSeqApiCommunicationDataId() == null
                ? other.getSeqApiCommunicationDataId() == null
                : this.getSeqApiCommunicationDataId()
                        .equals(other.getSeqApiCommunicationDataId()))
                && (this.getTransactionId() == null ? other.getTransactionId() == null
                        : this.getTransactionId().equals(other.getTransactionId()))
                && (this.getApiName() == null ? other.getApiName() == null
                        : this.getApiName().equals(other.getApiName()))
                && (this.getHttpMethod() == null ? other.getHttpMethod() == null
                        : this.getHttpMethod().equals(other.getHttpMethod()))
                && (this.getUrl() == null ? other.getUrl() == null
                        : this.getUrl().equals(other.getUrl()))
                && (this.getBody() == null ? other.getBody() == null
                        : this.getBody().equals(other.getBody()))
                && (this.getHttpStatus() == null ? other.getHttpStatus() == null
                        : this.getHttpStatus().equals(other.getHttpStatus()))
                && (this.getDetail() == null ? other.getDetail() == null
                        : this.getDetail().equals(other.getDetail()))
                && (this.getRequestDate() == null ? other.getRequestDate() == null
                        : this.getRequestDate().equals(other.getRequestDate()))
                && (this.getResponseDate() == null ? other.getResponseDate() == null
                        : this.getResponseDate().equals(other.getResponseDate()))
                && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null
                        : this.getDeleteFlag().equals(other.getDeleteFlag()))
                && (this.getRegDate() == null ? other.getRegDate() == null
                        : this.getRegDate().equals(other.getRegDate()))
                && (this.getUpdateDate() == null ? other.getUpdateDate() == null
                        : this.getUpdateDate().equals(other.getUpdateDate()));
        }

        /**
        * This method was generated by MyBatis Generator. This method corresponds to the database table API_COMMUNICATION_DATA
        * @mbg.generated  Fri Dec 19 22:01:19 GMT+09:00 2025
        */
        @Override
        public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSeqApiCommunicationDataId() == null) ? 0
                : getSeqApiCommunicationDataId().hashCode());
        result = prime * result
                + ((getTransactionId() == null) ? 0 : getTransactionId().hashCode());
        result = prime * result + ((getApiName() == null) ? 0 : getApiName().hashCode());
        result = prime * result
                + ((getHttpMethod() == null) ? 0 : getHttpMethod().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getBody() == null) ? 0 : getBody().hashCode());
        result = prime * result
                + ((getHttpStatus() == null) ? 0 : getHttpStatus().hashCode());
        result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
        result = prime * result
                + ((getRequestDate() == null) ? 0 : getRequestDate().hashCode());
        result = prime * result
                + ((getResponseDate() == null) ? 0 : getResponseDate().hashCode());
        result = prime * result
                + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getRegDate() == null) ? 0 : getRegDate().hashCode());
        result = prime * result
                + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
        }

    @Ignore
        private static final long serialVersionUID = 1L;
}