package jp.co.ha.db.entity;

import java.io.Serializable;

import jp.co.ha.common.log.annotation.Ignore;

/**
 * API通信情報のPrimaryKey
 *
 * @version 1.0.0
 */
public class ApiCommunicationDataKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column api_communication_data.SEQ_API_COMMUNICATION_DATA_ID
     *
     * @mbg.generated Sun Feb 07 12:27:35 GMT+09:00 2021
     */
    private Integer seqApiCommunicationDataId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table api_communication_data
     *
     * @mbg.generated Sun Feb 07 12:27:35 GMT+09:00 2021
     */
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * api_communication_data.SEQ_API_COMMUNICATION_DATA_ID
     *
     * @return the value of api_communication_data.SEQ_API_COMMUNICATION_DATA_ID
     * @mbg.generated Sun Feb 07 12:27:35 GMT+09:00 2021
     */
    public Integer getSeqApiCommunicationDataId() {
        return seqApiCommunicationDataId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * api_communication_data.SEQ_API_COMMUNICATION_DATA_ID
     *
     * @param seqApiCommunicationDataId
     *     the value for api_communication_data.SEQ_API_COMMUNICATION_DATA_ID
     * @mbg.generated Sun Feb 07 12:27:35 GMT+09:00 2021
     */
    public void setSeqApiCommunicationDataId(Integer seqApiCommunicationDataId) {
        this.seqApiCommunicationDataId = seqApiCommunicationDataId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table api_communication_data
     *
     * @mbg.generated Sun Feb 07 12:27:35 GMT+09:00 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqApiCommunicationDataId=").append(seqApiCommunicationDataId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table api_communication_data
     *
     * @mbg.generated Sun Feb 07 12:27:35 GMT+09:00 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ApiCommunicationDataKey other = (ApiCommunicationDataKey) that;
        return (this.getSeqApiCommunicationDataId() == null
                ? other.getSeqApiCommunicationDataId() == null
                : this.getSeqApiCommunicationDataId()
                        .equals(other.getSeqApiCommunicationDataId()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table api_communication_data
     *
     * @mbg.generated Sun Feb 07 12:27:35 GMT+09:00 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSeqApiCommunicationDataId() == null) ? 0
                : getSeqApiCommunicationDataId().hashCode());
        return result;
    }
}