package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * BMI範囲マスタEntity
 *
 * @version 1.0.0
 */
@Entity
public class BmiRangeMt extends BmiRangeMtKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BMI_RANGE_MT.RANGE_MIN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Integer rangeMin;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BMI_RANGE_MT.RANGE_MAX
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Integer rangeMax;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BMI_RANGE_MT.OVER_WEIGHT_STATUS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String overWeightStatus;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BMI_RANGE_MT.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Boolean deleteFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BMI_RANGE_MT.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BMI_RANGE_MT.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime updateDate;
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BMI_RANGE_MT.RANGE_MIN
     * @return  the value of BMI_RANGE_MT.RANGE_MIN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Integer getRangeMin() {
        return rangeMin;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BMI_RANGE_MT.RANGE_MIN
     * @param rangeMin  the value for BMI_RANGE_MT.RANGE_MIN
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRangeMin(Integer rangeMin) {
        this.rangeMin = rangeMin;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BMI_RANGE_MT.RANGE_MAX
     * @return  the value of BMI_RANGE_MT.RANGE_MAX
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Integer getRangeMax() {
        return rangeMax;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BMI_RANGE_MT.RANGE_MAX
     * @param rangeMax  the value for BMI_RANGE_MT.RANGE_MAX
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRangeMax(Integer rangeMax) {
        this.rangeMax = rangeMax;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BMI_RANGE_MT.OVER_WEIGHT_STATUS
     * @return  the value of BMI_RANGE_MT.OVER_WEIGHT_STATUS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getOverWeightStatus() {
        return overWeightStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BMI_RANGE_MT.OVER_WEIGHT_STATUS
     * @param overWeightStatus  the value for BMI_RANGE_MT.OVER_WEIGHT_STATUS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setOverWeightStatus(String overWeightStatus) {
        this.overWeightStatus = overWeightStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BMI_RANGE_MT.DELETE_FLAG
     * @return  the value of BMI_RANGE_MT.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BMI_RANGE_MT.DELETE_FLAG
     * @param deleteFlag  the value for BMI_RANGE_MT.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BMI_RANGE_MT.REG_DATE
     * @return  the value of BMI_RANGE_MT.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BMI_RANGE_MT.REG_DATE
     * @param regDate  the value for BMI_RANGE_MT.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BMI_RANGE_MT.UPDATE_DATE
     * @return  the value of BMI_RANGE_MT.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BMI_RANGE_MT.UPDATE_DATE
     * @param updateDate  the value for BMI_RANGE_MT.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

}