package jp.co.ha.db.entity;

import java.io.Serializable;

/**
 * BMI範囲マスタのPrimaryKey
 *
 * @version 1.0.0
 */
public class BmiRangeMtKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BMI_RANGE_MT.SEQ_BMI_RANGE_MT_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Long seqBmiRangeMtId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BMI_RANGE_MT.SEQ_BMI_RANGE_MT_ID
     * @return  the value of BMI_RANGE_MT.SEQ_BMI_RANGE_MT_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Long getSeqBmiRangeMtId() {
        return seqBmiRangeMtId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BMI_RANGE_MT.SEQ_BMI_RANGE_MT_ID
     * @param seqBmiRangeMtId  the value for BMI_RANGE_MT.SEQ_BMI_RANGE_MT_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setSeqBmiRangeMtId(Long seqBmiRangeMtId) {
        this.seqBmiRangeMtId = seqBmiRangeMtId;
    }
}