package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * 健康情報ファイル設定情報
 *
 * @version 1.0.0
 */
@Entity
public class HealthInfoFileSetting extends HealthInfoFileSettingKey
        implements Serializable {

    /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column HEALTH_INFO_FILE_SETTING.HEADER_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        private Boolean headerFlag;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column HEALTH_INFO_FILE_SETTING.FOOTER_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        private Boolean footerFlag;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column HEALTH_INFO_FILE_SETTING.MASK_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        private Boolean maskFlag;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column HEALTH_INFO_FILE_SETTING.ENCLOSURE_CHAR_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        private Boolean enclosureCharFlag;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column HEALTH_INFO_FILE_SETTING.REG_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        private LocalDateTime regDate;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column HEALTH_INFO_FILE_SETTING.UPDATE_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        private LocalDateTime updateDate;
        @Ignore
        private static final long serialVersionUID = 1L;

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column HEALTH_INFO_FILE_SETTING.HEADER_FLAG
        * @return  the value of HEALTH_INFO_FILE_SETTING.HEADER_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public Boolean getHeaderFlag() {
        return headerFlag;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column HEALTH_INFO_FILE_SETTING.HEADER_FLAG
        * @param headerFlag  the value for HEALTH_INFO_FILE_SETTING.HEADER_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public void setHeaderFlag(Boolean headerFlag) {
        this.headerFlag = headerFlag;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column HEALTH_INFO_FILE_SETTING.FOOTER_FLAG
        * @return  the value of HEALTH_INFO_FILE_SETTING.FOOTER_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public Boolean getFooterFlag() {
        return footerFlag;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column HEALTH_INFO_FILE_SETTING.FOOTER_FLAG
        * @param footerFlag  the value for HEALTH_INFO_FILE_SETTING.FOOTER_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public void setFooterFlag(Boolean footerFlag) {
        this.footerFlag = footerFlag;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column HEALTH_INFO_FILE_SETTING.MASK_FLAG
        * @return  the value of HEALTH_INFO_FILE_SETTING.MASK_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public Boolean getMaskFlag() {
        return maskFlag;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column HEALTH_INFO_FILE_SETTING.MASK_FLAG
        * @param maskFlag  the value for HEALTH_INFO_FILE_SETTING.MASK_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public void setMaskFlag(Boolean maskFlag) {
        this.maskFlag = maskFlag;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column HEALTH_INFO_FILE_SETTING.ENCLOSURE_CHAR_FLAG
        * @return  the value of HEALTH_INFO_FILE_SETTING.ENCLOSURE_CHAR_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public Boolean getEnclosureCharFlag() {
        return enclosureCharFlag;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column HEALTH_INFO_FILE_SETTING.ENCLOSURE_CHAR_FLAG
        * @param enclosureCharFlag  the value for HEALTH_INFO_FILE_SETTING.ENCLOSURE_CHAR_FLAG
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public void setEnclosureCharFlag(Boolean enclosureCharFlag) {
        this.enclosureCharFlag = enclosureCharFlag;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column HEALTH_INFO_FILE_SETTING.REG_DATE
        * @return  the value of HEALTH_INFO_FILE_SETTING.REG_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public LocalDateTime getRegDate() {
        return regDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column HEALTH_INFO_FILE_SETTING.REG_DATE
        * @param regDate  the value for HEALTH_INFO_FILE_SETTING.REG_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column HEALTH_INFO_FILE_SETTING.UPDATE_DATE
        * @return  the value of HEALTH_INFO_FILE_SETTING.UPDATE_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public LocalDateTime getUpdateDate() {
        return updateDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column HEALTH_INFO_FILE_SETTING.UPDATE_DATE
        * @param updateDate  the value for HEALTH_INFO_FILE_SETTING.UPDATE_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
        }

}