package jp.co.ha.db.entity;

import java.io.Serializable;

/**
 * 健康情報のPrimaryKey
 *
 * @version 1.0.0
 */
public class HealthInfoKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HEALTH_INFO.SEQ_HEALTH_INFO_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Long seqHealthInfoId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HEALTH_INFO.SEQ_HEALTH_INFO_ID
     * @return  the value of HEALTH_INFO.SEQ_HEALTH_INFO_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Long getSeqHealthInfoId() {
        return seqHealthInfoId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HEALTH_INFO.SEQ_HEALTH_INFO_ID
     * @param seqHealthInfoId  the value for HEALTH_INFO.SEQ_HEALTH_INFO_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setSeqHealthInfoId(Long seqHealthInfoId) {
        this.seqHealthInfoId = seqHealthInfoId;
    }
}