package jp.co.ha.db.entity;

public class InquiryTypeMtKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_TYPE_MT.INQUIRY_TYPE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String inquiryType;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_TYPE_MT.INQUIRY_TYPE
     * @return  the value of INQUIRY_TYPE_MT.INQUIRY_TYPE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getInquiryType() {
        return inquiryType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_TYPE_MT.INQUIRY_TYPE
     * @param inquiryType  the value for INQUIRY_TYPE_MT.INQUIRY_TYPE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setInquiryType(String inquiryType) {
        this.inquiryType = inquiryType;
    }
}