package jp.co.ha.db.entity;

public class InquiryStatusMtKey {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_STATUS_MT.INQUIRY_STATUS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String inquiryStatus;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_STATUS_MT.INQUIRY_STATUS
     * @return  the value of INQUIRY_STATUS_MT.INQUIRY_STATUS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getInquiryStatus() {
        return inquiryStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_STATUS_MT.INQUIRY_STATUS
     * @param inquiryStatus  the value for INQUIRY_STATUS_MT.INQUIRY_STATUS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setInquiryStatus(String inquiryStatus) {
        this.inquiryStatus = inquiryStatus;
    }
}