package jp.co.ha.db.entity;

public class InquiryStatusMtKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiry_status_mt.INQUIRY_STATUS
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    private String inquiryStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiry_status_mt.INQUIRY_STATUS
     *
     * @return the value of inquiry_status_mt.INQUIRY_STATUS
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    public String getInquiryStatus() {
        return inquiryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiry_status_mt.INQUIRY_STATUS
     *
     * @param inquiryStatus the value for inquiry_status_mt.INQUIRY_STATUS
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    public void setInquiryStatus(String inquiryStatus) {
        this.inquiryStatus = inquiryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inquiryStatus=").append(inquiryStatus);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InquiryStatusMtKey other = (InquiryStatusMtKey) that;
        return (this.getInquiryStatus() == null ? other.getInquiryStatus() == null : this.getInquiryStatus().equals(other.getInquiryStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_status_mt
     *
     * @mbg.generated Sat Aug 09 10:51:26 GMT+09:00 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInquiryStatus() == null) ? 0 : getInquiryStatus().hashCode());
        return result;
    }
}