package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

@Entity
public class InquiryManagement extends InquiryManagementKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_MANAGEMENT.SEQ_USER_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Long seqUserId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_MANAGEMENT.S3_KEY
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String s3Key;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_MANAGEMENT.INQUIRY_STATUS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String inquiryStatus;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_MANAGEMENT.INQUIRY_TYPE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String inquiryType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_MANAGEMENT.TITLE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_MANAGEMENT.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Boolean deleteFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_MANAGEMENT.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_MANAGEMENT.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime updateDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_MANAGEMENT.RESPONDER_LOGIN_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Long responderLoginId;
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_MANAGEMENT.SEQ_USER_ID
     * @return  the value of INQUIRY_MANAGEMENT.SEQ_USER_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Long getSeqUserId() {
        return seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_MANAGEMENT.SEQ_USER_ID
     * @param seqUserId  the value for INQUIRY_MANAGEMENT.SEQ_USER_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setSeqUserId(Long seqUserId) {
        this.seqUserId = seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_MANAGEMENT.S3_KEY
     * @return  the value of INQUIRY_MANAGEMENT.S3_KEY
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getS3Key() {
        return s3Key;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_MANAGEMENT.S3_KEY
     * @param s3Key  the value for INQUIRY_MANAGEMENT.S3_KEY
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setS3Key(String s3Key) {
        this.s3Key = s3Key;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_MANAGEMENT.INQUIRY_STATUS
     * @return  the value of INQUIRY_MANAGEMENT.INQUIRY_STATUS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getInquiryStatus() {
        return inquiryStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_MANAGEMENT.INQUIRY_STATUS
     * @param inquiryStatus  the value for INQUIRY_MANAGEMENT.INQUIRY_STATUS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setInquiryStatus(String inquiryStatus) {
        this.inquiryStatus = inquiryStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_MANAGEMENT.INQUIRY_TYPE
     * @return  the value of INQUIRY_MANAGEMENT.INQUIRY_TYPE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getInquiryType() {
        return inquiryType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_MANAGEMENT.INQUIRY_TYPE
     * @param inquiryType  the value for INQUIRY_MANAGEMENT.INQUIRY_TYPE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setInquiryType(String inquiryType) {
        this.inquiryType = inquiryType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_MANAGEMENT.TITLE
     * @return  the value of INQUIRY_MANAGEMENT.TITLE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_MANAGEMENT.TITLE
     * @param title  the value for INQUIRY_MANAGEMENT.TITLE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_MANAGEMENT.DELETE_FLAG
     * @return  the value of INQUIRY_MANAGEMENT.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_MANAGEMENT.DELETE_FLAG
     * @param deleteFlag  the value for INQUIRY_MANAGEMENT.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_MANAGEMENT.REG_DATE
     * @return  the value of INQUIRY_MANAGEMENT.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_MANAGEMENT.REG_DATE
     * @param regDate  the value for INQUIRY_MANAGEMENT.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_MANAGEMENT.UPDATE_DATE
     * @return  the value of INQUIRY_MANAGEMENT.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_MANAGEMENT.UPDATE_DATE
     * @param updateDate  the value for INQUIRY_MANAGEMENT.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_MANAGEMENT.RESPONDER_LOGIN_ID
     * @return  the value of INQUIRY_MANAGEMENT.RESPONDER_LOGIN_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Long getResponderLoginId() {
        return responderLoginId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_MANAGEMENT.RESPONDER_LOGIN_ID
     * @param responderLoginId  the value for INQUIRY_MANAGEMENT.RESPONDER_LOGIN_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setResponderLoginId(Long responderLoginId) {
        this.responderLoginId = responderLoginId;
    }

}