package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

@Entity
public class InquiryTypeMt extends InquiryTypeMtKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiry_type_mt.NAME
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiry_type_mt.DESCRIPTION
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiry_type_mt.DISP_FLAG
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    private Boolean dispFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiry_type_mt.DISP_ORDER
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    private Integer dispOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiry_type_mt.DELETE_FLAG
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    private Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiry_type_mt.REG_DATE
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    private LocalDateTime regDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inquiry_type_mt.UPDATE_DATE
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    private LocalDateTime updateDate;

    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiry_type_mt.NAME
     *
     * @return the value of inquiry_type_mt.NAME
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiry_type_mt.NAME
     *
     * @param name the value for inquiry_type_mt.NAME
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiry_type_mt.DESCRIPTION
     *
     * @return the value of inquiry_type_mt.DESCRIPTION
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiry_type_mt.DESCRIPTION
     *
     * @param description the value for inquiry_type_mt.DESCRIPTION
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiry_type_mt.DISP_FLAG
     *
     * @return the value of inquiry_type_mt.DISP_FLAG
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public Boolean getDispFlag() {
        return dispFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiry_type_mt.DISP_FLAG
     *
     * @param dispFlag the value for inquiry_type_mt.DISP_FLAG
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public void setDispFlag(Boolean dispFlag) {
        this.dispFlag = dispFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiry_type_mt.DISP_ORDER
     *
     * @return the value of inquiry_type_mt.DISP_ORDER
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public Integer getDispOrder() {
        return dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiry_type_mt.DISP_ORDER
     *
     * @param dispOrder the value for inquiry_type_mt.DISP_ORDER
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public void setDispOrder(Integer dispOrder) {
        this.dispOrder = dispOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiry_type_mt.DELETE_FLAG
     *
     * @return the value of inquiry_type_mt.DELETE_FLAG
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiry_type_mt.DELETE_FLAG
     *
     * @param deleteFlag the value for inquiry_type_mt.DELETE_FLAG
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiry_type_mt.REG_DATE
     *
     * @return the value of inquiry_type_mt.REG_DATE
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiry_type_mt.REG_DATE
     *
     * @param regDate the value for inquiry_type_mt.REG_DATE
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inquiry_type_mt.UPDATE_DATE
     *
     * @return the value of inquiry_type_mt.UPDATE_DATE
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inquiry_type_mt.UPDATE_DATE
     *
     * @param updateDate the value for inquiry_type_mt.UPDATE_DATE
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_type_mt
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", dispFlag=").append(dispFlag);
        sb.append(", dispOrder=").append(dispOrder);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", regDate=").append(regDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_type_mt
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InquiryTypeMt other = (InquiryTypeMt) that;
        return (this.getInquiryType() == null ? other.getInquiryType() == null : this.getInquiryType().equals(other.getInquiryType()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getDispFlag() == null ? other.getDispFlag() == null : this.getDispFlag().equals(other.getDispFlag()))
            && (this.getDispOrder() == null ? other.getDispOrder() == null : this.getDispOrder().equals(other.getDispOrder()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getRegDate() == null ? other.getRegDate() == null : this.getRegDate().equals(other.getRegDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inquiry_type_mt
     *
     * @mbg.generated Sat Aug 09 09:17:29 GMT+09:00 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInquiryType() == null) ? 0 : getInquiryType().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getDispFlag() == null) ? 0 : getDispFlag().hashCode());
        result = prime * result + ((getDispOrder() == null) ? 0 : getDispOrder().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getRegDate() == null) ? 0 : getRegDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}