package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

@Entity
public class InquiryManagement extends InquiryManagementKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_management.SEQ_USER_ID
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    private Long seqUserId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_management.S3_KEY
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    private String s3Key;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_management.INQUIRY_STATUS
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    private String inquiryStatus;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_management.INQUIRY_TYPE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    private String inquiryType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_management.TITLE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_management.REG_DATE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_management.UPDATE_DATE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    private LocalDateTime updateDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_management.DELETE_FLAG
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    private Boolean deleteFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column inquiry_management.RESPONDER_LOGIN_ID
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    private Long responderLoginId;
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_management.SEQ_USER_ID
     * @return  the value of inquiry_management.SEQ_USER_ID
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public Long getSeqUserId() {
        return seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_management.SEQ_USER_ID
     * @param seqUserId  the value for inquiry_management.SEQ_USER_ID
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public void setSeqUserId(Long seqUserId) {
        this.seqUserId = seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_management.S3_KEY
     * @return  the value of inquiry_management.S3_KEY
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public String getS3Key() {
        return s3Key;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_management.S3_KEY
     * @param s3Key  the value for inquiry_management.S3_KEY
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public void setS3Key(String s3Key) {
        this.s3Key = s3Key;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_management.INQUIRY_STATUS
     * @return  the value of inquiry_management.INQUIRY_STATUS
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public String getInquiryStatus() {
        return inquiryStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_management.INQUIRY_STATUS
     * @param inquiryStatus  the value for inquiry_management.INQUIRY_STATUS
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public void setInquiryStatus(String inquiryStatus) {
        this.inquiryStatus = inquiryStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_management.INQUIRY_TYPE
     * @return  the value of inquiry_management.INQUIRY_TYPE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public String getInquiryType() {
        return inquiryType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_management.INQUIRY_TYPE
     * @param inquiryType  the value for inquiry_management.INQUIRY_TYPE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public void setInquiryType(String inquiryType) {
        this.inquiryType = inquiryType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_management.TITLE
     * @return  the value of inquiry_management.TITLE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_management.TITLE
     * @param title  the value for inquiry_management.TITLE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_management.REG_DATE
     * @return  the value of inquiry_management.REG_DATE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_management.REG_DATE
     * @param regDate  the value for inquiry_management.REG_DATE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_management.UPDATE_DATE
     * @return  the value of inquiry_management.UPDATE_DATE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_management.UPDATE_DATE
     * @param updateDate  the value for inquiry_management.UPDATE_DATE
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_management.DELETE_FLAG
     * @return  the value of inquiry_management.DELETE_FLAG
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_management.DELETE_FLAG
     * @param deleteFlag  the value for inquiry_management.DELETE_FLAG
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column inquiry_management.RESPONDER_LOGIN_ID
     * @return  the value of inquiry_management.RESPONDER_LOGIN_ID
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public Long getResponderLoginId() {
        return responderLoginId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column inquiry_management.RESPONDER_LOGIN_ID
     * @param responderLoginId  the value for inquiry_management.RESPONDER_LOGIN_ID
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    public void setResponderLoginId(Long responderLoginId) {
        this.responderLoginId = responderLoginId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqUserId=").append(seqUserId);
        sb.append(", s3Key=").append(s3Key);
        sb.append(", inquiryStatus=").append(inquiryStatus);
        sb.append(", inquiryType=").append(inquiryType);
        sb.append(", title=").append(title);
        sb.append(", regDate=").append(regDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", responderLoginId=").append(responderLoginId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InquiryManagement other = (InquiryManagement) that;
        return (this.getSeqInquiryMngId() == null ? other.getSeqInquiryMngId() == null
                : this.getSeqInquiryMngId().equals(other.getSeqInquiryMngId()))
                && (this.getSeqUserId() == null ? other.getSeqUserId() == null
                        : this.getSeqUserId().equals(other.getSeqUserId()))
                && (this.getS3Key() == null ? other.getS3Key() == null
                        : this.getS3Key().equals(other.getS3Key()))
                && (this.getInquiryStatus() == null ? other.getInquiryStatus() == null
                        : this.getInquiryStatus().equals(other.getInquiryStatus()))
                && (this.getInquiryType() == null ? other.getInquiryType() == null
                        : this.getInquiryType().equals(other.getInquiryType()))
                && (this.getTitle() == null ? other.getTitle() == null
                        : this.getTitle().equals(other.getTitle()))
                && (this.getRegDate() == null ? other.getRegDate() == null
                        : this.getRegDate().equals(other.getRegDate()))
                && (this.getUpdateDate() == null ? other.getUpdateDate() == null
                        : this.getUpdateDate().equals(other.getUpdateDate()))
                && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null
                        : this.getDeleteFlag().equals(other.getDeleteFlag()))
                && (this.getResponderLoginId() == null
                        ? other.getResponderLoginId() == null
                        : this.getResponderLoginId().equals(other.getResponderLoginId()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table inquiry_management
     * @mbg.generated  Sat Aug 09 09:24:25 GMT+09:00 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result
                + ((getSeqInquiryMngId() == null) ? 0 : getSeqInquiryMngId().hashCode());
        result = prime * result
                + ((getSeqUserId() == null) ? 0 : getSeqUserId().hashCode());
        result = prime * result + ((getS3Key() == null) ? 0 : getS3Key().hashCode());
        result = prime * result
                + ((getInquiryStatus() == null) ? 0 : getInquiryStatus().hashCode());
        result = prime * result
                + ((getInquiryType() == null) ? 0 : getInquiryType().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getRegDate() == null) ? 0 : getRegDate().hashCode());
        result = prime * result
                + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result
                + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getResponderLoginId() == null) ? 0
                : getResponderLoginId().hashCode());
        return result;
    }

}