package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

@Entity
public class InquiryStatusMt extends InquiryStatusMtKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_STATUS_MT.NAME
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_STATUS_MT.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Boolean deleteFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_STATUS_MT.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column INQUIRY_STATUS_MT.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime updateDate;
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_STATUS_MT.NAME
     * @return  the value of INQUIRY_STATUS_MT.NAME
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_STATUS_MT.NAME
     * @param name  the value for INQUIRY_STATUS_MT.NAME
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_STATUS_MT.DELETE_FLAG
     * @return  the value of INQUIRY_STATUS_MT.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_STATUS_MT.DELETE_FLAG
     * @param deleteFlag  the value for INQUIRY_STATUS_MT.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_STATUS_MT.REG_DATE
     * @return  the value of INQUIRY_STATUS_MT.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_STATUS_MT.REG_DATE
     * @param regDate  the value for INQUIRY_STATUS_MT.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column INQUIRY_STATUS_MT.UPDATE_DATE
     * @return  the value of INQUIRY_STATUS_MT.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column INQUIRY_STATUS_MT.UPDATE_DATE
     * @param updateDate  the value for INQUIRY_STATUS_MT.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

}