package jp.co.ha.db.entity;

import java.io.Serializable;

import jp.co.ha.common.log.annotation.Ignore;

/**
 * メール情報のPrimaryKey
 *
 * @version 1.0.0
 */
public class MailInfoKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column mail_info.USER_ID
     *
     * @mbg.generated Sun Apr 05 13:39:31 GMT+09:00 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table mail_info
     *
     * @mbg.generated Sun Apr 05 13:39:31 GMT+09:00 2020
     */
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column mail_info.USER_ID
     *
     * @return the value of mail_info.USER_ID
     * @mbg.generated Sun Apr 05 13:39:31 GMT+09:00 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column mail_info.USER_ID
     *
     * @param userId
     *     the value for mail_info.USER_ID
     * @mbg.generated Sun Apr 05 13:39:31 GMT+09:00 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table mail_info
     *
     * @mbg.generated Sun Apr 05 13:39:31 GMT+09:00 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table mail_info
     *
     * @mbg.generated Sun Apr 05 13:39:31 GMT+09:00 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MailInfoKey other = (MailInfoKey) that;
        return (this.getUserId() == null ? other.getUserId() == null
                : this.getUserId().equals(other.getUserId()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table mail_info
     *
     * @mbg.generated Sun Apr 05 13:39:31 GMT+09:00 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        return result;
    }
}