package jp.co.ha.db.entity;

import java.io.Serializable;

import jp.co.ha.common.log.annotation.Ignore;

/**
 * お知らせ情報PrimaryKey
 *
 * @version 1.0.0
 */
public class NewsInfoKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column news_info.SEQ_NEWS_INFO_ID
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    private Long seqNewsInfoId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column news_info.SEQ_NEWS_INFO_ID
     * @return  the value of news_info.SEQ_NEWS_INFO_ID
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public Long getSeqNewsInfoId() {
        return seqNewsInfoId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column news_info.SEQ_NEWS_INFO_ID
     * @param seqNewsInfoId  the value for news_info.SEQ_NEWS_INFO_ID
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public void setSeqNewsInfoId(Long seqNewsInfoId) {
        this.seqNewsInfoId = seqNewsInfoId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqNewsInfoId=").append(seqNewsInfoId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NewsInfoKey other = (NewsInfoKey) that;
        return (this.getSeqNewsInfoId() == null ? other.getSeqNewsInfoId() == null
                : this.getSeqNewsInfoId().equals(other.getSeqNewsInfoId()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table news_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result
                + ((getSeqNewsInfoId() == null) ? 0 : getSeqNewsInfoId().hashCode());
        return result;
    }
}