package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * お知らせ情報
 *
 * @version 1.0.0
 */
@Entity
public class NewsInfo extends NewsInfoKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column NEWS_INFO.S3_KEY
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String s3Key;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column NEWS_INFO.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Boolean deleteFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column NEWS_INFO.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column NEWS_INFO.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime updateDate;
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column NEWS_INFO.S3_KEY
     * @return  the value of NEWS_INFO.S3_KEY
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getS3Key() {
        return s3Key;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column NEWS_INFO.S3_KEY
     * @param s3Key  the value for NEWS_INFO.S3_KEY
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setS3Key(String s3Key) {
        this.s3Key = s3Key;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column NEWS_INFO.DELETE_FLAG
     * @return  the value of NEWS_INFO.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column NEWS_INFO.DELETE_FLAG
     * @param deleteFlag  the value for NEWS_INFO.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column NEWS_INFO.REG_DATE
     * @return  the value of NEWS_INFO.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column NEWS_INFO.REG_DATE
     * @param regDate  the value for NEWS_INFO.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column NEWS_INFO.UPDATE_DATE
     * @return  the value of NEWS_INFO.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column NEWS_INFO.UPDATE_DATE
     * @param updateDate  the value for NEWS_INFO.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

}