package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * 管理者サイト権限マスタ
 *
 * @version 1.0.0
 */
@Entity
public class RootRoleMt extends RootRoleMtKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column root_role_mt.ROLE
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    private String role;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column root_role_mt.ROLE_NAME
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    private String roleName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column root_role_mt.UPDATE_DATE
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    private LocalDateTime updateDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column root_role_mt.REG_DATE
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table root_role_mt
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column root_role_mt.ROLE
     * @return  the value of root_role_mt.ROLE
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column root_role_mt.ROLE
     * @param role  the value for root_role_mt.ROLE
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column root_role_mt.ROLE_NAME
     * @return  the value of root_role_mt.ROLE_NAME
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column root_role_mt.ROLE_NAME
     * @param roleName  the value for root_role_mt.ROLE_NAME
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column root_role_mt.UPDATE_DATE
     * @return  the value of root_role_mt.UPDATE_DATE
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column root_role_mt.UPDATE_DATE
     * @param updateDate  the value for root_role_mt.UPDATE_DATE
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column root_role_mt.REG_DATE
     * @return  the value of root_role_mt.REG_DATE
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column root_role_mt.REG_DATE
     * @param regDate  the value for root_role_mt.REG_DATE
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table root_role_mt
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", role=").append(role);
        sb.append(", roleName=").append(roleName);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", regDate=").append(regDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table root_role_mt
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RootRoleMt other = (RootRoleMt) that;
        return (this.getSeqRootRoleMtId() == null ? other.getSeqRootRoleMtId() == null
                : this.getSeqRootRoleMtId().equals(other.getSeqRootRoleMtId()))
                && (this.getRole() == null ? other.getRole() == null
                        : this.getRole().equals(other.getRole()))
                && (this.getRoleName() == null ? other.getRoleName() == null
                        : this.getRoleName().equals(other.getRoleName()))
                && (this.getUpdateDate() == null ? other.getUpdateDate() == null
                        : this.getUpdateDate().equals(other.getUpdateDate()))
                && (this.getRegDate() == null ? other.getRegDate() == null
                        : this.getRegDate().equals(other.getRegDate()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table root_role_mt
     * @mbg.generated  Sun Jan 10 15:29:38 GMT+09:00 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result
                + ((getSeqRootRoleMtId() == null) ? 0 : getSeqRootRoleMtId().hashCode());
        result = prime * result + ((getRole() == null) ? 0 : getRole().hashCode());
        result = prime * result
                + ((getRoleName() == null) ? 0 : getRoleName().hashCode());
        result = prime * result
                + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getRegDate() == null) ? 0 : getRegDate().hashCode());
        return result;
    }
}