package jp.co.ha.db.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * 管理者サイトユーザメモ情報Example
 *
 * @version 1.0.0
 */
public class RootUserNoteInfoExample extends BaseExample {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public RootUserNoteInfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2,
                String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException(
                        "Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqRootUserNoteInfoIdIsNull() {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andSeqRootUserNoteInfoIdIsNotNull() {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSeqRootUserNoteInfoIdEqualTo(Long value) {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID =", value, "seqRootUserNoteInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootUserNoteInfoIdNotEqualTo(Long value) {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID <>", value, "seqRootUserNoteInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootUserNoteInfoIdGreaterThan(Long value) {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID >", value, "seqRootUserNoteInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootUserNoteInfoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID >=", value, "seqRootUserNoteInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootUserNoteInfoIdLessThan(Long value) {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID <", value, "seqRootUserNoteInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootUserNoteInfoIdLessThanOrEqualTo(Long value) {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID <=", value, "seqRootUserNoteInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootUserNoteInfoIdIn(List<Long> values) {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID in", values,
                    "seqRootUserNoteInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootUserNoteInfoIdNotIn(List<Long> values) {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID not in", values,
                    "seqRootUserNoteInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootUserNoteInfoIdBetween(Long value1, Long value2) {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID between", value1, value2,
                    "seqRootUserNoteInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootUserNoteInfoIdNotBetween(Long value1, Long value2) {
            addCriterion("SEQ_ROOT_USER_NOTE_INFO_ID not between", value1, value2,
                    "seqRootUserNoteInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdIsNull() {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdIsNotNull() {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdEqualTo(Long value) {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID =", value, "seqRootLoginInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdNotEqualTo(Long value) {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID <>", value, "seqRootLoginInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdGreaterThan(Long value) {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID >", value, "seqRootLoginInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID >=", value, "seqRootLoginInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdLessThan(Long value) {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID <", value, "seqRootLoginInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdLessThanOrEqualTo(Long value) {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID <=", value, "seqRootLoginInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdIn(List<Long> values) {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID in", values, "seqRootLoginInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdNotIn(List<Long> values) {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID not in", values, "seqRootLoginInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdBetween(Long value1, Long value2) {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID between", value1, value2,
                    "seqRootLoginInfoId");
            return (Criteria) this;
        }

        public Criteria andSeqRootLoginInfoIdNotBetween(Long value1, Long value2) {
            addCriterion("SEQ_ROOT_LOGIN_INFO_ID not between", value1, value2,
                    "seqRootLoginInfoId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("TITLE =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("TITLE <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("TITLE >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("TITLE <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("TITLE like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("TITLE not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("TITLE in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("TITLE not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andS3KeyIsNull() {
            addCriterion("S3_KEY is null");
            return (Criteria) this;
        }

        public Criteria andS3KeyIsNotNull() {
            addCriterion("S3_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andS3KeyEqualTo(String value) {
            addCriterion("S3_KEY =", value, "s3Key");
            return (Criteria) this;
        }

        public Criteria andS3KeyNotEqualTo(String value) {
            addCriterion("S3_KEY <>", value, "s3Key");
            return (Criteria) this;
        }

        public Criteria andS3KeyGreaterThan(String value) {
            addCriterion("S3_KEY >", value, "s3Key");
            return (Criteria) this;
        }

        public Criteria andS3KeyGreaterThanOrEqualTo(String value) {
            addCriterion("S3_KEY >=", value, "s3Key");
            return (Criteria) this;
        }

        public Criteria andS3KeyLessThan(String value) {
            addCriterion("S3_KEY <", value, "s3Key");
            return (Criteria) this;
        }

        public Criteria andS3KeyLessThanOrEqualTo(String value) {
            addCriterion("S3_KEY <=", value, "s3Key");
            return (Criteria) this;
        }

        public Criteria andS3KeyLike(String value) {
            addCriterion("S3_KEY like", value, "s3Key");
            return (Criteria) this;
        }

        public Criteria andS3KeyNotLike(String value) {
            addCriterion("S3_KEY not like", value, "s3Key");
            return (Criteria) this;
        }

        public Criteria andS3KeyIn(List<String> values) {
            addCriterion("S3_KEY in", values, "s3Key");
            return (Criteria) this;
        }

        public Criteria andS3KeyNotIn(List<String> values) {
            addCriterion("S3_KEY not in", values, "s3Key");
            return (Criteria) this;
        }

        public Criteria andS3KeyBetween(String value1, String value2) {
            addCriterion("S3_KEY between", value1, value2, "s3Key");
            return (Criteria) this;
        }

        public Criteria andS3KeyNotBetween(String value1, String value2) {
            addCriterion("S3_KEY not between", value1, value2, "s3Key");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Boolean value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Boolean value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andRegDateIsNull() {
            addCriterion("REG_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRegDateIsNotNull() {
            addCriterion("REG_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRegDateEqualTo(LocalDateTime value) {
            addCriterion("REG_DATE =", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotEqualTo(LocalDateTime value) {
            addCriterion("REG_DATE <>", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateGreaterThan(LocalDateTime value) {
            addCriterion("REG_DATE >", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("REG_DATE >=", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateLessThan(LocalDateTime value) {
            addCriterion("REG_DATE <", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("REG_DATE <=", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateIn(List<LocalDateTime> values) {
            addCriterion("REG_DATE in", values, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotIn(List<LocalDateTime> values) {
            addCriterion("REG_DATE not in", values, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("REG_DATE between", value1, value2, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("REG_DATE not between", value1, value2, "regDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(LocalDateTime value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(LocalDateTime value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(LocalDateTime value1,
                LocalDateTime value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table ROOT_USER_NOTE_INFO
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue,
                String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to
     * the database table root_user_note_info
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 11 15:45:11 GMT+09:00
     * 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}