package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * 管理者サイトユーザログイン情報
 *
 * @version 1.0.0
 */
@Entity
public class RootLoginInfo extends RootLoginInfoKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_LOGIN_INFO.PASSWORD
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_LOGIN_INFO.PASSWORD_EXPIRE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDate passwordExpire;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_LOGIN_INFO.SEQ_ROOT_USER_ROLE_MNG_MT_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Long seqRootUserRoleMngMtId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_LOGIN_INFO.REMARKS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String remarks;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_LOGIN_INFO.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Boolean deleteFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_LOGIN_INFO.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_LOGIN_INFO.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime updateDate;
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_LOGIN_INFO.PASSWORD
     * @return  the value of ROOT_LOGIN_INFO.PASSWORD
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_LOGIN_INFO.PASSWORD
     * @param password  the value for ROOT_LOGIN_INFO.PASSWORD
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_LOGIN_INFO.PASSWORD_EXPIRE
     * @return  the value of ROOT_LOGIN_INFO.PASSWORD_EXPIRE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDate getPasswordExpire() {
        return passwordExpire;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_LOGIN_INFO.PASSWORD_EXPIRE
     * @param passwordExpire  the value for ROOT_LOGIN_INFO.PASSWORD_EXPIRE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setPasswordExpire(LocalDate passwordExpire) {
        this.passwordExpire = passwordExpire;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_LOGIN_INFO.SEQ_ROOT_USER_ROLE_MNG_MT_ID
     * @return  the value of ROOT_LOGIN_INFO.SEQ_ROOT_USER_ROLE_MNG_MT_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Long getSeqRootUserRoleMngMtId() {
        return seqRootUserRoleMngMtId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_LOGIN_INFO.SEQ_ROOT_USER_ROLE_MNG_MT_ID
     * @param seqRootUserRoleMngMtId  the value for ROOT_LOGIN_INFO.SEQ_ROOT_USER_ROLE_MNG_MT_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setSeqRootUserRoleMngMtId(Long seqRootUserRoleMngMtId) {
        this.seqRootUserRoleMngMtId = seqRootUserRoleMngMtId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_LOGIN_INFO.REMARKS
     * @return  the value of ROOT_LOGIN_INFO.REMARKS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_LOGIN_INFO.REMARKS
     * @param remarks  the value for ROOT_LOGIN_INFO.REMARKS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_LOGIN_INFO.DELETE_FLAG
     * @return  the value of ROOT_LOGIN_INFO.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_LOGIN_INFO.DELETE_FLAG
     * @param deleteFlag  the value for ROOT_LOGIN_INFO.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_LOGIN_INFO.REG_DATE
     * @return  the value of ROOT_LOGIN_INFO.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_LOGIN_INFO.REG_DATE
     * @param regDate  the value for ROOT_LOGIN_INFO.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_LOGIN_INFO.UPDATE_DATE
     * @return  the value of ROOT_LOGIN_INFO.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_LOGIN_INFO.UPDATE_DATE
     * @param updateDate  the value for ROOT_LOGIN_INFO.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

}