package jp.co.ha.db.entity;

import java.io.Serializable;

import jp.co.ha.common.log.annotation.Ignore;

/**
 * 管理者サイトユーザ権限詳細マスタPrimarykey
 *
 * @version 1.0.0
 */
public class RootUserRoleDetailMtKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column
     * root_user_role_detail_mt.SEQ_ROOT_USER_ROLE_DETAIL_MT_ID
     *
     * @mbg.generated Thu Feb 11 20:45:56 GMT+09:00 2021
     */
    private Integer seqRootUserRoleDetailMtId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table root_user_role_detail_mt
     *
     * @mbg.generated Thu Feb 11 20:45:56 GMT+09:00 2021
     */
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * root_user_role_detail_mt.SEQ_ROOT_USER_ROLE_DETAIL_MT_ID
     *
     * @return the value of
     * root_user_role_detail_mt.SEQ_ROOT_USER_ROLE_DETAIL_MT_ID
     * @mbg.generated Thu Feb 11 20:45:56 GMT+09:00 2021
     */
    public Integer getSeqRootUserRoleDetailMtId() {
        return seqRootUserRoleDetailMtId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * root_user_role_detail_mt.SEQ_ROOT_USER_ROLE_DETAIL_MT_ID
     *
     * @param seqRootUserRoleDetailMtId
     *     the value for
     *     root_user_role_detail_mt.SEQ_ROOT_USER_ROLE_DETAIL_MT_ID
     * @mbg.generated Thu Feb 11 20:45:56 GMT+09:00 2021
     */
    public void setSeqRootUserRoleDetailMtId(Integer seqRootUserRoleDetailMtId) {
        this.seqRootUserRoleDetailMtId = seqRootUserRoleDetailMtId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     *
     * @mbg.generated Thu Feb 11 20:45:56 GMT+09:00 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqRootUserRoleDetailMtId=").append(seqRootUserRoleDetailMtId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     *
     * @mbg.generated Thu Feb 11 20:45:56 GMT+09:00 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RootUserRoleDetailMtKey other = (RootUserRoleDetailMtKey) that;
        return (this.getSeqRootUserRoleDetailMtId() == null
                ? other.getSeqRootUserRoleDetailMtId() == null
                : this.getSeqRootUserRoleDetailMtId()
                        .equals(other.getSeqRootUserRoleDetailMtId()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table root_user_role_detail_mt
     *
     * @mbg.generated Thu Feb 11 20:45:56 GMT+09:00 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSeqRootUserRoleDetailMtId() == null) ? 0
                : getSeqRootUserRoleDetailMtId().hashCode());
        return result;
    }
}