package jp.co.ha.db.entity;

import java.io.Serializable;

/**
 * 管理者サイトユーザログイン情報のPrimaryKey
 *
 * @version 1.0.0
 */
public class RootLoginInfoKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_LOGIN_INFO.SEQ_ROOT_LOGIN_INFO_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Long seqRootLoginInfoId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_LOGIN_INFO.SEQ_ROOT_LOGIN_INFO_ID
     * @return  the value of ROOT_LOGIN_INFO.SEQ_ROOT_LOGIN_INFO_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Long getSeqRootLoginInfoId() {
        return seqRootLoginInfoId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_LOGIN_INFO.SEQ_ROOT_LOGIN_INFO_ID
     * @param seqRootLoginInfoId  the value for ROOT_LOGIN_INFO.SEQ_ROOT_LOGIN_INFO_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setSeqRootLoginInfoId(Long seqRootLoginInfoId) {
        this.seqRootLoginInfoId = seqRootLoginInfoId;
    }
}