package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * 管理者サイトユーザ権限詳細マスタ
 *
 * @version 1.0.0
 */
@Entity
public class RootUserRoleDetailMt extends RootUserRoleDetailMtKey
        implements Serializable {

    /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_USER_ROLE_DETAIL_MT.SEQ_ROOT_USER_ROLE_MNG_MT_ID
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        private Long seqRootUserRoleMngMtId;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_USER_ROLE_DETAIL_MT.SEQ_ROOT_ROLE_MT_ID
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        private Long seqRootRoleMtId;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_USER_ROLE_DETAIL_MT.REG_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        private LocalDateTime regDate;
        /**
        * This field was generated by MyBatis Generator. This field corresponds to the database column ROOT_USER_ROLE_DETAIL_MT.UPDATE_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        private LocalDateTime updateDate;
        @Ignore
        private static final long serialVersionUID = 1L;

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_USER_ROLE_DETAIL_MT.SEQ_ROOT_USER_ROLE_MNG_MT_ID
        * @return  the value of ROOT_USER_ROLE_DETAIL_MT.SEQ_ROOT_USER_ROLE_MNG_MT_ID
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public Long getSeqRootUserRoleMngMtId() {
        return seqRootUserRoleMngMtId;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_USER_ROLE_DETAIL_MT.SEQ_ROOT_USER_ROLE_MNG_MT_ID
        * @param seqRootUserRoleMngMtId  the value for ROOT_USER_ROLE_DETAIL_MT.SEQ_ROOT_USER_ROLE_MNG_MT_ID
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public void setSeqRootUserRoleMngMtId(Long seqRootUserRoleMngMtId) {
        this.seqRootUserRoleMngMtId = seqRootUserRoleMngMtId;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_USER_ROLE_DETAIL_MT.SEQ_ROOT_ROLE_MT_ID
        * @return  the value of ROOT_USER_ROLE_DETAIL_MT.SEQ_ROOT_ROLE_MT_ID
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public Long getSeqRootRoleMtId() {
        return seqRootRoleMtId;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_USER_ROLE_DETAIL_MT.SEQ_ROOT_ROLE_MT_ID
        * @param seqRootRoleMtId  the value for ROOT_USER_ROLE_DETAIL_MT.SEQ_ROOT_ROLE_MT_ID
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public void setSeqRootRoleMtId(Long seqRootRoleMtId) {
        this.seqRootRoleMtId = seqRootRoleMtId;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_USER_ROLE_DETAIL_MT.REG_DATE
        * @return  the value of ROOT_USER_ROLE_DETAIL_MT.REG_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public LocalDateTime getRegDate() {
        return regDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_USER_ROLE_DETAIL_MT.REG_DATE
        * @param regDate  the value for ROOT_USER_ROLE_DETAIL_MT.REG_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method returns the value of the database column ROOT_USER_ROLE_DETAIL_MT.UPDATE_DATE
        * @return  the value of ROOT_USER_ROLE_DETAIL_MT.UPDATE_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public LocalDateTime getUpdateDate() {
        return updateDate;
        }

        /**
        * This method was generated by MyBatis Generator. This method sets the value of the database column ROOT_USER_ROLE_DETAIL_MT.UPDATE_DATE
        * @param updateDate  the value for ROOT_USER_ROLE_DETAIL_MT.UPDATE_DATE
        * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
        */
        public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
        }

}