package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * 管理者サイトユーザメモ情報Entity
 *
 * @version 1.0.0
 */
@Entity
public class RootUserNoteInfo extends RootUserNoteInfoKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column root_user_note_info.SEQ_ROOT_LOGIN_INFO_ID
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    private Long seqRootLoginInfoId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column root_user_note_info.TITLE
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column root_user_note_info.S3_KEY
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    private String s3Key;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column root_user_note_info.UPDATE_DATE
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    private LocalDateTime updateDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column root_user_note_info.REG_DATE
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column root_user_note_info.DELETE_FLAG
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    private Boolean deleteFlag;
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column root_user_note_info.SEQ_ROOT_LOGIN_INFO_ID
     * @return  the value of root_user_note_info.SEQ_ROOT_LOGIN_INFO_ID
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public Long getSeqRootLoginInfoId() {
        return seqRootLoginInfoId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column root_user_note_info.SEQ_ROOT_LOGIN_INFO_ID
     * @param seqRootLoginInfoId  the value for root_user_note_info.SEQ_ROOT_LOGIN_INFO_ID
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public void setSeqRootLoginInfoId(Long seqRootLoginInfoId) {
        this.seqRootLoginInfoId = seqRootLoginInfoId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column root_user_note_info.TITLE
     * @return  the value of root_user_note_info.TITLE
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column root_user_note_info.TITLE
     * @param title  the value for root_user_note_info.TITLE
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column root_user_note_info.S3_KEY
     * @return  the value of root_user_note_info.S3_KEY
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public String getS3Key() {
        return s3Key;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column root_user_note_info.S3_KEY
     * @param s3Key  the value for root_user_note_info.S3_KEY
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public void setS3Key(String s3Key) {
        this.s3Key = s3Key;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column root_user_note_info.UPDATE_DATE
     * @return  the value of root_user_note_info.UPDATE_DATE
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column root_user_note_info.UPDATE_DATE
     * @param updateDate  the value for root_user_note_info.UPDATE_DATE
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column root_user_note_info.REG_DATE
     * @return  the value of root_user_note_info.REG_DATE
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column root_user_note_info.REG_DATE
     * @param regDate  the value for root_user_note_info.REG_DATE
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column root_user_note_info.DELETE_FLAG
     * @return  the value of root_user_note_info.DELETE_FLAG
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column root_user_note_info.DELETE_FLAG
     * @param deleteFlag  the value for root_user_note_info.DELETE_FLAG
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table root_user_note_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqRootLoginInfoId=").append(seqRootLoginInfoId);
        sb.append(", title=").append(title);
        sb.append(", s3Key=").append(s3Key);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", regDate=").append(regDate);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table root_user_note_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RootUserNoteInfo other = (RootUserNoteInfo) that;
        return (this.getSeqRootUserNoteInfoId() == null
                ? other.getSeqRootUserNoteInfoId() == null
                : this.getSeqRootUserNoteInfoId()
                        .equals(other.getSeqRootUserNoteInfoId()))
                && (this.getSeqRootLoginInfoId() == null
                        ? other.getSeqRootLoginInfoId() == null
                        : this.getSeqRootLoginInfoId()
                                .equals(other.getSeqRootLoginInfoId()))
                && (this.getTitle() == null ? other.getTitle() == null
                        : this.getTitle().equals(other.getTitle()))
                && (this.getS3Key() == null ? other.getS3Key() == null
                        : this.getS3Key().equals(other.getS3Key()))
                && (this.getUpdateDate() == null ? other.getUpdateDate() == null
                        : this.getUpdateDate().equals(other.getUpdateDate()))
                && (this.getRegDate() == null ? other.getRegDate() == null
                        : this.getRegDate().equals(other.getRegDate()))
                && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null
                        : this.getDeleteFlag().equals(other.getDeleteFlag()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table root_user_note_info
     * @mbg.generated  Mon Sep 01 11:22:18 GMT+09:00 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSeqRootUserNoteInfoId() == null) ? 0
                : getSeqRootUserNoteInfoId().hashCode());
        result = prime * result + ((getSeqRootLoginInfoId() == null) ? 0
                : getSeqRootLoginInfoId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getS3Key() == null) ? 0 : getS3Key().hashCode());
        result = prime * result
                + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getRegDate() == null) ? 0 : getRegDate().hashCode());
        result = prime * result
                + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        return result;
    }
}