package jp.co.ha.db.entity;

import java.io.Serializable;

/**
 * ユーザ回復トークン情報Primarykey
 *
 * @version 1.0.0
 */
public class UserRecoveryTokenKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER_RECOVERY_TOKEN.SEQ_USER_RECOVERY_TOKEN_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Long seqUserRecoveryTokenId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER_RECOVERY_TOKEN.SEQ_USER_RECOVERY_TOKEN_ID
     * @return  the value of USER_RECOVERY_TOKEN.SEQ_USER_RECOVERY_TOKEN_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Long getSeqUserRecoveryTokenId() {
        return seqUserRecoveryTokenId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER_RECOVERY_TOKEN.SEQ_USER_RECOVERY_TOKEN_ID
     * @param seqUserRecoveryTokenId  the value for USER_RECOVERY_TOKEN.SEQ_USER_RECOVERY_TOKEN_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setSeqUserRecoveryTokenId(Long seqUserRecoveryTokenId) {
        this.seqUserRecoveryTokenId = seqUserRecoveryTokenId;
    }
}