package jp.co.ha.db.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * ユーザ健康目標情報
 *
 * @version 1.0.0
 */
@Entity
public class UserHealthGoal extends UserHealthGoalKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER_HEALTH_GOAL.SEQ_USER_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Long seqUserId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER_HEALTH_GOAL.WEIGHT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private BigDecimal weight;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER_HEALTH_GOAL.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Boolean deleteFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER_HEALTH_GOAL.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER_HEALTH_GOAL.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime updateDate;
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER_HEALTH_GOAL.SEQ_USER_ID
     * @return  the value of USER_HEALTH_GOAL.SEQ_USER_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Long getSeqUserId() {
        return seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER_HEALTH_GOAL.SEQ_USER_ID
     * @param seqUserId  the value for USER_HEALTH_GOAL.SEQ_USER_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setSeqUserId(Long seqUserId) {
        this.seqUserId = seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER_HEALTH_GOAL.WEIGHT
     * @return  the value of USER_HEALTH_GOAL.WEIGHT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER_HEALTH_GOAL.WEIGHT
     * @param weight  the value for USER_HEALTH_GOAL.WEIGHT
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER_HEALTH_GOAL.DELETE_FLAG
     * @return  the value of USER_HEALTH_GOAL.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER_HEALTH_GOAL.DELETE_FLAG
     * @param deleteFlag  the value for USER_HEALTH_GOAL.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER_HEALTH_GOAL.REG_DATE
     * @return  the value of USER_HEALTH_GOAL.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER_HEALTH_GOAL.REG_DATE
     * @param regDate  the value for USER_HEALTH_GOAL.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER_HEALTH_GOAL.UPDATE_DATE
     * @return  the value of USER_HEALTH_GOAL.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER_HEALTH_GOAL.UPDATE_DATE
     * @param updateDate  the value for USER_HEALTH_GOAL.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

}