package jp.co.ha.db.entity;

import java.io.Serializable;

/**
 * ユーザ健康目標情報Primarykey
 *
 * @version 1.0.0
 */
public class UserHealthGoalKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER_HEALTH_GOAL.SEQ_HEALTH_GOAL_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Long seqHealthGoalId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER_HEALTH_GOAL.SEQ_HEALTH_GOAL_ID
     * @return  the value of USER_HEALTH_GOAL.SEQ_HEALTH_GOAL_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Long getSeqHealthGoalId() {
        return seqHealthGoalId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER_HEALTH_GOAL.SEQ_HEALTH_GOAL_ID
     * @param seqHealthGoalId  the value for USER_HEALTH_GOAL.SEQ_HEALTH_GOAL_ID
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setSeqHealthGoalId(Long seqHealthGoalId) {
        this.seqHealthGoalId = seqHealthGoalId;
    }
}