package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * ユーザ回復トークン情報
 *
 * @version 1.0.0
 */
@Entity
public class UserRecoveryToken extends UserRecoveryTokenKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column USER_RECOVERY_TOKEN.SEQ_USER_ID
     * 
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Long seqUserId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column USER_RECOVERY_TOKEN.TOKEN
     * 
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String token;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column USER_RECOVERY_TOKEN.TOKEN_CREATE_DATE
     * 
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime tokenCreateDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column USER_RECOVERY_TOKEN.DELETE_FLAG
     * 
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Boolean deleteFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column USER_RECOVERY_TOKEN.REG_DATE
     * 
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column USER_RECOVERY_TOKEN.UPDATE_DATE
     * 
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime updateDate;
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column USER_RECOVERY_TOKEN.SEQ_USER_ID
     * 
     * @return the value of USER_RECOVERY_TOKEN.SEQ_USER_ID
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Long getSeqUserId() {
        return seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column USER_RECOVERY_TOKEN.SEQ_USER_ID
     * 
     * @param seqUserId
     *     the value for USER_RECOVERY_TOKEN.SEQ_USER_ID
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setSeqUserId(Long seqUserId) {
        this.seqUserId = seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column USER_RECOVERY_TOKEN.TOKEN
     * 
     * @return the value of USER_RECOVERY_TOKEN.TOKEN
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column USER_RECOVERY_TOKEN.TOKEN
     * 
     * @param token
     *     the value for USER_RECOVERY_TOKEN.TOKEN
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column USER_RECOVERY_TOKEN.TOKEN_CREATE_DATE
     * 
     * @return the value of USER_RECOVERY_TOKEN.TOKEN_CREATE_DATE
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getTokenCreateDate() {
        return tokenCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column USER_RECOVERY_TOKEN.TOKEN_CREATE_DATE
     * 
     * @param tokenCreateDate
     *     the value for USER_RECOVERY_TOKEN.TOKEN_CREATE_DATE
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setTokenCreateDate(LocalDateTime tokenCreateDate) {
        this.tokenCreateDate = tokenCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column USER_RECOVERY_TOKEN.DELETE_FLAG
     * 
     * @return the value of USER_RECOVERY_TOKEN.DELETE_FLAG
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column USER_RECOVERY_TOKEN.DELETE_FLAG
     * 
     * @param deleteFlag
     *     the value for USER_RECOVERY_TOKEN.DELETE_FLAG
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column USER_RECOVERY_TOKEN.REG_DATE
     * 
     * @return the value of USER_RECOVERY_TOKEN.REG_DATE
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column USER_RECOVERY_TOKEN.REG_DATE
     * 
     * @param regDate
     *     the value for USER_RECOVERY_TOKEN.REG_DATE
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column USER_RECOVERY_TOKEN.UPDATE_DATE
     * 
     * @return the value of USER_RECOVERY_TOKEN.UPDATE_DATE
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column USER_RECOVERY_TOKEN.UPDATE_DATE
     * 
     * @param updateDate
     *     the value for USER_RECOVERY_TOKEN.UPDATE_DATE
     * @mbg.generated Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

}