package jp.co.ha.db.entity;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Crypt;
import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Mask;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * ユーザ情報
 *
 * @version 1.0.0
 */
@Entity
public class User extends UserKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER.PASSWORD
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    @Mask
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER.MAIL_ADDRESS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    @Mask
    @Crypt
    private String mailAddress;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Boolean deleteFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER.PASSWORD_EXPIRE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDate passwordExpire;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER.REMARKS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String remarks;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER.API_KEY
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private String apiKey;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDateTime updateDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER.GENDER_TYPE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private Integer genderType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column USER.BIRTH_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    private LocalDate birthDate;
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER.PASSWORD
     * @return  the value of USER.PASSWORD
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER.PASSWORD
     * @param password  the value for USER.PASSWORD
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER.MAIL_ADDRESS
     * @return  the value of USER.MAIL_ADDRESS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER.MAIL_ADDRESS
     * @param mailAddress  the value for USER.MAIL_ADDRESS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER.DELETE_FLAG
     * @return  the value of USER.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER.DELETE_FLAG
     * @param deleteFlag  the value for USER.DELETE_FLAG
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER.PASSWORD_EXPIRE
     * @return  the value of USER.PASSWORD_EXPIRE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDate getPasswordExpire() {
        return passwordExpire;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER.PASSWORD_EXPIRE
     * @param passwordExpire  the value for USER.PASSWORD_EXPIRE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setPasswordExpire(LocalDate passwordExpire) {
        this.passwordExpire = passwordExpire;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER.REMARKS
     * @return  the value of USER.REMARKS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER.REMARKS
     * @param remarks  the value for USER.REMARKS
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER.API_KEY
     * @return  the value of USER.API_KEY
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER.API_KEY
     * @param apiKey  the value for USER.API_KEY
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER.REG_DATE
     * @return  the value of USER.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER.REG_DATE
     * @param regDate  the value for USER.REG_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER.UPDATE_DATE
     * @return  the value of USER.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER.UPDATE_DATE
     * @param updateDate  the value for USER.UPDATE_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER.GENDER_TYPE
     * @return  the value of USER.GENDER_TYPE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Integer getGenderType() {
        return genderType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER.GENDER_TYPE
     * @param genderType  the value for USER.GENDER_TYPE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setGenderType(Integer genderType) {
        this.genderType = genderType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column USER.BIRTH_DATE
     * @return  the value of USER.BIRTH_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public LocalDate getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column USER.BIRTH_DATE
     * @param birthDate  the value for USER.BIRTH_DATE
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
    }

}