package jp.co.ha.db.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * ユーザ健康目標情報Example
 *
 * @version 1.0.0
 */
public class UserHealthGoalExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public UserHealthGoalExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2,
                String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException(
                        "Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqHealthGoalIdIsNull() {
            addCriterion("SEQ_HEALTH_GOAL_ID is null");
            return (Criteria) this;
        }

        public Criteria andSeqHealthGoalIdIsNotNull() {
            addCriterion("SEQ_HEALTH_GOAL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSeqHealthGoalIdEqualTo(Long value) {
            addCriterion("SEQ_HEALTH_GOAL_ID =", value, "seqHealthGoalId");
            return (Criteria) this;
        }

        public Criteria andSeqHealthGoalIdNotEqualTo(Long value) {
            addCriterion("SEQ_HEALTH_GOAL_ID <>", value, "seqHealthGoalId");
            return (Criteria) this;
        }

        public Criteria andSeqHealthGoalIdGreaterThan(Long value) {
            addCriterion("SEQ_HEALTH_GOAL_ID >", value, "seqHealthGoalId");
            return (Criteria) this;
        }

        public Criteria andSeqHealthGoalIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SEQ_HEALTH_GOAL_ID >=", value, "seqHealthGoalId");
            return (Criteria) this;
        }

        public Criteria andSeqHealthGoalIdLessThan(Long value) {
            addCriterion("SEQ_HEALTH_GOAL_ID <", value, "seqHealthGoalId");
            return (Criteria) this;
        }

        public Criteria andSeqHealthGoalIdLessThanOrEqualTo(Long value) {
            addCriterion("SEQ_HEALTH_GOAL_ID <=", value, "seqHealthGoalId");
            return (Criteria) this;
        }

        public Criteria andSeqHealthGoalIdIn(List<Long> values) {
            addCriterion("SEQ_HEALTH_GOAL_ID in", values, "seqHealthGoalId");
            return (Criteria) this;
        }

        public Criteria andSeqHealthGoalIdNotIn(List<Long> values) {
            addCriterion("SEQ_HEALTH_GOAL_ID not in", values, "seqHealthGoalId");
            return (Criteria) this;
        }

        public Criteria andSeqHealthGoalIdBetween(Long value1, Long value2) {
            addCriterion("SEQ_HEALTH_GOAL_ID between", value1, value2, "seqHealthGoalId");
            return (Criteria) this;
        }

        public Criteria andSeqHealthGoalIdNotBetween(Long value1, Long value2) {
            addCriterion("SEQ_HEALTH_GOAL_ID not between", value1, value2,
                    "seqHealthGoalId");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdIsNull() {
            addCriterion("SEQ_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdIsNotNull() {
            addCriterion("SEQ_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdEqualTo(Long value) {
            addCriterion("SEQ_USER_ID =", value, "seqUserId");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdNotEqualTo(Long value) {
            addCriterion("SEQ_USER_ID <>", value, "seqUserId");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdGreaterThan(Long value) {
            addCriterion("SEQ_USER_ID >", value, "seqUserId");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SEQ_USER_ID >=", value, "seqUserId");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdLessThan(Long value) {
            addCriterion("SEQ_USER_ID <", value, "seqUserId");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdLessThanOrEqualTo(Long value) {
            addCriterion("SEQ_USER_ID <=", value, "seqUserId");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdIn(List<Long> values) {
            addCriterion("SEQ_USER_ID in", values, "seqUserId");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdNotIn(List<Long> values) {
            addCriterion("SEQ_USER_ID not in", values, "seqUserId");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdBetween(Long value1, Long value2) {
            addCriterion("SEQ_USER_ID between", value1, value2, "seqUserId");
            return (Criteria) this;
        }

        public Criteria andSeqUserIdNotBetween(Long value1, Long value2) {
            addCriterion("SEQ_USER_ID not between", value1, value2, "seqUserId");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(BigDecimal value) {
            addCriterion("WEIGHT =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(BigDecimal value) {
            addCriterion("WEIGHT <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(BigDecimal value) {
            addCriterion("WEIGHT >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("WEIGHT >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(BigDecimal value) {
            addCriterion("WEIGHT <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("WEIGHT <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<BigDecimal> values) {
            addCriterion("WEIGHT in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<BigDecimal> values) {
            addCriterion("WEIGHT not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("WEIGHT between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("WEIGHT not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Boolean value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Boolean value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andRegDateIsNull() {
            addCriterion("REG_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRegDateIsNotNull() {
            addCriterion("REG_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRegDateEqualTo(LocalDateTime value) {
            addCriterion("REG_DATE =", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotEqualTo(LocalDateTime value) {
            addCriterion("REG_DATE <>", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateGreaterThan(LocalDateTime value) {
            addCriterion("REG_DATE >", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("REG_DATE >=", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateLessThan(LocalDateTime value) {
            addCriterion("REG_DATE <", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("REG_DATE <=", value, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateIn(List<LocalDateTime> values) {
            addCriterion("REG_DATE in", values, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotIn(List<LocalDateTime> values) {
            addCriterion("REG_DATE not in", values, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("REG_DATE between", value1, value2, "regDate");
            return (Criteria) this;
        }

        public Criteria andRegDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("REG_DATE not between", value1, value2, "regDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(LocalDateTime value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(LocalDateTime value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(LocalDateTime value1,
                LocalDateTime value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table USER_HEALTH_GOAL
     * @mbg.generated  Sat Feb 14 17:57:25 GMT+09:00 2026
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue,
                String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to
     * the database table user_health_goal
     *
     * @mbg.generated do_not_delete_during_merge Sun Jul 27 19:47:35 GMT+09:00
     * 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}