package jp.co.ha.db.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import jp.co.ha.common.db.annotation.Entity;
import jp.co.ha.common.log.annotation.Ignore;

/**
 * ユーザ健康目標情報
 *
 * @version 1.0.0
 */
@Entity
public class UserHealthGoal extends UserHealthGoalKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_health_goal.SEQ_USER_ID
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    private Long seqUserId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_health_goal.WEIGHT
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    private BigDecimal weight;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_health_goal.DELETE_FLAG
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    private Boolean deleteFlag;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_health_goal.REG_DATE
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    private LocalDateTime regDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user_health_goal.UPDATE_DATE
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    private LocalDateTime updateDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table user_health_goal
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user_health_goal.SEQ_USER_ID
     * @return  the value of user_health_goal.SEQ_USER_ID
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    public Long getSeqUserId() {
        return seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user_health_goal.SEQ_USER_ID
     * @param seqUserId  the value for user_health_goal.SEQ_USER_ID
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    public void setSeqUserId(Long seqUserId) {
        this.seqUserId = seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user_health_goal.WEIGHT
     * @return  the value of user_health_goal.WEIGHT
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user_health_goal.WEIGHT
     * @param weight  the value for user_health_goal.WEIGHT
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user_health_goal.DELETE_FLAG
     * @return  the value of user_health_goal.DELETE_FLAG
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user_health_goal.DELETE_FLAG
     * @param deleteFlag  the value for user_health_goal.DELETE_FLAG
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user_health_goal.REG_DATE
     * @return  the value of user_health_goal.REG_DATE
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    public LocalDateTime getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user_health_goal.REG_DATE
     * @param regDate  the value for user_health_goal.REG_DATE
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    public void setRegDate(LocalDateTime regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user_health_goal.UPDATE_DATE
     * @return  the value of user_health_goal.UPDATE_DATE
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user_health_goal.UPDATE_DATE
     * @param updateDate  the value for user_health_goal.UPDATE_DATE
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_health_goal
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqUserId=").append(seqUserId);
        sb.append(", weight=").append(weight);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", regDate=").append(regDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_health_goal
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserHealthGoal other = (UserHealthGoal) that;
        return (this.getSeqHealthGoalId() == null ? other.getSeqHealthGoalId() == null
                : this.getSeqHealthGoalId().equals(other.getSeqHealthGoalId()))
                && (this.getSeqUserId() == null ? other.getSeqUserId() == null
                        : this.getSeqUserId().equals(other.getSeqUserId()))
                && (this.getWeight() == null ? other.getWeight() == null
                        : this.getWeight().equals(other.getWeight()))
                && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null
                        : this.getDeleteFlag().equals(other.getDeleteFlag()))
                && (this.getRegDate() == null ? other.getRegDate() == null
                        : this.getRegDate().equals(other.getRegDate()))
                && (this.getUpdateDate() == null ? other.getUpdateDate() == null
                        : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_health_goal
     * @mbg.generated  Sat Aug 02 11:49:21 GMT+09:00 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result
                + ((getSeqHealthGoalId() == null) ? 0 : getSeqHealthGoalId().hashCode());
        result = prime * result
                + ((getSeqUserId() == null) ? 0 : getSeqUserId().hashCode());
        result = prime * result + ((getWeight() == null) ? 0 : getWeight().hashCode());
        result = prime * result
                + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getRegDate() == null) ? 0 : getRegDate().hashCode());
        result = prime * result
                + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}