package jp.co.ha.db.entity;

import java.io.Serializable;

import jp.co.ha.common.log.annotation.Ignore;

/**
 * ユーザ情報Primarykey
 *
 * @version 1.0.0
 */
public class UserKey implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.SEQ_USER_ID
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    private Long seqUserId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    @Ignore
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.SEQ_USER_ID
     * 
     * @return the value of user.SEQ_USER_ID
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    public Long getSeqUserId() {
        return seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.SEQ_USER_ID
     * 
     * @param seqUserId
     *     the value for user.SEQ_USER_ID
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    public void setSeqUserId(Long seqUserId) {
        this.seqUserId = seqUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqUserId=").append(seqUserId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserKey other = (UserKey) that;
        return (this.getSeqUserId() == null ? other.getSeqUserId() == null
                : this.getSeqUserId().equals(other.getSeqUserId()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     * 
     * @mbg.generated Sun Jul 20 14:33:36 GMT+09:00 2025
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result
                + ((getSeqUserId() == null) ? 0 : getSeqUserId().hashCode());
        return result;
    }
}