-- BMI_RANGE_MT
INSERT INTO BMI_RANGE_MT (
  RANGE_MIN, RANGE_MAX, OVER_WEIGHT_STATUS, UPDATE_DATE, REG_DATE
) VALUES (
  0, 18, 10, now(), now()
);

INSERT INTO BMI_RANGE_MT (
  RANGE_MIN, RANGE_MAX, OVER_WEIGHT_STATUS, UPDATE_DATE, REG_DATE
) VALUES (
  18, 25, 11, now(), now()
);

INSERT INTO BMI_RANGE_MT (
  RANGE_MIN, RANGE_MAX, OVER_WEIGHT_STATUS, UPDATE_DATE, REG_DATE
) VALUES (
  25, 30, 12, now(), now()
);

INSERT INTO BMI_RANGE_MT (
  RANGE_MIN, RANGE_MAX, OVER_WEIGHT_STATUS, UPDATE_DATE, REG_DATE
) VALUES (
  30, 35, 13, now(), now()
);

INSERT INTO BMI_RANGE_MT (
  RANGE_MIN, RANGE_MAX, OVER_WEIGHT_STATUS, UPDATE_DATE, REG_DATE
) VALUES (
  35, 40, 14, now(), now()
);

INSERT INTO BMI_RANGE_MT (
  RANGE_MIN, RANGE_MAX, OVER_WEIGHT_STATUS, UPDATE_DATE, REG_DATE
) VALUES (
  40, 999, 15, now(), now()
);
