-- アカウント回復トークン情報
CREATE TABLE IF NOT EXISTS ACCOUNT_RECOVERY_TOKEN_DATA (
  -- アカウント回復トークン情報ID
  SEQ_ACCOUNT_RECOVERY_TOKEN_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'アカウント回復トークン情報ID',
  -- ユーザID
  SEQ_USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
  -- トークン
  TOKEN VARCHAR(64) NOT NULL COMMENT 'トークン',
  -- トークン作成日時
  TOKEN_CREATE_DATE DATETIME NOT NULL COMMENT 'トークン作成日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);