-- API通信ログ
CREATE TABLE IF NOT EXISTS API_LOG (
  -- API通信ログID
  SEQ_API_LOG_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'API通信ログID',
  -- トランザクションID
  TRANSACTION_ID VARCHAR(36) NOT NULL COMMENT 'トランザクションID',
  -- API名
  API_NAME VARCHAR(64) NOT NULL COMMENT 'API名',
  -- HTTPメソッド
  HTTP_METHOD VARCHAR(16) NOT NULL COMMENT 'HTTPメソッド',
  -- URL
  URL VARCHAR(256) NOT NULL COMMENT 'URL',
  -- リクエストBody
  BODY VARCHAR(2048) COMMENT 'リクエストBody',
  -- HTTPステータス
  HTTP_STATUS INT COMMENT 'HTTPステータス',
  -- エラー詳細
  DETAIL VARCHAR(256) COMMENT 'エラー詳細',
  -- リクエスト送信日時
  REQUEST_DATE DATETIME NOT NULL COMMENT 'リクエスト送信日時',
  -- レスポンス受信日時
  RESPONSE_DATE DATETIME COMMENT 'レスポンス受信日時',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);