-- BMI範囲マスタ
CREATE TABLE IF NOT EXISTS BMI_RANGE_MT (
  -- BMI範囲マスタID
  SEQ_BMI_RANGE_MT_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'BMI範囲マスタID',
  -- 範囲下限
  RANGE_MIN INT NOT NULL COMMENT '範囲下限',
  -- 範囲上限
  RANGE_MAX INT NOT NULL COMMENT '範囲上限',
  -- 肥満度ステータス
  OVER_WEIGHT_STATUS VARCHAR(2) NOT NULL COMMENT '肥満度ステータス',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);