-- 健康情報ファイル設定
CREATE TABLE IF NOT EXISTS HEALTH_INFO_FILE_SETTING (
  -- ユーザID
  SEQ_USER_ID BIGINT NOT NULL PRIMARY KEY COMMENT 'ユーザID',
  -- ヘッダーフラグ
  HEADER_FLAG BOOLEAN COMMENT 'ヘッダーフラグ',
  -- フッターフラグ
  FOOTER_FLAG BOOLEAN COMMENT 'フッターフラグ',
  -- マスクフラグ
  MASK_FLAG BOOLEAN COMMENT 'マスクフラグ',
  -- 囲い文字利用フラグ
  ENCLOSURE_CHAR_FLAG BOOLEAN COMMENT '囲い文字利用フラグ',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);