-- 問い合わせ管理情報
CREATE TABLE IF NOT EXISTS INQUIRY_MANAGEMENT (
  -- 問い合わせID
  SEQ_INQUIRY_MNG_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '問い合わせID',
  -- ユーザID
  SEQ_USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
  -- S3キー
  S3_KEY VARCHAR(100) NOT NULL COMMENT 'S3キー',
  -- 問い合わせステータス
  INQUIRY_STATUS VARCHAR(2) NOT NULL COMMENT '問い合わせステータス',
  -- 問い合わせ種別
  INQUIRY_TYPE VARCHAR(2) COMMENT '問い合わせ種別',
  -- タイトル
  TITLE VARCHAR(100) NOT NULL COMMENT 'タイトル',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 対応者ログイン情報ID
  RESPONDER_LOGIN_ID BIGINT COMMENT '対応者ログイン情報ID'
);