-- 問い合わせ種別マスタ
CREATE TABLE IF NOT EXISTS INQUIRY_TYPE_MT (
  -- 問い合わせ種別
  INQUIRY_TYPE VARCHAR(2) NOT NULL PRIMARY KEY COMMENT '問い合わせ種別',
  -- 名前
  NAME VARCHAR(16) NOT NULL COMMENT '名前',
  -- 補足説明
  DESCRIPTION VARCHAR(64) COMMENT '補足説明',
  -- 表示フラグ
  DISP_FLAG BOOLEAN NOT NULL DEFAULT TRUE COMMENT '表示フラグ',
  -- 表示順
  DISP_ORDER INT NOT NULL COMMENT '表示順',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);