-- 問い合わせステータスマスタ
CREATE TABLE IF NOT EXISTS INQUIRY_STATUS_MT (
  -- 問い合わせステータス
  INQUIRY_STATUS VARCHAR(2) NOT NULL PRIMARY KEY COMMENT '問い合わせステータス',
  -- 名前
  NAME VARCHAR(16) NOT NULL COMMENT '名前',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);