-- 管理者サイトユーザ権限管理マスタ
CREATE TABLE IF NOT EXISTS ROOT_USER_ROLE_MNG_MT (
  -- 管理者サイトユーザ権限管理マスタID
  SEQ_ROOT_USER_ROLE_MNG_MT_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '管理者サイトユーザ権限管理マスタID',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時'
);