-- ユーザ情報
CREATE TABLE IF NOT EXISTS USER (
  -- ユーザID
  SEQ_USER_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'ユーザID',
  -- パスワード
  PASSWORD VARCHAR(64) NOT NULL COMMENT 'パスワード',
  -- メールアドレス
  MAIL_ADDRESS VARCHAR(512) NOT NULL COMMENT 'メールアドレス',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL DEFAULT FALSE COMMENT '削除フラグ',
  -- パスワード有効期限
  PASSWORD_EXPIRE DATE NOT NULL COMMENT 'パスワード有効期限',
  -- 備考
  REMARKS VARCHAR(256) COMMENT '備考',
  -- APIキー
  API_KEY VARCHAR(64) NOT NULL COMMENT 'APIキー',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時',
  -- 性別
  GENDER_TYPE INT NOT NULL DEFAULT 0 COMMENT '性別',
  -- 誕生日
  BIRTH_DATE DATE NOT NULL DEFAULT '2000/01/01' COMMENT '誕生日'
);