-- ユーザ健康目標情報
CREATE TABLE IF NOT EXISTS USER_HEALTH_GOAL (
  -- 目標ID
  SEQ_HEALTH_GOAL_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '目標ID',
  -- ユーザID
  SEQ_USER_ID BIGINT NOT NULL COMMENT 'ユーザID',
  -- 体重
  WEIGHT DECIMAL(6, 3) NOT NULL COMMENT '体重',
  -- 削除フラグ
  DELETE_FLAG BOOLEAN NOT NULL COMMENT '削除フラグ',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);