version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto25
    commands:
      - |
        java -version
        mvn -v

  build:
    commands:
      - |
        ls -ltr
        echo "env=${TARGET_MODULE}"
        cd ha-pom
        mvn -B -ntp -pl ../${TARGET_MODULE} -am clean test -Dgroups=!integration
        # mvn -B -ntp -f ha-pom/pom.xml -pl :${TARGET_MODULE} -am clean test -Dgroups=!integration

reports:
  junit_reports:
    files:
      - '**/target/surefire-reports/*.xml'
      - '**/target/failsafe-reports/*.xml'
    file-format: JUNITXML

cache:
  paths:
    - '/root/.m2/**/*'
