version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - python --version
      - pip --version
      - python -m pip install --upgrade pip
      - pip install -r ha_track/requirements.txt

  build:
    commands:
      - python ha_track/manage.py check
      - python ha_track/manage.py test -v 2

cache:
  paths:
    - '/root/.cache/pip/**/*'